CREATE TABLE IF NOT EXISTS diagram_annotations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  x REAL NOT NULL DEFAULT 0,
  y REAL NOT NULL DEFAULT 0,
  text TEXT NOT NULL DEFAULT 'Text',
  font_size INTEGER NOT NULL DEFAULT 14,
  color TEXT DEFAULT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
