import type { DiagramData, UpdatePositionsRequest, NodePrefs, LegendItem } from 'shared/types';
import { projectBase } from './base';

export async function fetchDiagram(projectId: number): Promise<DiagramData> {
  const res = await fetch(projectBase(projectId, 'diagram'));
  if (!res.ok) throw new Error('Failed to fetch diagram');
  return res.json();
}

export async function updatePositions(projectId: number, data: UpdatePositionsRequest): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/positions`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error('Failed to update positions');
}

export async function removeDeviceFromDiagram(projectId: number, deviceId: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/device/${deviceId}`, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to remove device from diagram');
}

export async function removeSubnetFromDiagram(projectId: number, subnetId: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/subnet/${subnetId}`, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to remove subnet from diagram');
}

export async function autoGenerateDiagram(projectId: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/auto-generate`, { method: 'POST' });
  if (!res.ok) throw new Error('Failed to auto-generate diagram');
}

export async function updateNodePrefs(projectId: number, nodeId: string, prefs: NodePrefs): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/node-preferences`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ nodeId, prefs }),
  });
  if (!res.ok) throw new Error('Failed to update node preferences');
}

export async function updateLegendItems(projectId: number, items: LegendItem[]): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/legend`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ items }),
  });
  if (!res.ok) throw new Error('Failed to update legend');
}
