import type { DiagramData, DiagramAnnotation, DiagramView, UpdatePositionsRequest, NodePrefs, LegendItem } from 'shared/types';
import { projectBase } from './base';

export async function fetchDiagram(projectId: number, viewId?: number): Promise<DiagramData> {
  const url = viewId ? `${projectBase(projectId, 'diagram')}?view_id=${viewId}` : projectBase(projectId, 'diagram');
  const res = await fetch(url);
  if (!res.ok) throw new Error('Failed to fetch diagram');
  return res.json();
}

export async function updatePositions(projectId: number, data: UpdatePositionsRequest, viewId?: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/positions`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ...data, view_id: viewId }),
  });
  if (!res.ok) throw new Error('Failed to update positions');
}

export async function removeDeviceFromDiagram(projectId: number, deviceId: number, viewId?: number): Promise<void> {
  const url = viewId ? `${projectBase(projectId, 'diagram')}/device/${deviceId}?view_id=${viewId}` : `${projectBase(projectId, 'diagram')}/device/${deviceId}`;
  const res = await fetch(url, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to remove device from diagram');
}

export async function removeSubnetFromDiagram(projectId: number, subnetId: number, viewId?: number): Promise<void> {
  const url = viewId ? `${projectBase(projectId, 'diagram')}/subnet/${subnetId}?view_id=${viewId}` : `${projectBase(projectId, 'diagram')}/subnet/${subnetId}`;
  const res = await fetch(url, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to remove subnet from diagram');
}

export async function autoGenerateDiagram(projectId: number, viewId?: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/auto-generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ view_id: viewId }),
  });
  if (!res.ok) throw new Error('Failed to auto-generate diagram');
}

export async function updateNodePrefs(projectId: number, nodeId: string, prefs: NodePrefs): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/node-preferences`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ nodeId, prefs }),
  });
  if (!res.ok) throw new Error('Failed to update node preferences');
}

export async function updateLegendItems(projectId: number, items: LegendItem[]): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/legend`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ items }),
  });
  if (!res.ok) throw new Error('Failed to update legend');
}

export async function createAnnotation(projectId: number, data: { x: number; y: number; text?: string; font_size?: number; color?: string | null; view_id?: number }): Promise<DiagramAnnotation> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/annotations`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error('Failed to create annotation');
  return res.json();
}

export async function updateAnnotation(projectId: number, id: number, data: Partial<{ x: number; y: number; text: string; font_size: number; color: string | null }>): Promise<DiagramAnnotation> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/annotations/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error('Failed to update annotation');
  return res.json();
}

export async function deleteAnnotation(projectId: number, id: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/annotations/${id}`, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to delete annotation');
}

// View CRUD
export async function fetchViews(projectId: number): Promise<DiagramView[]> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/views`);
  if (!res.ok) throw new Error('Failed to fetch views');
  return res.json();
}

export async function createView(projectId: number, name: string): Promise<DiagramView> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/views`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name }),
  });
  if (!res.ok) throw new Error('Failed to create view');
  return res.json();
}

export async function updateView(projectId: number, viewId: number, name: string): Promise<DiagramView> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/views/${viewId}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name }),
  });
  if (!res.ok) throw new Error('Failed to update view');
  return res.json();
}

export async function deleteView(projectId: number, viewId: number): Promise<void> {
  const res = await fetch(`${projectBase(projectId, 'diagram')}/views/${viewId}`, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to delete view');
}
