// AUTO-GENERATED by scripts/build-icon-libraries.ts. Do not edit by hand.

import type { DeviceType } from 'shared/types';

export interface DrawioShapeMapping {
  libraryId: string;
  iconKey: string;
  suggestedType?: DeviceType;
}

// Drawio shape keys are lowercase, with non-alphanumeric runs collapsed to
// underscores; matching is case-insensitive but values here are pre-lowered.
export const DRAWIO_SHAPE_MAP: Record<string, DrawioShapeMapping> = {
  "mxgraph.networks.router": {
    "libraryId": "network2018",
    "iconKey": "router",
    "suggestedType": "router"
  },
  "mxgraph.networks.switch": {
    "libraryId": "network2018",
    "iconKey": "switch",
    "suggestedType": "switch"
  },
  "mxgraph.networks.firewall": {
    "libraryId": "network2018",
    "iconKey": "firewall",
    "suggestedType": "firewall"
  },
  "mxgraph.networks.hub": {
    "libraryId": "network2018",
    "iconKey": "hub"
  },
  "mxgraph.networks.server": {
    "libraryId": "network2018",
    "iconKey": "server",
    "suggestedType": "server"
  },
  "mxgraph.networks.mainframe": {
    "libraryId": "network2018",
    "iconKey": "mainframe"
  },
  "mxgraph.networks.nas_filer": {
    "libraryId": "network2018",
    "iconKey": "nas",
    "suggestedType": "nas"
  },
  "mxgraph.networks.storage": {
    "libraryId": "network2018",
    "iconKey": "storage"
  },
  "mxgraph.networks.tape_storage": {
    "libraryId": "network2018",
    "iconKey": "tape_storage"
  },
  "mxgraph.networks.mail_server": {
    "libraryId": "network2018",
    "iconKey": "mail_server"
  },
  "mxgraph.networks.proxy_server": {
    "libraryId": "network2018",
    "iconKey": "proxy_server"
  },
  "mxgraph.networks.load_balancer": {
    "libraryId": "network2018",
    "iconKey": "load_balancer"
  },
  "mxgraph.networks.pc": {
    "libraryId": "network2018",
    "iconKey": "pc",
    "suggestedType": "workstation"
  },
  "mxgraph.networks.desktop_pc": {
    "libraryId": "network2018",
    "iconKey": "desktop_pc",
    "suggestedType": "workstation"
  },
  "mxgraph.networks.laptop": {
    "libraryId": "network2018",
    "iconKey": "laptop",
    "suggestedType": "workstation"
  },
  "mxgraph.networks.tablet": {
    "libraryId": "network2018",
    "iconKey": "tablet"
  },
  "mxgraph.networks.mobile": {
    "libraryId": "network2018",
    "iconKey": "mobile"
  },
  "mxgraph.networks.phone_1": {
    "libraryId": "network2018",
    "iconKey": "phone",
    "suggestedType": "phone"
  },
  "mxgraph.networks.printer": {
    "libraryId": "network2018",
    "iconKey": "printer"
  },
  "mxgraph.networks.monitor": {
    "libraryId": "network2018",
    "iconKey": "monitor"
  },
  "mxgraph.networks.cloud": {
    "libraryId": "network2018",
    "iconKey": "cloud"
  },
  "mxgraph.networks.modem": {
    "libraryId": "network2018",
    "iconKey": "modem"
  },
  "mxgraph.networks.rack": {
    "libraryId": "network2018",
    "iconKey": "rack"
  },
  "mxgraph.networks.security_camera": {
    "libraryId": "network2018",
    "iconKey": "camera",
    "suggestedType": "camera"
  },
  "mxgraph.networks.radio_tower": {
    "libraryId": "network2018",
    "iconKey": "radio_tower"
  },
  "mxgraph.networks.satellite_dish": {
    "libraryId": "network2018",
    "iconKey": "satellite_dish"
  },
  "mxgraph.networks.ups_enterprise": {
    "libraryId": "network2018",
    "iconKey": "ups"
  },
  "mxgraph.networks.biometric_reader": {
    "libraryId": "network2018",
    "iconKey": "biometric_reader"
  },
  "mxgraph.networks.business_center": {
    "libraryId": "network2018",
    "iconKey": "business_center"
  },
  "mxgraph.networks.community": {
    "libraryId": "network2018",
    "iconKey": "community"
  },
  "mxgraph.networks.comm_link": {
    "libraryId": "network2018",
    "iconKey": "comm_link"
  },
  "mxgraph.networks.copier": {
    "libraryId": "network2018",
    "iconKey": "copier"
  },
  "mxgraph.networks.dvr": {
    "libraryId": "network2018",
    "iconKey": "dvr"
  },
  "mxgraph.networks.external_storage": {
    "libraryId": "network2018",
    "iconKey": "external_storage"
  },
  "mxgraph.networks.gamepad": {
    "libraryId": "network2018",
    "iconKey": "gamepad"
  },
  "mxgraph.networks.patch_panel": {
    "libraryId": "network2018",
    "iconKey": "patch_panel"
  },
  "mxgraph.networks.phone_2": {
    "libraryId": "network2018",
    "iconKey": "phone_2"
  },
  "mxgraph.networks.satellite": {
    "libraryId": "network2018",
    "iconKey": "satellite"
  },
  "mxgraph.networks.scanner": {
    "libraryId": "network2018",
    "iconKey": "scanner"
  },
  "mxgraph.networks.secured": {
    "libraryId": "network2018",
    "iconKey": "secured"
  },
  "mxgraph.networks.server_storage": {
    "libraryId": "network2018",
    "iconKey": "server_storage"
  },
  "mxgraph.networks.supercomputer": {
    "libraryId": "network2018",
    "iconKey": "supercomputer"
  },
  "mxgraph.networks.terminal": {
    "libraryId": "network2018",
    "iconKey": "terminal"
  },
  "mxgraph.networks.unsecure": {
    "libraryId": "network2018",
    "iconKey": "unsecure"
  },
  "mxgraph.networks.ups_small": {
    "libraryId": "network2018",
    "iconKey": "ups_small"
  },
  "mxgraph.networks.usb_stick": {
    "libraryId": "network2018",
    "iconKey": "usb_stick"
  },
  "mxgraph.networks.users": {
    "libraryId": "network2018",
    "iconKey": "users"
  },
  "mxgraph.networks.user_female": {
    "libraryId": "network2018",
    "iconKey": "user_female"
  },
  "mxgraph.networks.user_male": {
    "libraryId": "network2018",
    "iconKey": "user_male"
  },
  "mxgraph.networks.video_projector": {
    "libraryId": "network2018",
    "iconKey": "video_projector"
  },
  "mxgraph.networks.video_projector_screen": {
    "libraryId": "network2018",
    "iconKey": "video_projector_screen"
  },
  "mxgraph.networks.virtual_pc": {
    "libraryId": "network2018",
    "iconKey": "virtual_pc"
  },
  "mxgraph.networks.virtual_server": {
    "libraryId": "network2018",
    "iconKey": "virtual_server"
  },
  "mxgraph.networks.virus": {
    "libraryId": "network2018",
    "iconKey": "virus"
  },
  "mxgraph.networks.web_server": {
    "libraryId": "network2018",
    "iconKey": "web_server"
  },
  "mxgraph.networks.wireless_hub": {
    "libraryId": "network2018",
    "iconKey": "wireless_hub"
  },
  "mxgraph.networks.wireless_modem": {
    "libraryId": "network2018",
    "iconKey": "wireless_modem"
  },
  "mxgraph.networks2.router": {
    "libraryId": "network2025",
    "iconKey": "router",
    "suggestedType": "router"
  },
  "mxgraph.networks2.firewall": {
    "libraryId": "network2025",
    "iconKey": "firewall",
    "suggestedType": "firewall"
  },
  "mxgraph.networks2.hub": {
    "libraryId": "network2025",
    "iconKey": "hub"
  },
  "mxgraph.networks2.server": {
    "libraryId": "network2025",
    "iconKey": "server",
    "suggestedType": "server"
  },
  "mxgraph.networks2.mainframe": {
    "libraryId": "network2025",
    "iconKey": "mainframe"
  },
  "mxgraph.networks2.global_server": {
    "libraryId": "network2025",
    "iconKey": "global_server"
  },
  "mxgraph.networks2.data_storage": {
    "libraryId": "network2025",
    "iconKey": "data_storage",
    "suggestedType": "nas"
  },
  "mxgraph.networks2.mail_server": {
    "libraryId": "network2025",
    "iconKey": "mail_server"
  },
  "mxgraph.networks2.load_balancer": {
    "libraryId": "network2025",
    "iconKey": "load_balancer"
  },
  "mxgraph.networks2.desktop_pc": {
    "libraryId": "network2025",
    "iconKey": "desktop_pc",
    "suggestedType": "workstation"
  },
  "mxgraph.networks2.laptop": {
    "libraryId": "network2025",
    "iconKey": "laptop",
    "suggestedType": "workstation"
  },
  "mxgraph.networks2.mobile_phone": {
    "libraryId": "network2025",
    "iconKey": "mobile_phone"
  },
  "mxgraph.networks2.modem": {
    "libraryId": "network2025",
    "iconKey": "modem"
  },
  "mxgraph.networks2.cloud": {
    "libraryId": "network2025",
    "iconKey": "cloud"
  },
  "mxgraph.networks2.internet": {
    "libraryId": "network2025",
    "iconKey": "internet"
  },
  "mxgraph.networks2.internet_security": {
    "libraryId": "network2025",
    "iconKey": "internet_security"
  },
  "mxgraph.networks2.lan": {
    "libraryId": "network2025",
    "iconKey": "lan"
  },
  "mxgraph.networks2.cctv": {
    "libraryId": "network2025",
    "iconKey": "cctv",
    "suggestedType": "camera"
  },
  "mxgraph.networks2.antenna": {
    "libraryId": "network2025",
    "iconKey": "antenna"
  },
  "mxgraph.networks2.biometric_reader": {
    "libraryId": "network2025",
    "iconKey": "biometric_reader"
  },
  "mxgraph.networks2.big_data": {
    "libraryId": "network2025",
    "iconKey": "big_data"
  },
  "mxgraph.networks2.encryption": {
    "libraryId": "network2025",
    "iconKey": "encryption"
  },
  "mxgraph.networks2.lock": {
    "libraryId": "network2025",
    "iconKey": "lock"
  },
  "mxgraph.networks2.mobile_network": {
    "libraryId": "network2025",
    "iconKey": "mobile_network"
  },
  "mxgraph.networks2.antenna_shadow": {
    "libraryId": "network2025",
    "iconKey": "antenna_shadow"
  },
  "mxgraph.networks2.application": {
    "libraryId": "network2025",
    "iconKey": "application"
  },
  "mxgraph.networks2.application_shadow": {
    "libraryId": "network2025",
    "iconKey": "application_shadow"
  },
  "mxgraph.networks2.big_data_shadow": {
    "libraryId": "network2025",
    "iconKey": "big_data_shadow"
  },
  "mxgraph.networks2.biohazard": {
    "libraryId": "network2025",
    "iconKey": "biohazard"
  },
  "mxgraph.networks2.biohazard_shadow": {
    "libraryId": "network2025",
    "iconKey": "biohazard_shadow"
  },
  "mxgraph.networks2.biometric_reader_shadow": {
    "libraryId": "network2025",
    "iconKey": "biometric_reader_shadow"
  },
  "mxgraph.networks2.cctv_shadow": {
    "libraryId": "network2025",
    "iconKey": "cctv_shadow"
  },
  "mxgraph.networks2.cloud_shadow": {
    "libraryId": "network2025",
    "iconKey": "cloud_shadow"
  },
  "mxgraph.networks2.community": {
    "libraryId": "network2025",
    "iconKey": "community"
  },
  "mxgraph.networks2.community_shadow": {
    "libraryId": "network2025",
    "iconKey": "community_shadow"
  },
  "mxgraph.networks2.copier": {
    "libraryId": "network2025",
    "iconKey": "copier"
  },
  "mxgraph.networks2.copier_shadow": {
    "libraryId": "network2025",
    "iconKey": "copier_shadow"
  },
  "mxgraph.networks2.data_management": {
    "libraryId": "network2025",
    "iconKey": "data_management"
  },
  "mxgraph.networks2.data_management_shadow": {
    "libraryId": "network2025",
    "iconKey": "data_management_shadow"
  },
  "mxgraph.networks2.data_storage_shadow": {
    "libraryId": "network2025",
    "iconKey": "data_storage_shadow"
  },
  "mxgraph.networks2.desktop_pc_shadow": {
    "libraryId": "network2025",
    "iconKey": "desktop_pc_shadow"
  },
  "mxgraph.networks2.encryption_shadow": {
    "libraryId": "network2025",
    "iconKey": "encryption_shadow"
  },
  "mxgraph.networks2.external_storage": {
    "libraryId": "network2025",
    "iconKey": "external_storage"
  },
  "mxgraph.networks2.external_storage_shadow": {
    "libraryId": "network2025",
    "iconKey": "external_storage_shadow"
  },
  "mxgraph.networks2.firewall_shadow": {
    "libraryId": "network2025",
    "iconKey": "firewall_shadow"
  },
  "mxgraph.networks2.gamepad": {
    "libraryId": "network2025",
    "iconKey": "gamepad"
  },
  "mxgraph.networks2.gamepad_shadow": {
    "libraryId": "network2025",
    "iconKey": "gamepad_shadow"
  },
  "mxgraph.networks2.global_server_shadow": {
    "libraryId": "network2025",
    "iconKey": "global_server_shadow"
  },
  "mxgraph.networks2.globe": {
    "libraryId": "network2025",
    "iconKey": "globe"
  },
  "mxgraph.networks2.globe_shadow": {
    "libraryId": "network2025",
    "iconKey": "globe_shadow"
  },
  "mxgraph.networks2.hub_shadow": {
    "libraryId": "network2025",
    "iconKey": "hub_shadow"
  },
  "mxgraph.networks2.internet_shadow": {
    "libraryId": "network2025",
    "iconKey": "internet_shadow"
  },
  "mxgraph.networks2.internet_security_shadow": {
    "libraryId": "network2025",
    "iconKey": "internet_security_shadow"
  },
  "mxgraph.networks2.lan_shadow": {
    "libraryId": "network2025",
    "iconKey": "lan_shadow"
  },
  "mxgraph.networks2.laptop_shadow": {
    "libraryId": "network2025",
    "iconKey": "laptop_shadow"
  },
  "mxgraph.networks2.load_balancer_shadow": {
    "libraryId": "network2025",
    "iconKey": "load_balancer_shadow"
  },
  "mxgraph.networks2.lock_shadow": {
    "libraryId": "network2025",
    "iconKey": "lock_shadow"
  },
  "mxgraph.networks2.mail_server_shadow": {
    "libraryId": "network2025",
    "iconKey": "mail_server_shadow"
  },
  "mxgraph.networks2.mainframe_shadow": {
    "libraryId": "network2025",
    "iconKey": "mainframe_shadow"
  },
  "mxgraph.networks2.mobile_network_shadow": {
    "libraryId": "network2025",
    "iconKey": "mobile_network_shadow"
  },
  "mxgraph.networks2.mobile_phone_shadow": {
    "libraryId": "network2025",
    "iconKey": "mobile_phone_shadow"
  },
  "mxgraph.networks2.modem_shadow": {
    "libraryId": "network2025",
    "iconKey": "modem_shadow"
  },
  "mxgraph.networks2.monitor": {
    "libraryId": "network2025",
    "iconKey": "monitor"
  },
  "mxgraph.networks2.monitor_shadow": {
    "libraryId": "network2025",
    "iconKey": "monitor_shadow"
  },
  "mxgraph.networks2.nas_filer": {
    "libraryId": "network2025",
    "iconKey": "nas_filer"
  },
  "mxgraph.networks2.nas_filer_shadow": {
    "libraryId": "network2025",
    "iconKey": "nas_filer_shadow"
  },
  "mxgraph.networks2.network": {
    "libraryId": "network2025",
    "iconKey": "network"
  },
  "mxgraph.networks2.network_shadow": {
    "libraryId": "network2025",
    "iconKey": "network_shadow"
  },
  "mxgraph.networks2.network_security": {
    "libraryId": "network2025",
    "iconKey": "network_security"
  },
  "mxgraph.networks2.network_security_shadow": {
    "libraryId": "network2025",
    "iconKey": "network_security_shadow"
  },
  "mxgraph.networks2.patch_panel": {
    "libraryId": "network2025",
    "iconKey": "patch_panel"
  },
  "mxgraph.networks2.patch_panel_shadow": {
    "libraryId": "network2025",
    "iconKey": "patch_panel_shadow"
  },
  "mxgraph.networks2.pc": {
    "libraryId": "network2025",
    "iconKey": "pc"
  },
  "mxgraph.networks2.pc_shadow": {
    "libraryId": "network2025",
    "iconKey": "pc_shadow"
  },
  "mxgraph.networks2.phone": {
    "libraryId": "network2025",
    "iconKey": "phone"
  },
  "mxgraph.networks2.phone_shadow": {
    "libraryId": "network2025",
    "iconKey": "phone_shadow"
  },
  "mxgraph.networks2.printer": {
    "libraryId": "network2025",
    "iconKey": "printer"
  },
  "mxgraph.networks2.printer_shadow": {
    "libraryId": "network2025",
    "iconKey": "printer_shadow"
  },
  "mxgraph.networks2.projector_canvas": {
    "libraryId": "network2025",
    "iconKey": "projector_canvas"
  },
  "mxgraph.networks2.projector_canvas_shadow": {
    "libraryId": "network2025",
    "iconKey": "projector_canvas_shadow"
  },
  "mxgraph.networks2.rack_cabinet": {
    "libraryId": "network2025",
    "iconKey": "rack_cabinet"
  },
  "mxgraph.networks2.rack_cabinet_shadow": {
    "libraryId": "network2025",
    "iconKey": "rack_cabinet_shadow"
  },
  "mxgraph.networks2.router_shadow": {
    "libraryId": "network2025",
    "iconKey": "router_shadow"
  },
  "mxgraph.networks2.satellite_dish": {
    "libraryId": "network2025",
    "iconKey": "satellite_dish"
  },
  "mxgraph.networks2.satellite_dish_shadow": {
    "libraryId": "network2025",
    "iconKey": "satellite_dish_shadow"
  },
  "mxgraph.networks2.satellite": {
    "libraryId": "network2025",
    "iconKey": "satellite"
  },
  "mxgraph.networks2.satellite_shadow": {
    "libraryId": "network2025",
    "iconKey": "satellite_shadow"
  },
  "mxgraph.networks2.scanner": {
    "libraryId": "network2025",
    "iconKey": "scanner"
  },
  "mxgraph.networks2.scanner_shadow": {
    "libraryId": "network2025",
    "iconKey": "scanner_shadow"
  },
  "mxgraph.networks2.server_shadow": {
    "libraryId": "network2025",
    "iconKey": "server_shadow"
  },
  "mxgraph.networks2.social_media": {
    "libraryId": "network2025",
    "iconKey": "social_media"
  },
  "mxgraph.networks2.social_media_shadow": {
    "libraryId": "network2025",
    "iconKey": "social_media_shadow"
  },
  "mxgraph.networks2.tablet": {
    "libraryId": "network2025",
    "iconKey": "tablet"
  },
  "mxgraph.networks2.tablet_shadow": {
    "libraryId": "network2025",
    "iconKey": "tablet_shadow"
  },
  "mxgraph.networks2.terminal": {
    "libraryId": "network2025",
    "iconKey": "terminal"
  },
  "mxgraph.networks2.terminal_shadow": {
    "libraryId": "network2025",
    "iconKey": "terminal_shadow"
  },
  "mxgraph.networks2.threat": {
    "libraryId": "network2025",
    "iconKey": "threat"
  },
  "mxgraph.networks2.threat_shadow": {
    "libraryId": "network2025",
    "iconKey": "threat_shadow"
  },
  "mxgraph.networks2.ups": {
    "libraryId": "network2025",
    "iconKey": "ups"
  },
  "mxgraph.networks2.ups_shadow": {
    "libraryId": "network2025",
    "iconKey": "ups_shadow"
  },
  "mxgraph.networks2.user_female": {
    "libraryId": "network2025",
    "iconKey": "user_female"
  },
  "mxgraph.networks2.user_female_shadow": {
    "libraryId": "network2025",
    "iconKey": "user_female_shadow"
  },
  "mxgraph.networks2.user_male": {
    "libraryId": "network2025",
    "iconKey": "user_male"
  },
  "mxgraph.networks2.user_male_shadow": {
    "libraryId": "network2025",
    "iconKey": "user_male_shadow"
  },
  "mxgraph.networks2.users": {
    "libraryId": "network2025",
    "iconKey": "users"
  },
  "mxgraph.networks2.users_shadow": {
    "libraryId": "network2025",
    "iconKey": "users_shadow"
  },
  "mxgraph.networks2.video_projector": {
    "libraryId": "network2025",
    "iconKey": "video_projector"
  },
  "mxgraph.networks2.video_projector_shadow": {
    "libraryId": "network2025",
    "iconKey": "video_projector_shadow"
  },
  "mxgraph.networks2.vr": {
    "libraryId": "network2025",
    "iconKey": "vr"
  },
  "mxgraph.networks2.vr_shadow": {
    "libraryId": "network2025",
    "iconKey": "vr_shadow"
  },
  "mxgraph.networks2.web_hosting": {
    "libraryId": "network2025",
    "iconKey": "web_hosting"
  },
  "mxgraph.networks2.web_hosting_shadow": {
    "libraryId": "network2025",
    "iconKey": "web_hosting_shadow"
  },
  "mxgraph.networks2.wireless_hub": {
    "libraryId": "network2025",
    "iconKey": "wireless_hub"
  },
  "mxgraph.networks2.wireless_hub_shadow": {
    "libraryId": "network2025",
    "iconKey": "wireless_hub_shadow"
  },
  "mxgraph.cisco.routers.router": {
    "libraryId": "cisco",
    "iconKey": "router",
    "suggestedType": "router"
  },
  "mxgraph.cisco.routers.broadcast_router": {
    "libraryId": "cisco",
    "iconKey": "broadcast_router"
  },
  "mxgraph.cisco.switches.layer_3_switch": {
    "libraryId": "cisco",
    "iconKey": "l3_switch",
    "suggestedType": "switch"
  },
  "mxgraph.cisco.switches.multilayer_remote_switch": {
    "libraryId": "cisco",
    "iconKey": "l2_switch",
    "suggestedType": "switch"
  },
  "mxgraph.cisco.switches.atm_switch": {
    "libraryId": "cisco",
    "iconKey": "atm_switch"
  },
  "mxgraph.cisco.security.firewall": {
    "libraryId": "cisco",
    "iconKey": "firewall",
    "suggestedType": "firewall"
  },
  "mxgraph.cisco.security.pix_firewall": {
    "libraryId": "cisco",
    "iconKey": "pix_firewall"
  },
  "mxgraph.cisco.security.lock": {
    "libraryId": "cisco",
    "iconKey": "lock"
  },
  "mxgraph.cisco.security.network_security": {
    "libraryId": "cisco",
    "iconKey": "network_security"
  },
  "mxgraph.cisco.servers.server_with_router": {
    "libraryId": "cisco",
    "iconKey": "server_with_router"
  },
  "mxgraph.cisco.servers.fileserver": {
    "libraryId": "cisco",
    "iconKey": "fileserver"
  },
  "mxgraph.cisco.servers.file_server": {
    "libraryId": "cisco",
    "iconKey": "file_server"
  },
  "mxgraph.cisco.servers.host": {
    "libraryId": "cisco",
    "iconKey": "host",
    "suggestedType": "server"
  },
  "mxgraph.cisco.servers.iptv_server": {
    "libraryId": "cisco",
    "iconKey": "iptv_server"
  },
  "mxgraph.cisco.computers_and_peripherals.pc": {
    "libraryId": "cisco",
    "iconKey": "pc",
    "suggestedType": "workstation"
  },
  "mxgraph.cisco.computers_and_peripherals.macintosh": {
    "libraryId": "cisco",
    "iconKey": "macintosh",
    "suggestedType": "workstation"
  },
  "mxgraph.cisco.computers_and_peripherals.laptop": {
    "libraryId": "cisco",
    "iconKey": "laptop",
    "suggestedType": "workstation"
  },
  "mxgraph.cisco.computers_and_peripherals.printer": {
    "libraryId": "cisco",
    "iconKey": "printer"
  },
  "mxgraph.cisco.computers_and_peripherals.ibm_mainframe": {
    "libraryId": "cisco",
    "iconKey": "mainframe"
  },
  "mxgraph.cisco.wireless.antenna": {
    "libraryId": "cisco",
    "iconKey": "antenna"
  },
  "mxgraph.cisco.wireless.wireless": {
    "libraryId": "cisco",
    "iconKey": "wireless"
  },
  "mxgraph.cisco.wireless.wireless_bridge": {
    "libraryId": "cisco",
    "iconKey": "wireless_bridge"
  },
  "mxgraph.cisco.wireless.radio_tower": {
    "libraryId": "cisco",
    "iconKey": "radio_tower"
  },
  "mxgraph.cisco.wireless.satellite_dish": {
    "libraryId": "cisco",
    "iconKey": "satellite_dish"
  },
  "mxgraph.cisco.storage.cloud": {
    "libraryId": "cisco",
    "iconKey": "cloud"
  },
  "mxgraph.cisco.storage.tape_array": {
    "libraryId": "cisco",
    "iconKey": "tape_array"
  },
  "mxgraph.cisco.routers.10700": {
    "libraryId": "cisco",
    "iconKey": "10700"
  },
  "mxgraph.cisco.routers.atm_router": {
    "libraryId": "cisco",
    "iconKey": "atm_router"
  },
  "mxgraph.cisco.routers.atm_tag_switch_router": {
    "libraryId": "cisco",
    "iconKey": "atm_tag_switch_router"
  },
  "mxgraph.cisco.routers.content_service_router": {
    "libraryId": "cisco",
    "iconKey": "content_service_router"
  },
  "mxgraph.cisco.routers.gigabit_switch_atm_tag_router": {
    "libraryId": "cisco",
    "iconKey": "gigabit_switch_atm_tag_router"
  },
  "mxgraph.cisco.routers.iad_router": {
    "libraryId": "cisco",
    "iconKey": "iad_router"
  },
  "mxgraph.cisco.routers.ip_telephony_router": {
    "libraryId": "cisco",
    "iconKey": "ip_telephony_router"
  },
  "mxgraph.cisco.routers.isci_router": {
    "libraryId": "cisco",
    "iconKey": "isci_router"
  },
  "mxgraph.cisco.routers.mobile_access_router": {
    "libraryId": "cisco",
    "iconKey": "mobile_access_router"
  },
  "mxgraph.cisco.routers.nce_router": {
    "libraryId": "cisco",
    "iconKey": "nce_router"
  },
  "mxgraph.cisco.routers.netflow_router": {
    "libraryId": "cisco",
    "iconKey": "netflow_router"
  },
  "mxgraph.cisco.routers.optical_services_router": {
    "libraryId": "cisco",
    "iconKey": "optical_services_router"
  },
  "mxgraph.cisco.routers.router_in_building": {
    "libraryId": "cisco",
    "iconKey": "router_in_building"
  },
  "mxgraph.cisco.routers.router_with_silicon_switch": {
    "libraryId": "cisco",
    "iconKey": "router_with_silicon_switch"
  },
  "mxgraph.cisco.routers.service_router": {
    "libraryId": "cisco",
    "iconKey": "service_router"
  },
  "mxgraph.cisco.routers.space_router": {
    "libraryId": "cisco",
    "iconKey": "space_router"
  },
  "mxgraph.cisco.routers.storage_router": {
    "libraryId": "cisco",
    "iconKey": "storage_router"
  },
  "mxgraph.cisco.routers.tdm_router": {
    "libraryId": "cisco",
    "iconKey": "tdm_router"
  },
  "mxgraph.cisco.routers.voice_router": {
    "libraryId": "cisco",
    "iconKey": "voice_router"
  },
  "mxgraph.cisco.routers.wavelength_router": {
    "libraryId": "cisco",
    "iconKey": "wavelength_router"
  },
  "mxgraph.cisco.routers.wireless_router": {
    "libraryId": "cisco",
    "iconKey": "wireless_router"
  },
  "mxgraph.cisco.switches.atm_fast_gigabit_etherswitch": {
    "libraryId": "cisco",
    "iconKey": "atm_fast_gigabit_etherswitch"
  },
  "mxgraph.cisco.switches.class_4_5_switch": {
    "libraryId": "cisco",
    "iconKey": "class_4_5_switch"
  },
  "mxgraph.cisco.switches.content_service_switch_1100": {
    "libraryId": "cisco",
    "iconKey": "content_service_switch_1100"
  },
  "mxgraph.cisco.switches.content_switch": {
    "libraryId": "cisco",
    "iconKey": "content_switch"
  },
  "mxgraph.cisco.switches.fibre_channel_fabric_switch": {
    "libraryId": "cisco",
    "iconKey": "fibre_channel_fabric_switch"
  },
  "mxgraph.cisco.switches.generic_softswitch": {
    "libraryId": "cisco",
    "iconKey": "generic_softswitch"
  },
  "mxgraph.cisco.switches.intelliswitch_stack": {
    "libraryId": "cisco",
    "iconKey": "intelliswitch_stack"
  },
  "mxgraph.cisco.switches.isdn_switch": {
    "libraryId": "cisco",
    "iconKey": "isdn_switch"
  },
  "mxgraph.cisco.switches.layer_2_remote_switch": {
    "libraryId": "cisco",
    "iconKey": "layer_2_remote_switch"
  },
  "mxgraph.cisco.switches.mgx_8000_multiservice_switch": {
    "libraryId": "cisco",
    "iconKey": "mgx_8000_multiservice_switch"
  },
  "mxgraph.cisco.switches.multi_fabric_server_switch": {
    "libraryId": "cisco",
    "iconKey": "multi_fabric_server_switch"
  },
  "mxgraph.cisco.switches.multiswitch_device": {
    "libraryId": "cisco",
    "iconKey": "multiswitch_device"
  },
  "mxgraph.cisco.switches.pbx_switch": {
    "libraryId": "cisco",
    "iconKey": "pbx_switch"
  },
  "mxgraph.cisco.switches.programmable_switch": {
    "libraryId": "cisco",
    "iconKey": "programmable_switch"
  },
  "mxgraph.cisco.switches.server_switch": {
    "libraryId": "cisco",
    "iconKey": "server_switch"
  },
  "mxgraph.cisco.switches.simultilayer_switch": {
    "libraryId": "cisco",
    "iconKey": "simultilayer_switch"
  },
  "mxgraph.cisco.switches.softswitch_pgw_mgc": {
    "libraryId": "cisco",
    "iconKey": "softswitch_pgw_mgc"
  },
  "mxgraph.cisco.switches.virtual_layer_switch": {
    "libraryId": "cisco",
    "iconKey": "virtual_layer_switch"
  },
  "mxgraph.cisco.switches.voice_atm_switch": {
    "libraryId": "cisco",
    "iconKey": "voice_atm_switch"
  },
  "mxgraph.cisco.switches.voice_switch": {
    "libraryId": "cisco",
    "iconKey": "voice_switch"
  },
  "mxgraph.cisco.switches.workgroup_switch": {
    "libraryId": "cisco",
    "iconKey": "workgroup_switch"
  },
  "mxgraph.cisco.security.centri_firewall": {
    "libraryId": "cisco",
    "iconKey": "centri_firewall"
  },
  "mxgraph.cisco.security.cisco_security": {
    "libraryId": "cisco",
    "iconKey": "cisco_security"
  },
  "mxgraph.cisco.security.gatekeeper": {
    "libraryId": "cisco",
    "iconKey": "gatekeeper"
  },
  "mxgraph.cisco.security.guard": {
    "libraryId": "cisco",
    "iconKey": "guard"
  },
  "mxgraph.cisco.security.ios_firewall": {
    "libraryId": "cisco",
    "iconKey": "ios_firewall"
  },
  "mxgraph.cisco.security.network_security_2": {
    "libraryId": "cisco",
    "iconKey": "network_security_2"
  },
  "mxgraph.cisco.security.router_firewall": {
    "libraryId": "cisco",
    "iconKey": "router_firewall"
  },
  "mxgraph.cisco.servers.cisco_unified_presence_server": {
    "libraryId": "cisco",
    "iconKey": "cisco_unified_presence_server"
  },
  "mxgraph.cisco.servers.communications_server": {
    "libraryId": "cisco",
    "iconKey": "communications_server"
  },
  "mxgraph.cisco.servers.directory_server": {
    "libraryId": "cisco",
    "iconKey": "directory_server"
  },
  "mxgraph.cisco.servers.microwebserver": {
    "libraryId": "cisco",
    "iconKey": "microwebserver"
  },
  "mxgraph.cisco.servers.moh_server": {
    "libraryId": "cisco",
    "iconKey": "moh_server"
  },
  "mxgraph.cisco.servers.sip_proxy_server": {
    "libraryId": "cisco",
    "iconKey": "sip_proxy_server"
  },
  "mxgraph.cisco.servers.software_based_server": {
    "libraryId": "cisco",
    "iconKey": "software_based_server"
  },
  "mxgraph.cisco.servers.standard_host": {
    "libraryId": "cisco",
    "iconKey": "standard_host"
  },
  "mxgraph.cisco.servers.storage_server": {
    "libraryId": "cisco",
    "iconKey": "storage_server"
  },
  "mxgraph.cisco.servers.unity_server": {
    "libraryId": "cisco",
    "iconKey": "unity_server"
  },
  "mxgraph.cisco.servers.voice_commserver": {
    "libraryId": "cisco",
    "iconKey": "voice_commserver"
  },
  "mxgraph.cisco.servers.www_server": {
    "libraryId": "cisco",
    "iconKey": "www_server"
  },
  "mxgraph.cisco.storage.cisco_file_engine": {
    "libraryId": "cisco",
    "iconKey": "cisco_file_engine"
  },
  "mxgraph.cisco.storage.diskette": {
    "libraryId": "cisco",
    "iconKey": "diskette"
  },
  "mxgraph.cisco.storage.fc_storage": {
    "libraryId": "cisco",
    "iconKey": "fc_storage"
  },
  "mxgraph.cisco.storage.fibre_channel_disk_subsystem": {
    "libraryId": "cisco",
    "iconKey": "fibre_channel_disk_subsystem"
  },
  "mxgraph.cisco.storage.file_cabinet": {
    "libraryId": "cisco",
    "iconKey": "file_cabinet"
  },
  "mxgraph.cisco.storage.relational_database": {
    "libraryId": "cisco",
    "iconKey": "relational_database"
  },
  "mxgraph.cisco.storage.web_cluster": {
    "libraryId": "cisco",
    "iconKey": "web_cluster"
  },
  "mxgraph.cisco.wireless.ground_terminal": {
    "libraryId": "cisco",
    "iconKey": "ground_terminal"
  },
  "mxgraph.cisco.wireless.satellite": {
    "libraryId": "cisco",
    "iconKey": "satellite"
  },
  "mxgraph.cisco.wireless.wi_fi_tag": {
    "libraryId": "cisco",
    "iconKey": "wi_fi_tag"
  },
  "mxgraph.cisco.wireless.wireless_location_appliance": {
    "libraryId": "cisco",
    "iconKey": "wireless_location_appliance"
  },
  "mxgraph.cisco.wireless.wireless_transport": {
    "libraryId": "cisco",
    "iconKey": "wireless_transport"
  },
  "mxgraph.cisco.wireless.wlan_controller": {
    "libraryId": "cisco",
    "iconKey": "wlan_controller"
  },
  "mxgraph.cisco.computers_and_peripherals.ibm_mini_as400": {
    "libraryId": "cisco",
    "iconKey": "ibm_mini_as400"
  },
  "mxgraph.cisco.computers_and_peripherals.ibm_tower": {
    "libraryId": "cisco",
    "iconKey": "ibm_tower"
  },
  "mxgraph.cisco.computers_and_peripherals.microphone": {
    "libraryId": "cisco",
    "iconKey": "microphone"
  },
  "mxgraph.cisco.computers_and_peripherals.pc_adapter_card": {
    "libraryId": "cisco",
    "iconKey": "pc_adapter_card"
  },
  "mxgraph.cisco.computers_and_peripherals.pc_routercard": {
    "libraryId": "cisco",
    "iconKey": "pc_routercard"
  },
  "mxgraph.cisco.computers_and_peripherals.scanner": {
    "libraryId": "cisco",
    "iconKey": "scanner"
  },
  "mxgraph.cisco.computers_and_peripherals.speaker": {
    "libraryId": "cisco",
    "iconKey": "speaker"
  },
  "mxgraph.cisco.computers_and_peripherals.sun_workstation": {
    "libraryId": "cisco",
    "iconKey": "sun_workstation"
  },
  "mxgraph.cisco.computers_and_peripherals.supercomputer": {
    "libraryId": "cisco",
    "iconKey": "supercomputer"
  },
  "mxgraph.cisco.computers_and_peripherals.tablet": {
    "libraryId": "cisco",
    "iconKey": "tablet"
  },
  "mxgraph.cisco.computers_and_peripherals.terminal": {
    "libraryId": "cisco",
    "iconKey": "terminal"
  },
  "mxgraph.cisco.computers_and_peripherals.upc": {
    "libraryId": "cisco",
    "iconKey": "upc"
  },
  "mxgraph.cisco.computers_and_peripherals.video_camera": {
    "libraryId": "cisco",
    "iconKey": "video_camera"
  },
  "mxgraph.cisco.computers_and_peripherals.web_browser": {
    "libraryId": "cisco",
    "iconKey": "web_browser"
  },
  "mxgraph.cisco.computers_and_peripherals.workstation": {
    "libraryId": "cisco",
    "iconKey": "workstation"
  },
  "mxgraph.cisco.hubs_and_gateways.100baset_hub": {
    "libraryId": "cisco",
    "iconKey": "100baset_hub"
  },
  "mxgraph.cisco.hubs_and_gateways.cisco_hub": {
    "libraryId": "cisco",
    "iconKey": "cisco_hub"
  },
  "mxgraph.cisco.hubs_and_gateways.generic_gateway": {
    "libraryId": "cisco",
    "iconKey": "generic_gateway"
  },
  "mxgraph.cisco.hubs_and_gateways.hub": {
    "libraryId": "cisco",
    "iconKey": "hub"
  },
  "mxgraph.cisco.hubs_and_gateways.mas_gateway": {
    "libraryId": "cisco",
    "iconKey": "mas_gateway"
  },
  "mxgraph.cisco.hubs_and_gateways.small_hub": {
    "libraryId": "cisco",
    "iconKey": "small_hub"
  },
  "mxgraph.cisco.hubs_and_gateways.universal_gateway": {
    "libraryId": "cisco",
    "iconKey": "universal_gateway"
  },
  "mxgraph.cisco.hubs_and_gateways.vpn_gateway": {
    "libraryId": "cisco",
    "iconKey": "vpn_gateway"
  },
  "mxgraph.cisco.modems_and_phones.cable_modem": {
    "libraryId": "cisco",
    "iconKey": "cable_modem"
  },
  "mxgraph.cisco.modems_and_phones.cell_phone": {
    "libraryId": "cisco",
    "iconKey": "cell_phone"
  },
  "mxgraph.cisco.modems_and_phones.fax": {
    "libraryId": "cisco",
    "iconKey": "fax"
  },
  "mxgraph.cisco.modems_and_phones.hootphone": {
    "libraryId": "cisco",
    "iconKey": "hootphone"
  },
  "mxgraph.cisco.modems_and_phones.ip_phone": {
    "libraryId": "cisco",
    "iconKey": "ip_phone"
  },
  "mxgraph.cisco.modems_and_phones.mobile_access_ip_phone": {
    "libraryId": "cisco",
    "iconKey": "mobile_access_ip_phone"
  },
  "mxgraph.cisco.modems_and_phones.mobile_access_ip_phone_2": {
    "libraryId": "cisco",
    "iconKey": "mobile_access_ip_phone_2"
  },
  "mxgraph.cisco.modems_and_phones.modem": {
    "libraryId": "cisco",
    "iconKey": "modem"
  },
  "mxgraph.cisco.modems_and_phones.phone_fax": {
    "libraryId": "cisco",
    "iconKey": "phone_fax"
  },
  "mxgraph.cisco.modems_and_phones.phone": {
    "libraryId": "cisco",
    "iconKey": "phone"
  },
  "mxgraph.cisco.modems_and_phones.rf_modem": {
    "libraryId": "cisco",
    "iconKey": "rf_modem"
  },
  "mxgraph.cisco.modems_and_phones.softphone": {
    "libraryId": "cisco",
    "iconKey": "softphone"
  },
  "mxgraph.cisco.misc.15200": {
    "libraryId": "cisco",
    "iconKey": "15200"
  },
  "mxgraph.cisco.misc.6700_series": {
    "libraryId": "cisco",
    "iconKey": "6700_series"
  },
  "mxgraph.cisco.misc.7500ars_7513": {
    "libraryId": "cisco",
    "iconKey": "7500ars_7513"
  },
  "mxgraph.cisco.misc.access_point": {
    "libraryId": "cisco",
    "iconKey": "access_point"
  },
  "mxgraph.cisco.misc.ace": {
    "libraryId": "cisco",
    "iconKey": "ace"
  },
  "mxgraph.cisco.misc.acs": {
    "libraryId": "cisco",
    "iconKey": "acs"
  },
  "mxgraph.cisco.misc.adm": {
    "libraryId": "cisco",
    "iconKey": "adm"
  },
  "mxgraph.cisco.misc.asa_5500": {
    "libraryId": "cisco",
    "iconKey": "asa_5500"
  },
  "mxgraph.cisco.misc.asic_processor": {
    "libraryId": "cisco",
    "iconKey": "asic_processor"
  },
  "mxgraph.cisco.misc.asr_1000_series": {
    "libraryId": "cisco",
    "iconKey": "asr_1000_series"
  },
  "mxgraph.cisco.misc.ata": {
    "libraryId": "cisco",
    "iconKey": "ata"
  },
  "mxgraph.cisco.misc.atm_3800": {
    "libraryId": "cisco",
    "iconKey": "atm_3800"
  },
  "mxgraph.cisco.misc.avs": {
    "libraryId": "cisco",
    "iconKey": "avs"
  },
  "mxgraph.cisco.misc.axp": {
    "libraryId": "cisco",
    "iconKey": "axp"
  },
  "mxgraph.cisco.misc.bbsm": {
    "libraryId": "cisco",
    "iconKey": "bbsm"
  },
  "mxgraph.cisco.misc.breakout_box": {
    "libraryId": "cisco",
    "iconKey": "breakout_box"
  },
  "mxgraph.cisco.misc.bridge": {
    "libraryId": "cisco",
    "iconKey": "bridge"
  },
  "mxgraph.cisco.misc.bts_10200": {
    "libraryId": "cisco",
    "iconKey": "bts_10200"
  },
  "mxgraph.cisco.misc.call_manager": {
    "libraryId": "cisco",
    "iconKey": "call_manager"
  },
  "mxgraph.cisco.misc.car": {
    "libraryId": "cisco",
    "iconKey": "car"
  },
  "mxgraph.cisco.misc.carrier_routing_system": {
    "libraryId": "cisco",
    "iconKey": "carrier_routing_system"
  },
  "mxgraph.cisco.misc.cddi_fddi": {
    "libraryId": "cisco",
    "iconKey": "cddi_fddi"
  },
  "mxgraph.cisco.misc.cdm": {
    "libraryId": "cisco",
    "iconKey": "cdm"
  },
  "mxgraph.cisco.misc.cisco_1000": {
    "libraryId": "cisco",
    "iconKey": "cisco_1000"
  },
  "mxgraph.cisco.misc.cisco_ca": {
    "libraryId": "cisco",
    "iconKey": "cisco_ca"
  },
  "mxgraph.cisco.misc.cisco_unity_express": {
    "libraryId": "cisco",
    "iconKey": "cisco_unity_express"
  },
  "mxgraph.cisco.misc.cisco_works": {
    "libraryId": "cisco",
    "iconKey": "cisco_works"
  },
  "mxgraph.cisco.misc.contact_acquirer": {
    "libraryId": "cisco",
    "iconKey": "contact_acquirer"
  },
  "mxgraph.cisco.misc.contact_center": {
    "libraryId": "cisco",
    "iconKey": "contact_center"
  },
  "mxgraph.cisco.misc.content_transformation_engine_cte": {
    "libraryId": "cisco",
    "iconKey": "content_transformation_engine_cte"
  },
  "mxgraph.cisco.misc.cs_mars": {
    "libraryId": "cisco",
    "iconKey": "cs_mars"
  },
  "mxgraph.cisco.misc.csm_s": {
    "libraryId": "cisco",
    "iconKey": "csm_s"
  },
  "mxgraph.cisco.misc.csu_dsu": {
    "libraryId": "cisco",
    "iconKey": "csu_dsu"
  },
  "mxgraph.cisco.misc.cube": {
    "libraryId": "cisco",
    "iconKey": "cube"
  },
  "mxgraph.cisco.misc.detector": {
    "libraryId": "cisco",
    "iconKey": "detector"
  },
  "mxgraph.cisco.misc.dot_dot": {
    "libraryId": "cisco",
    "iconKey": "dot_dot"
  },
  "mxgraph.cisco.misc.dpt": {
    "libraryId": "cisco",
    "iconKey": "dpt"
  },
  "mxgraph.cisco.misc.dslam": {
    "libraryId": "cisco",
    "iconKey": "dslam"
  },
  "mxgraph.cisco.misc.dual_mode": {
    "libraryId": "cisco",
    "iconKey": "dual_mode"
  },
  "mxgraph.cisco.misc.dwdm_filter": {
    "libraryId": "cisco",
    "iconKey": "dwdm_filter"
  },
  "mxgraph.cisco.misc.fddi_ring": {
    "libraryId": "cisco",
    "iconKey": "fddi_ring"
  },
  "mxgraph.cisco.misc.front_end_processor": {
    "libraryId": "cisco",
    "iconKey": "front_end_processor"
  },
  "mxgraph.cisco.misc.general_appliance": {
    "libraryId": "cisco",
    "iconKey": "general_appliance"
  },
  "mxgraph.cisco.misc.generic_processor": {
    "libraryId": "cisco",
    "iconKey": "generic_processor"
  },
  "mxgraph.cisco.misc.handheld": {
    "libraryId": "cisco",
    "iconKey": "handheld"
  },
  "mxgraph.cisco.misc.hp_mini": {
    "libraryId": "cisco",
    "iconKey": "hp_mini"
  },
  "mxgraph.cisco.misc.h_323": {
    "libraryId": "cisco",
    "iconKey": "h_323"
  },
  "mxgraph.cisco.misc.icm": {
    "libraryId": "cisco",
    "iconKey": "icm"
  },
  "mxgraph.cisco.misc.ics": {
    "libraryId": "cisco",
    "iconKey": "ics"
  },
  "mxgraph.cisco.misc.internet_streamer": {
    "libraryId": "cisco",
    "iconKey": "internet_streamer"
  },
  "mxgraph.cisco.misc.ios_slb": {
    "libraryId": "cisco",
    "iconKey": "ios_slb"
  },
  "mxgraph.cisco.misc.ip": {
    "libraryId": "cisco",
    "iconKey": "ip"
  },
  "mxgraph.cisco.misc.iptc": {
    "libraryId": "cisco",
    "iconKey": "iptc"
  },
  "mxgraph.cisco.misc.iptv_content_manager": {
    "libraryId": "cisco",
    "iconKey": "iptv_content_manager"
  },
  "mxgraph.cisco.misc.ip_communicator": {
    "libraryId": "cisco",
    "iconKey": "ip_communicator"
  },
  "mxgraph.cisco.misc.ip_dsl": {
    "libraryId": "cisco",
    "iconKey": "ip_dsl"
  },
  "mxgraph.cisco.misc.itp": {
    "libraryId": "cisco",
    "iconKey": "itp"
  },
  "mxgraph.cisco.misc.jbod": {
    "libraryId": "cisco",
    "iconKey": "jbod"
  },
  "mxgraph.cisco.misc.key": {
    "libraryId": "cisco",
    "iconKey": "key"
  },
  "mxgraph.cisco.misc.keys": {
    "libraryId": "cisco",
    "iconKey": "keys"
  },
  "mxgraph.cisco.misc.lan_to_lan": {
    "libraryId": "cisco",
    "iconKey": "lan_to_lan"
  },
  "mxgraph.cisco.misc.lightweight_ap": {
    "libraryId": "cisco",
    "iconKey": "lightweight_ap"
  },
  "mxgraph.cisco.misc.longreach_cpe": {
    "libraryId": "cisco",
    "iconKey": "longreach_cpe"
  },
  "mxgraph.cisco.misc.mau": {
    "libraryId": "cisco",
    "iconKey": "mau"
  },
  "mxgraph.cisco.misc.mcu": {
    "libraryId": "cisco",
    "iconKey": "mcu"
  },
  "mxgraph.cisco.misc.me1100": {
    "libraryId": "cisco",
    "iconKey": "me1100"
  },
  "mxgraph.cisco.misc.mediator": {
    "libraryId": "cisco",
    "iconKey": "mediator"
  },
  "mxgraph.cisco.misc.meetingplace": {
    "libraryId": "cisco",
    "iconKey": "meetingplace"
  },
  "mxgraph.cisco.misc.mesh_ap": {
    "libraryId": "cisco",
    "iconKey": "mesh_ap"
  },
  "mxgraph.cisco.misc.metro_1500": {
    "libraryId": "cisco",
    "iconKey": "metro_1500"
  },
  "mxgraph.cisco.misc.mini_vax": {
    "libraryId": "cisco",
    "iconKey": "mini_vax"
  },
  "mxgraph.cisco.misc.mobile_streamer": {
    "libraryId": "cisco",
    "iconKey": "mobile_streamer"
  },
  "mxgraph.cisco.misc.mse": {
    "libraryId": "cisco",
    "iconKey": "mse"
  },
  "mxgraph.cisco.misc.mux": {
    "libraryId": "cisco",
    "iconKey": "mux"
  },
  "mxgraph.cisco.misc.mxe": {
    "libraryId": "cisco",
    "iconKey": "mxe"
  },
  "mxgraph.cisco.misc.nac_appliance": {
    "libraryId": "cisco",
    "iconKey": "nac_appliance"
  },
  "mxgraph.cisco.misc.nce": {
    "libraryId": "cisco",
    "iconKey": "nce"
  },
  "mxgraph.cisco.misc.netranger": {
    "libraryId": "cisco",
    "iconKey": "netranger"
  },
  "mxgraph.cisco.misc.netsonar": {
    "libraryId": "cisco",
    "iconKey": "netsonar"
  },
  "mxgraph.cisco.misc.network_management": {
    "libraryId": "cisco",
    "iconKey": "network_management"
  },
  "mxgraph.cisco.misc.nexus_1000": {
    "libraryId": "cisco",
    "iconKey": "nexus_1000"
  },
  "mxgraph.cisco.misc.nexus_2000_fabric_extender": {
    "libraryId": "cisco",
    "iconKey": "nexus_2000_fabric_extender"
  },
  "mxgraph.cisco.misc.nexus_5000": {
    "libraryId": "cisco",
    "iconKey": "nexus_5000"
  },
  "mxgraph.cisco.misc.nexus_7000": {
    "libraryId": "cisco",
    "iconKey": "nexus_7000"
  },
  "mxgraph.cisco.misc.octel": {
    "libraryId": "cisco",
    "iconKey": "octel"
  },
  "mxgraph.cisco.misc.ons15500": {
    "libraryId": "cisco",
    "iconKey": "ons15500"
  },
  "mxgraph.cisco.misc.optical_amplifier": {
    "libraryId": "cisco",
    "iconKey": "optical_amplifier"
  },
  "mxgraph.cisco.misc.optical_transport": {
    "libraryId": "cisco",
    "iconKey": "optical_transport"
  },
  "mxgraph.cisco.misc.pad_1": {
    "libraryId": "cisco",
    "iconKey": "pad_1"
  },
  "mxgraph.cisco.misc.pad_2": {
    "libraryId": "cisco",
    "iconKey": "pad_2"
  },
  "mxgraph.cisco.misc.page_icon": {
    "libraryId": "cisco",
    "iconKey": "page_icon"
  },
  "mxgraph.cisco.misc.pbx": {
    "libraryId": "cisco",
    "iconKey": "pbx"
  },
  "mxgraph.cisco.misc.pc_software": {
    "libraryId": "cisco",
    "iconKey": "pc_software"
  },
  "mxgraph.cisco.misc.pc_video": {
    "libraryId": "cisco",
    "iconKey": "pc_video"
  },
  "mxgraph.cisco.misc.pda": {
    "libraryId": "cisco",
    "iconKey": "pda"
  },
  "mxgraph.cisco.misc.pmc": {
    "libraryId": "cisco",
    "iconKey": "pmc"
  },
  "mxgraph.cisco.misc.protocol_translator": {
    "libraryId": "cisco",
    "iconKey": "protocol_translator"
  },
  "mxgraph.cisco.misc.pxf": {
    "libraryId": "cisco",
    "iconKey": "pxf"
  },
  "mxgraph.cisco.misc.ratemux": {
    "libraryId": "cisco",
    "iconKey": "ratemux"
  },
  "mxgraph.cisco.misc.repeater": {
    "libraryId": "cisco",
    "iconKey": "repeater"
  },
  "mxgraph.cisco.misc.route_switch_processor": {
    "libraryId": "cisco",
    "iconKey": "route_switch_processor"
  },
  "mxgraph.cisco.misc.rpsrps": {
    "libraryId": "cisco",
    "iconKey": "rpsrps"
  },
  "mxgraph.cisco.misc.services": {
    "libraryId": "cisco",
    "iconKey": "services"
  },
  "mxgraph.cisco.misc.service_control": {
    "libraryId": "cisco",
    "iconKey": "service_control"
  },
  "mxgraph.cisco.misc.set_top_box": {
    "libraryId": "cisco",
    "iconKey": "set_top_box"
  },
  "mxgraph.cisco.misc.ssc": {
    "libraryId": "cisco",
    "iconKey": "ssc"
  },
  "mxgraph.cisco.misc.ssl_terminator": {
    "libraryId": "cisco",
    "iconKey": "ssl_terminator"
  },
  "mxgraph.cisco.misc.stb": {
    "libraryId": "cisco",
    "iconKey": "stb"
  },
  "mxgraph.cisco.misc.stp": {
    "libraryId": "cisco",
    "iconKey": "stp"
  },
  "mxgraph.cisco.misc.streamer": {
    "libraryId": "cisco",
    "iconKey": "streamer"
  },
  "mxgraph.cisco.misc.svx": {
    "libraryId": "cisco",
    "iconKey": "svx"
  },
  "mxgraph.cisco.misc.telecommuter_icon": {
    "libraryId": "cisco",
    "iconKey": "telecommuter_icon"
  },
  "mxgraph.cisco.misc.telepresence": {
    "libraryId": "cisco",
    "iconKey": "telepresence"
  },
  "mxgraph.cisco.misc.token": {
    "libraryId": "cisco",
    "iconKey": "token"
  },
  "mxgraph.cisco.misc.token_2": {
    "libraryId": "cisco",
    "iconKey": "token_2"
  },
  "mxgraph.cisco.misc.tp_mcu": {
    "libraryId": "cisco",
    "iconKey": "tp_mcu"
  },
  "mxgraph.cisco.misc.transpath": {
    "libraryId": "cisco",
    "iconKey": "transpath"
  },
  "mxgraph.cisco.misc.truck": {
    "libraryId": "cisco",
    "iconKey": "truck"
  },
  "mxgraph.cisco.misc.turret": {
    "libraryId": "cisco",
    "iconKey": "turret"
  },
  "mxgraph.cisco.misc.tv": {
    "libraryId": "cisco",
    "iconKey": "tv"
  },
  "mxgraph.cisco.misc.ubr910": {
    "libraryId": "cisco",
    "iconKey": "ubr910"
  },
  "mxgraph.cisco.misc.umg_series": {
    "libraryId": "cisco",
    "iconKey": "umg_series"
  },
  "mxgraph.cisco.misc.ups": {
    "libraryId": "cisco",
    "iconKey": "ups"
  },
  "mxgraph.cisco.misc.vault": {
    "libraryId": "cisco",
    "iconKey": "vault"
  },
  "mxgraph.cisco.misc.vip": {
    "libraryId": "cisco",
    "iconKey": "vip"
  },
  "mxgraph.cisco.misc.vpn_concentrator": {
    "libraryId": "cisco",
    "iconKey": "vpn_concentrator"
  },
  "mxgraph.cisco.misc.vss": {
    "libraryId": "cisco",
    "iconKey": "vss"
  },
  "mxgraph.cisco.misc.wae": {
    "libraryId": "cisco",
    "iconKey": "wae"
  },
  "mxgraph.cisco.misc.wism": {
    "libraryId": "cisco",
    "iconKey": "wism"
  },
  "mxgraph.cisco19.router": {
    "libraryId": "cisco19",
    "iconKey": "router",
    "suggestedType": "router"
  },
  "mxgraph.cisco19.l3_switch": {
    "libraryId": "cisco19",
    "iconKey": "l3_switch",
    "suggestedType": "switch"
  },
  "mxgraph.cisco19.l2_switch": {
    "libraryId": "cisco19",
    "iconKey": "l2_switch",
    "suggestedType": "switch"
  },
  "mxgraph.cisco19.workgroup_switch": {
    "libraryId": "cisco19",
    "iconKey": "workgroup_switch"
  },
  "mxgraph.cisco19.asa_5500": {
    "libraryId": "cisco19",
    "iconKey": "asa_5500",
    "suggestedType": "firewall"
  },
  "mxgraph.cisco19.firewall": {
    "libraryId": "cisco19",
    "iconKey": "firewall",
    "suggestedType": "firewall"
  },
  "mxgraph.cisco19.server": {
    "libraryId": "cisco19",
    "iconKey": "server",
    "suggestedType": "server"
  },
  "mxgraph.cisco19.blade_server": {
    "libraryId": "cisco19",
    "iconKey": "blade_server",
    "suggestedType": "server"
  },
  "mxgraph.cisco19.storage": {
    "libraryId": "cisco19",
    "iconKey": "storage",
    "suggestedType": "nas"
  },
  "mxgraph.cisco19.cloud": {
    "libraryId": "cisco19",
    "iconKey": "cloud"
  },
  "mxgraph.cisco19.cloud2": {
    "libraryId": "cisco19",
    "iconKey": "cloud_alt"
  },
  "mxgraph.cisco19.wireless_access_point": {
    "libraryId": "cisco19",
    "iconKey": "wireless_access_point",
    "suggestedType": "access_point"
  },
  "mxgraph.cisco19.camera": {
    "libraryId": "cisco19",
    "iconKey": "camera",
    "suggestedType": "camera"
  },
  "mxgraph.cisco19.cell_phone": {
    "libraryId": "cisco19",
    "iconKey": "cell_phone"
  },
  "mxgraph.cisco19.ip_phone": {
    "libraryId": "cisco19",
    "iconKey": "ip_phone",
    "suggestedType": "phone"
  },
  "mxgraph.cisco19.laptop": {
    "libraryId": "cisco19",
    "iconKey": "laptop",
    "suggestedType": "workstation"
  },
  "mxgraph.cisco19.printer": {
    "libraryId": "cisco19",
    "iconKey": "printer"
  },
  "mxgraph.cisco19.router_with_firewall": {
    "libraryId": "cisco19",
    "iconKey": "router_with_firewall"
  },
  "mxgraph.cisco19.asr_1000": {
    "libraryId": "cisco19",
    "iconKey": "asr_1000"
  },
  "mxgraph.cisco19.asr_9000": {
    "libraryId": "cisco19",
    "iconKey": "asr_9000"
  },
  "mxgraph.cisco19.branch": {
    "libraryId": "cisco19",
    "iconKey": "branch"
  },
  "mxgraph.cisco19.data_center": {
    "libraryId": "cisco19",
    "iconKey": "data_center"
  },
  "mxgraph.cisco19.3g_4g_indicator": {
    "libraryId": "cisco19",
    "iconKey": "3g_4g_indicator"
  },
  "mxgraph.cisco19.6500_vss": {
    "libraryId": "cisco19",
    "iconKey": "6500_vss"
  },
  "mxgraph.cisco19.6500_vss2": {
    "libraryId": "cisco19",
    "iconKey": "6500_vss2"
  },
  "mxgraph.cisco19.access_control_and_trustsec": {
    "libraryId": "cisco19",
    "iconKey": "access_control_and_trustsec"
  },
  "mxgraph.cisco19.aci": {
    "libraryId": "cisco19",
    "iconKey": "aci"
  },
  "mxgraph.cisco19.aci2": {
    "libraryId": "cisco19",
    "iconKey": "aci2"
  },
  "mxgraph.cisco19.acibg": {
    "libraryId": "cisco19",
    "iconKey": "acibg"
  },
  "mxgraph.cisco19.acs": {
    "libraryId": "cisco19",
    "iconKey": "acs"
  },
  "mxgraph.cisco19.ad_decoder": {
    "libraryId": "cisco19",
    "iconKey": "ad_decoder"
  },
  "mxgraph.cisco19.ad_encoder": {
    "libraryId": "cisco19",
    "iconKey": "ad_encoder"
  },
  "mxgraph.cisco19.analysis_correlation": {
    "libraryId": "cisco19",
    "iconKey": "analysis_correlation"
  },
  "mxgraph.cisco19.anomaly_detection": {
    "libraryId": "cisco19",
    "iconKey": "anomaly_detection"
  },
  "mxgraph.cisco19.anti_malware": {
    "libraryId": "cisco19",
    "iconKey": "anti_malware"
  },
  "mxgraph.cisco19.anti_malware2": {
    "libraryId": "cisco19",
    "iconKey": "anti_malware2"
  },
  "mxgraph.cisco19.appnav": {
    "libraryId": "cisco19",
    "iconKey": "appnav"
  },
  "mxgraph.cisco19.avc_application_visibility_control": {
    "libraryId": "cisco19",
    "iconKey": "avc_application_visibility_control"
  },
  "mxgraph.cisco19.avc_application_visibility_control2": {
    "libraryId": "cisco19",
    "iconKey": "avc_application_visibility_control2"
  },
  "mxgraph.cisco19.bg1": {
    "libraryId": "cisco19",
    "iconKey": "bg1"
  },
  "mxgraph.cisco19.bg10": {
    "libraryId": "cisco19",
    "iconKey": "bg10"
  },
  "mxgraph.cisco19.bg2": {
    "libraryId": "cisco19",
    "iconKey": "bg2"
  },
  "mxgraph.cisco19.bg3": {
    "libraryId": "cisco19",
    "iconKey": "bg3"
  },
  "mxgraph.cisco19.bg4": {
    "libraryId": "cisco19",
    "iconKey": "bg4"
  },
  "mxgraph.cisco19.bg5": {
    "libraryId": "cisco19",
    "iconKey": "bg5"
  },
  "mxgraph.cisco19.bg6": {
    "libraryId": "cisco19",
    "iconKey": "bg6"
  },
  "mxgraph.cisco19.bg7": {
    "libraryId": "cisco19",
    "iconKey": "bg7"
  },
  "mxgraph.cisco19.bg8": {
    "libraryId": "cisco19",
    "iconKey": "bg8"
  },
  "mxgraph.cisco19.bg9": {
    "libraryId": "cisco19",
    "iconKey": "bg9"
  },
  "mxgraph.cisco19.branch2": {
    "libraryId": "cisco19",
    "iconKey": "branch2"
  },
  "mxgraph.cisco19.camera2": {
    "libraryId": "cisco19",
    "iconKey": "camera2"
  },
  "mxgraph.cisco19.cell_phone2": {
    "libraryId": "cisco19",
    "iconKey": "cell_phone2"
  },
  "mxgraph.cisco19.cisco_15800": {
    "libraryId": "cisco19",
    "iconKey": "cisco_15800"
  },
  "mxgraph.cisco19.cisco_dna": {
    "libraryId": "cisco19",
    "iconKey": "cisco_dna"
  },
  "mxgraph.cisco19.cisco_dna_center": {
    "libraryId": "cisco19",
    "iconKey": "cisco_dna_center"
  },
  "mxgraph.cisco19.cisco_meetingplace_express": {
    "libraryId": "cisco19",
    "iconKey": "cisco_meetingplace_express"
  },
  "mxgraph.cisco19.cisco_security_manager": {
    "libraryId": "cisco19",
    "iconKey": "cisco_security_manager"
  },
  "mxgraph.cisco19.cisco_unified_contact_center_enterprise_and_hosted": {
    "libraryId": "cisco19",
    "iconKey": "cisco_unified_contact_center_enterprise_and_hosted"
  },
  "mxgraph.cisco19.cisco_unified_presence_service": {
    "libraryId": "cisco19",
    "iconKey": "cisco_unified_presence_service"
  },
  "mxgraph.cisco19.clock": {
    "libraryId": "cisco19",
    "iconKey": "clock"
  },
  "mxgraph.cisco19.cognitive": {
    "libraryId": "cisco19",
    "iconKey": "cognitive"
  },
  "mxgraph.cisco19.collab1": {
    "libraryId": "cisco19",
    "iconKey": "collab1"
  },
  "mxgraph.cisco19.collab2": {
    "libraryId": "cisco19",
    "iconKey": "collab2"
  },
  "mxgraph.cisco19.collab3": {
    "libraryId": "cisco19",
    "iconKey": "collab3"
  },
  "mxgraph.cisco19.collab4": {
    "libraryId": "cisco19",
    "iconKey": "collab4"
  },
  "mxgraph.cisco19.communications_manager": {
    "libraryId": "cisco19",
    "iconKey": "communications_manager"
  },
  "mxgraph.cisco19.contact_center_express": {
    "libraryId": "cisco19",
    "iconKey": "contact_center_express"
  },
  "mxgraph.cisco19.content_recording_streaming_server": {
    "libraryId": "cisco19",
    "iconKey": "content_recording_streaming_server"
  },
  "mxgraph.cisco19.content_router": {
    "libraryId": "cisco19",
    "iconKey": "content_router"
  },
  "mxgraph.cisco19.csr_1000v": {
    "libraryId": "cisco19",
    "iconKey": "csr_1000v"
  },
  "mxgraph.cisco19.database_relational": {
    "libraryId": "cisco19",
    "iconKey": "database_relational"
  },
  "mxgraph.cisco19.data_center2": {
    "libraryId": "cisco19",
    "iconKey": "data_center2"
  },
  "mxgraph.cisco19.da_decoder": {
    "libraryId": "cisco19",
    "iconKey": "da_decoder"
  },
  "mxgraph.cisco19.da_encoder": {
    "libraryId": "cisco19",
    "iconKey": "da_encoder"
  },
  "mxgraph.cisco19.dns_server": {
    "libraryId": "cisco19",
    "iconKey": "dns_server"
  },
  "mxgraph.cisco19.dns_server2": {
    "libraryId": "cisco19",
    "iconKey": "dns_server2"
  },
  "mxgraph.cisco19.dual_mode_access_point": {
    "libraryId": "cisco19",
    "iconKey": "dual_mode_access_point"
  },
  "mxgraph.cisco19.email_security": {
    "libraryId": "cisco19",
    "iconKey": "email_security"
  },
  "mxgraph.cisco19.fabric_interconnect": {
    "libraryId": "cisco19",
    "iconKey": "fabric_interconnect"
  },
  "mxgraph.cisco19.fibre_channel_director_mds_9000": {
    "libraryId": "cisco19",
    "iconKey": "fibre_channel_director_mds_9000"
  },
  "mxgraph.cisco19.fibre_channel_fabric_switch": {
    "libraryId": "cisco19",
    "iconKey": "fibre_channel_fabric_switch"
  },
  "mxgraph.cisco19.flow_analytics": {
    "libraryId": "cisco19",
    "iconKey": "flow_analytics"
  },
  "mxgraph.cisco19.flow_analytics2": {
    "libraryId": "cisco19",
    "iconKey": "flow_analytics2"
  },
  "mxgraph.cisco19.flow_collector": {
    "libraryId": "cisco19",
    "iconKey": "flow_collector"
  },
  "mxgraph.cisco19.h323": {
    "libraryId": "cisco19",
    "iconKey": "h323"
  },
  "mxgraph.cisco19.handheld": {
    "libraryId": "cisco19",
    "iconKey": "handheld"
  },
  "mxgraph.cisco19.handheld2": {
    "libraryId": "cisco19",
    "iconKey": "handheld2"
  },
  "mxgraph.cisco19.hdtv": {
    "libraryId": "cisco19",
    "iconKey": "hdtv"
  },
  "mxgraph.cisco19.hdtv2": {
    "libraryId": "cisco19",
    "iconKey": "hdtv2"
  },
  "mxgraph.cisco19.home_office": {
    "libraryId": "cisco19",
    "iconKey": "home_office"
  },
  "mxgraph.cisco19.home_office2": {
    "libraryId": "cisco19",
    "iconKey": "home_office2"
  },
  "mxgraph.cisco19.host_based_security": {
    "libraryId": "cisco19",
    "iconKey": "host_based_security"
  },
  "mxgraph.cisco19.hypervisor": {
    "libraryId": "cisco19",
    "iconKey": "hypervisor"
  },
  "mxgraph.cisco19.immersive_telepresence_endpoint": {
    "libraryId": "cisco19",
    "iconKey": "immersive_telepresence_endpoint"
  },
  "mxgraph.cisco19.ips_ids": {
    "libraryId": "cisco19",
    "iconKey": "ips_ids"
  },
  "mxgraph.cisco19.ip_ip_gateway": {
    "libraryId": "cisco19",
    "iconKey": "ip_ip_gateway"
  },
  "mxgraph.cisco19.ip_phone2": {
    "libraryId": "cisco19",
    "iconKey": "ip_phone2"
  },
  "mxgraph.cisco19.ip_telephone_router": {
    "libraryId": "cisco19",
    "iconKey": "ip_telephone_router"
  },
  "mxgraph.cisco19.ironport": {
    "libraryId": "cisco19",
    "iconKey": "ironport"
  },
  "mxgraph.cisco19.ise": {
    "libraryId": "cisco19",
    "iconKey": "ise"
  },
  "mxgraph.cisco19.joystick_keyboard": {
    "libraryId": "cisco19",
    "iconKey": "joystick_keyboard"
  },
  "mxgraph.cisco19.joystick_keyboard2": {
    "libraryId": "cisco19",
    "iconKey": "joystick_keyboard2"
  },
  "mxgraph.cisco19.key": {
    "libraryId": "cisco19",
    "iconKey": "key"
  },
  "mxgraph.cisco19.key2": {
    "libraryId": "cisco19",
    "iconKey": "key2"
  },
  "mxgraph.cisco19.l2_modular": {
    "libraryId": "cisco19",
    "iconKey": "l2_modular"
  },
  "mxgraph.cisco19.l2_modular2": {
    "libraryId": "cisco19",
    "iconKey": "l2_modular2"
  },
  "mxgraph.cisco19.l2_switch_with_dual_supervisor": {
    "libraryId": "cisco19",
    "iconKey": "l2_switch_with_dual_supervisor"
  },
  "mxgraph.cisco19.l3_modular": {
    "libraryId": "cisco19",
    "iconKey": "l3_modular"
  },
  "mxgraph.cisco19.l3_modular2": {
    "libraryId": "cisco19",
    "iconKey": "l3_modular2"
  },
  "mxgraph.cisco19.l3_modular3": {
    "libraryId": "cisco19",
    "iconKey": "l3_modular3"
  },
  "mxgraph.cisco19.l3_switch_with_dual_supervisor": {
    "libraryId": "cisco19",
    "iconKey": "l3_switch_with_dual_supervisor"
  },
  "mxgraph.cisco19.laptop2": {
    "libraryId": "cisco19",
    "iconKey": "laptop2"
  },
  "mxgraph.cisco19.laptop_video_client": {
    "libraryId": "cisco19",
    "iconKey": "laptop_video_client"
  },
  "mxgraph.cisco19.laptop_video_client2": {
    "libraryId": "cisco19",
    "iconKey": "laptop_video_client2"
  },
  "mxgraph.cisco19.layer3_nexus_5k_switch": {
    "libraryId": "cisco19",
    "iconKey": "layer3_nexus_5k_switch"
  },
  "mxgraph.cisco19.ldap": {
    "libraryId": "cisco19",
    "iconKey": "ldap"
  },
  "mxgraph.cisco19.ldap2": {
    "libraryId": "cisco19",
    "iconKey": "ldap2"
  },
  "mxgraph.cisco19.load_balancer": {
    "libraryId": "cisco19",
    "iconKey": "load_balancer"
  },
  "mxgraph.cisco19.lock": {
    "libraryId": "cisco19",
    "iconKey": "lock"
  },
  "mxgraph.cisco19.lock2": {
    "libraryId": "cisco19",
    "iconKey": "lock2"
  },
  "mxgraph.cisco19.media_server": {
    "libraryId": "cisco19",
    "iconKey": "media_server"
  },
  "mxgraph.cisco19.meeting_scheduling_and_management_server": {
    "libraryId": "cisco19",
    "iconKey": "meeting_scheduling_and_management_server"
  },
  "mxgraph.cisco19.mesh_access_point": {
    "libraryId": "cisco19",
    "iconKey": "mesh_access_point"
  },
  "mxgraph.cisco19.monitor": {
    "libraryId": "cisco19",
    "iconKey": "monitor"
  },
  "mxgraph.cisco19.monitoring": {
    "libraryId": "cisco19",
    "iconKey": "monitoring"
  },
  "mxgraph.cisco19.multipoint_meeting_server": {
    "libraryId": "cisco19",
    "iconKey": "multipoint_meeting_server"
  },
  "mxgraph.cisco19.nac_appliance": {
    "libraryId": "cisco19",
    "iconKey": "nac_appliance"
  },
  "mxgraph.cisco19.nam_virtual_service_blade": {
    "libraryId": "cisco19",
    "iconKey": "nam_virtual_service_blade"
  },
  "mxgraph.cisco19.netflow_router": {
    "libraryId": "cisco19",
    "iconKey": "netflow_router"
  },
  "mxgraph.cisco19.netflow_router2": {
    "libraryId": "cisco19",
    "iconKey": "netflow_router2"
  },
  "mxgraph.cisco19.netflow_router3": {
    "libraryId": "cisco19",
    "iconKey": "netflow_router3"
  },
  "mxgraph.cisco19.net_mgmt_appliance": {
    "libraryId": "cisco19",
    "iconKey": "net_mgmt_appliance"
  },
  "mxgraph.cisco19.next_generation_intrusion_prevention_system": {
    "libraryId": "cisco19",
    "iconKey": "next_generation_intrusion_prevention_system"
  },
  "mxgraph.cisco19.nexus_1010": {
    "libraryId": "cisco19",
    "iconKey": "nexus_1010"
  },
  "mxgraph.cisco19.nexus_1k": {
    "libraryId": "cisco19",
    "iconKey": "nexus_1k"
  },
  "mxgraph.cisco19.nexus_1kv_vsm": {
    "libraryId": "cisco19",
    "iconKey": "nexus_1kv_vsm"
  },
  "mxgraph.cisco19.nexus_2000_10ge": {
    "libraryId": "cisco19",
    "iconKey": "nexus_2000_10ge"
  },
  "mxgraph.cisco19.nexus_2k": {
    "libraryId": "cisco19",
    "iconKey": "nexus_2k"
  },
  "mxgraph.cisco19.nexus_3k": {
    "libraryId": "cisco19",
    "iconKey": "nexus_3k"
  },
  "mxgraph.cisco19.nexus_4k": {
    "libraryId": "cisco19",
    "iconKey": "nexus_4k"
  },
  "mxgraph.cisco19.nexus_5k": {
    "libraryId": "cisco19",
    "iconKey": "nexus_5k"
  },
  "mxgraph.cisco19.nexus_5k_with_integrated_vsm": {
    "libraryId": "cisco19",
    "iconKey": "nexus_5k_with_integrated_vsm"
  },
  "mxgraph.cisco19.nexus_7k": {
    "libraryId": "cisco19",
    "iconKey": "nexus_7k"
  },
  "mxgraph.cisco19.nexus_9300": {
    "libraryId": "cisco19",
    "iconKey": "nexus_9300"
  },
  "mxgraph.cisco19.nexus_9500": {
    "libraryId": "cisco19",
    "iconKey": "nexus_9500"
  },
  "mxgraph.cisco19.operations_manager": {
    "libraryId": "cisco19",
    "iconKey": "operations_manager"
  },
  "mxgraph.cisco19.phone_polycom": {
    "libraryId": "cisco19",
    "iconKey": "phone_polycom"
  },
  "mxgraph.cisco19.phone_polycom2": {
    "libraryId": "cisco19",
    "iconKey": "phone_polycom2"
  },
  "mxgraph.cisco19.policy_configuration": {
    "libraryId": "cisco19",
    "iconKey": "policy_configuration"
  },
  "mxgraph.cisco19.pos": {
    "libraryId": "cisco19",
    "iconKey": "pos"
  },
  "mxgraph.cisco19.pos2": {
    "libraryId": "cisco19",
    "iconKey": "pos2"
  },
  "mxgraph.cisco19.posture_assessment": {
    "libraryId": "cisco19",
    "iconKey": "posture_assessment"
  },
  "mxgraph.cisco19.primary_codec": {
    "libraryId": "cisco19",
    "iconKey": "primary_codec"
  },
  "mxgraph.cisco19.printer2": {
    "libraryId": "cisco19",
    "iconKey": "printer2"
  },
  "mxgraph.cisco19.router_with_firewall2": {
    "libraryId": "cisco19",
    "iconKey": "router_with_firewall2"
  },
  "mxgraph.cisco19.router_with_voice": {
    "libraryId": "cisco19",
    "iconKey": "router_with_voice"
  },
  "mxgraph.cisco19.rps": {
    "libraryId": "cisco19",
    "iconKey": "rps"
  },
  "mxgraph.cisco19.secondary_codec": {
    "libraryId": "cisco19",
    "iconKey": "secondary_codec"
  },
  "mxgraph.cisco19.secure_catalyst_switch_color": {
    "libraryId": "cisco19",
    "iconKey": "secure_catalyst_switch_color"
  },
  "mxgraph.cisco19.secure_catalyst_switch_color2": {
    "libraryId": "cisco19",
    "iconKey": "secure_catalyst_switch_color2"
  },
  "mxgraph.cisco19.secure_catalyst_switch_color3": {
    "libraryId": "cisco19",
    "iconKey": "secure_catalyst_switch_color3"
  },
  "mxgraph.cisco19.secure_catalyst_switch_subdued": {
    "libraryId": "cisco19",
    "iconKey": "secure_catalyst_switch_subdued"
  },
  "mxgraph.cisco19.secure_catalyst_switch_subdued2": {
    "libraryId": "cisco19",
    "iconKey": "secure_catalyst_switch_subdued2"
  },
  "mxgraph.cisco19.secure_endpoints": {
    "libraryId": "cisco19",
    "iconKey": "secure_endpoints"
  },
  "mxgraph.cisco19.secure_endpoints2": {
    "libraryId": "cisco19",
    "iconKey": "secure_endpoints2"
  },
  "mxgraph.cisco19.secure_endpoint_pc": {
    "libraryId": "cisco19",
    "iconKey": "secure_endpoint_pc"
  },
  "mxgraph.cisco19.secure_endpoint_pc2": {
    "libraryId": "cisco19",
    "iconKey": "secure_endpoint_pc2"
  },
  "mxgraph.cisco19.secure_router": {
    "libraryId": "cisco19",
    "iconKey": "secure_router"
  },
  "mxgraph.cisco19.secure_server": {
    "libraryId": "cisco19",
    "iconKey": "secure_server"
  },
  "mxgraph.cisco19.secure_server2": {
    "libraryId": "cisco19",
    "iconKey": "secure_server2"
  },
  "mxgraph.cisco19.secure_switch": {
    "libraryId": "cisco19",
    "iconKey": "secure_switch"
  },
  "mxgraph.cisco19.security_management": {
    "libraryId": "cisco19",
    "iconKey": "security_management"
  },
  "mxgraph.cisco19.server2": {
    "libraryId": "cisco19",
    "iconKey": "server2"
  },
  "mxgraph.cisco19.service_ready_engine": {
    "libraryId": "cisco19",
    "iconKey": "service_ready_engine"
  },
  "mxgraph.cisco19.set_top": {
    "libraryId": "cisco19",
    "iconKey": "set_top"
  },
  "mxgraph.cisco19.set_top2": {
    "libraryId": "cisco19",
    "iconKey": "set_top2"
  },
  "mxgraph.cisco19.shield": {
    "libraryId": "cisco19",
    "iconKey": "shield"
  },
  "mxgraph.cisco19.ssl_terminator": {
    "libraryId": "cisco19",
    "iconKey": "ssl_terminator"
  },
  "mxgraph.cisco19.stealthwatch_management_console_smc": {
    "libraryId": "cisco19",
    "iconKey": "stealthwatch_management_console_smc"
  },
  "mxgraph.cisco19.stealthwatch_management_console_smc2": {
    "libraryId": "cisco19",
    "iconKey": "stealthwatch_management_console_smc2"
  },
  "mxgraph.cisco19.surveillance_camera": {
    "libraryId": "cisco19",
    "iconKey": "surveillance_camera"
  },
  "mxgraph.cisco19.surveillance_camera2": {
    "libraryId": "cisco19",
    "iconKey": "surveillance_camera2"
  },
  "mxgraph.cisco19.tablet": {
    "libraryId": "cisco19",
    "iconKey": "tablet"
  },
  "mxgraph.cisco19.tablet2": {
    "libraryId": "cisco19",
    "iconKey": "tablet2"
  },
  "mxgraph.cisco19.telepresence_endpoint": {
    "libraryId": "cisco19",
    "iconKey": "telepresence_endpoint"
  },
  "mxgraph.cisco19.telepresence_endpoint_twin_data_display": {
    "libraryId": "cisco19",
    "iconKey": "telepresence_endpoint_twin_data_display"
  },
  "mxgraph.cisco19.telepresence_exchange": {
    "libraryId": "cisco19",
    "iconKey": "telepresence_exchange"
  },
  "mxgraph.cisco19.threat_intelligence": {
    "libraryId": "cisco19",
    "iconKey": "threat_intelligence"
  },
  "mxgraph.cisco19.transcoder": {
    "libraryId": "cisco19",
    "iconKey": "transcoder"
  },
  "mxgraph.cisco19.ucs_5108_blade_chassis": {
    "libraryId": "cisco19",
    "iconKey": "ucs_5108_blade_chassis"
  },
  "mxgraph.cisco19.ucs_c_series_server": {
    "libraryId": "cisco19",
    "iconKey": "ucs_c_series_server"
  },
  "mxgraph.cisco19.ucs_express": {
    "libraryId": "cisco19",
    "iconKey": "ucs_express"
  },
  "mxgraph.cisco19.unity": {
    "libraryId": "cisco19",
    "iconKey": "unity"
  },
  "mxgraph.cisco19.upc_unified_personal_communicator": {
    "libraryId": "cisco19",
    "iconKey": "upc_unified_personal_communicator"
  },
  "mxgraph.cisco19.upc_unified_personal_communicator2": {
    "libraryId": "cisco19",
    "iconKey": "upc_unified_personal_communicator2"
  },
  "mxgraph.cisco19.ups": {
    "libraryId": "cisco19",
    "iconKey": "ups"
  },
  "mxgraph.cisco19.user": {
    "libraryId": "cisco19",
    "iconKey": "user"
  },
  "mxgraph.cisco19.user2": {
    "libraryId": "cisco19",
    "iconKey": "user2"
  },
  "mxgraph.cisco19.vbond": {
    "libraryId": "cisco19",
    "iconKey": "vbond"
  },
  "mxgraph.cisco19.video_analytics": {
    "libraryId": "cisco19",
    "iconKey": "video_analytics"
  },
  "mxgraph.cisco19.video_call_server": {
    "libraryId": "cisco19",
    "iconKey": "video_call_server"
  },
  "mxgraph.cisco19.video_gateway": {
    "libraryId": "cisco19",
    "iconKey": "video_gateway"
  },
  "mxgraph.cisco19.virtual_desktop_service": {
    "libraryId": "cisco19",
    "iconKey": "virtual_desktop_service"
  },
  "mxgraph.cisco19.virtual_matrix_switch": {
    "libraryId": "cisco19",
    "iconKey": "virtual_matrix_switch"
  },
  "mxgraph.cisco19.virtual_private_network": {
    "libraryId": "cisco19",
    "iconKey": "virtual_private_network"
  },
  "mxgraph.cisco19.virtual_private_network2": {
    "libraryId": "cisco19",
    "iconKey": "virtual_private_network2"
  },
  "mxgraph.cisco19.virtual_private_network_connector": {
    "libraryId": "cisco19",
    "iconKey": "virtual_private_network_connector"
  },
  "mxgraph.cisco19.vmanage": {
    "libraryId": "cisco19",
    "iconKey": "vmanage"
  },
  "mxgraph.cisco19.vpn_concentrator": {
    "libraryId": "cisco19",
    "iconKey": "vpn_concentrator"
  },
  "mxgraph.cisco19.vsmart": {
    "libraryId": "cisco19",
    "iconKey": "vsmart"
  },
  "mxgraph.cisco19.vts": {
    "libraryId": "cisco19",
    "iconKey": "vts"
  },
  "mxgraph.cisco19.vts2": {
    "libraryId": "cisco19",
    "iconKey": "vts2"
  },
  "mxgraph.cisco19.webex": {
    "libraryId": "cisco19",
    "iconKey": "webex"
  },
  "mxgraph.cisco19.web_application_firewall": {
    "libraryId": "cisco19",
    "iconKey": "web_application_firewall"
  },
  "mxgraph.cisco19.web_reputation_filtering": {
    "libraryId": "cisco19",
    "iconKey": "web_reputation_filtering"
  },
  "mxgraph.cisco19.web_reputation_filtering_2": {
    "libraryId": "cisco19",
    "iconKey": "web_reputation_filtering_2"
  },
  "mxgraph.cisco19.web_security": {
    "libraryId": "cisco19",
    "iconKey": "web_security"
  },
  "mxgraph.cisco19.web_security_services": {
    "libraryId": "cisco19",
    "iconKey": "web_security_services"
  },
  "mxgraph.cisco19.web_security_services2": {
    "libraryId": "cisco19",
    "iconKey": "web_security_services2"
  },
  "mxgraph.cisco19.wifi_indicator": {
    "libraryId": "cisco19",
    "iconKey": "wifi_indicator"
  },
  "mxgraph.cisco19.wireless_access_point2": {
    "libraryId": "cisco19",
    "iconKey": "wireless_access_point2"
  },
  "mxgraph.cisco19.wireless_bridge": {
    "libraryId": "cisco19",
    "iconKey": "wireless_bridge"
  },
  "mxgraph.cisco19.wireless_bridge2": {
    "libraryId": "cisco19",
    "iconKey": "wireless_bridge2"
  },
  "mxgraph.cisco19.wireless_connector": {
    "libraryId": "cisco19",
    "iconKey": "wireless_connector"
  },
  "mxgraph.cisco19.wireless_intrusion_prevention": {
    "libraryId": "cisco19",
    "iconKey": "wireless_intrusion_prevention"
  },
  "mxgraph.cisco19.wireless_lan_controller": {
    "libraryId": "cisco19",
    "iconKey": "wireless_lan_controller"
  },
  "mxgraph.cisco19.wireless_location_appliance": {
    "libraryId": "cisco19",
    "iconKey": "wireless_location_appliance"
  },
  "mxgraph.cisco19.wireless_router": {
    "libraryId": "cisco19",
    "iconKey": "wireless_router"
  },
  "mxgraph.cisco19.workstation": {
    "libraryId": "cisco19",
    "iconKey": "workstation"
  },
  "mxgraph.cisco19.workstation2": {
    "libraryId": "cisco19",
    "iconKey": "workstation2"
  },
  "mxgraph.cisco19.x509_certificate": {
    "libraryId": "cisco19",
    "iconKey": "x509_certificate"
  },
  "mxgraph.cisco19.x509_certificate2": {
    "libraryId": "cisco19",
    "iconKey": "x509_certificate2"
  }
};

export function lookupDrawioShape(rawShapeKey: string | null | undefined): DrawioShapeMapping | undefined {
  if (!rawShapeKey) return undefined;
  return DRAWIO_SHAPE_MAP[rawShapeKey.toLowerCase()];
}
