// AUTO-GENERATED by scripts/build-icon-libraries.ts. Do not edit by hand.

export interface IconLibraryEntry {
  key: string;
  label: string;
  suggestedTypes?: string[];
}

export interface IconLibrary {
  id: string;
  label: string;
  icons: IconLibraryEntry[];
}

export const ICON_LIBRARIES: IconLibrary[] = [
  {
    "id": "network2018",
    "label": "Networking (legacy)",
    "icons": [
      {
        "key": "router",
        "label": "Router",
        "suggestedTypes": [
          "router"
        ]
      },
      {
        "key": "switch",
        "label": "Switch",
        "suggestedTypes": [
          "switch"
        ]
      },
      {
        "key": "firewall",
        "label": "Firewall",
        "suggestedTypes": [
          "firewall"
        ]
      },
      {
        "key": "hub",
        "label": "Hub"
      },
      {
        "key": "server",
        "label": "Server",
        "suggestedTypes": [
          "server"
        ]
      },
      {
        "key": "mainframe",
        "label": "Mainframe"
      },
      {
        "key": "nas",
        "label": "NAS",
        "suggestedTypes": [
          "nas"
        ]
      },
      {
        "key": "storage",
        "label": "Storage"
      },
      {
        "key": "tape_storage",
        "label": "Tape Storage"
      },
      {
        "key": "mail_server",
        "label": "Mail Server"
      },
      {
        "key": "proxy_server",
        "label": "Proxy Server"
      },
      {
        "key": "load_balancer",
        "label": "Load Balancer"
      },
      {
        "key": "pc",
        "label": "PC",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "desktop_pc",
        "label": "Desktop PC",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "laptop",
        "label": "Laptop",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "tablet",
        "label": "Tablet"
      },
      {
        "key": "mobile",
        "label": "Mobile"
      },
      {
        "key": "phone",
        "label": "Phone",
        "suggestedTypes": [
          "phone"
        ]
      },
      {
        "key": "printer",
        "label": "Printer"
      },
      {
        "key": "monitor",
        "label": "Monitor"
      },
      {
        "key": "cloud",
        "label": "Cloud"
      },
      {
        "key": "modem",
        "label": "Modem"
      },
      {
        "key": "rack",
        "label": "Rack"
      },
      {
        "key": "camera",
        "label": "Camera",
        "suggestedTypes": [
          "camera"
        ]
      },
      {
        "key": "radio_tower",
        "label": "Radio Tower"
      },
      {
        "key": "satellite_dish",
        "label": "Satellite Dish"
      },
      {
        "key": "ups",
        "label": "UPS"
      },
      {
        "key": "biometric_reader",
        "label": "Biometric Reader"
      },
      {
        "key": "business_center",
        "label": "Business Center"
      },
      {
        "key": "community",
        "label": "Community"
      },
      {
        "key": "comm_link",
        "label": "Comm Link"
      },
      {
        "key": "copier",
        "label": "Copier"
      },
      {
        "key": "dvr",
        "label": "DVR"
      },
      {
        "key": "external_storage",
        "label": "External Storage"
      },
      {
        "key": "gamepad",
        "label": "Gamepad"
      },
      {
        "key": "patch_panel",
        "label": "Patch Panel"
      },
      {
        "key": "phone_2",
        "label": "Phone 2"
      },
      {
        "key": "satellite",
        "label": "Satellite"
      },
      {
        "key": "scanner",
        "label": "Scanner"
      },
      {
        "key": "secured",
        "label": "Secured"
      },
      {
        "key": "server_storage",
        "label": "Server Storage"
      },
      {
        "key": "supercomputer",
        "label": "Supercomputer"
      },
      {
        "key": "terminal",
        "label": "Terminal"
      },
      {
        "key": "unsecure",
        "label": "Unsecure"
      },
      {
        "key": "ups_small",
        "label": "UPS Small"
      },
      {
        "key": "usb_stick",
        "label": "USB Stick"
      },
      {
        "key": "users",
        "label": "Users"
      },
      {
        "key": "user_female",
        "label": "User Female"
      },
      {
        "key": "user_male",
        "label": "User Male"
      },
      {
        "key": "video_projector",
        "label": "Video Projector"
      },
      {
        "key": "video_projector_screen",
        "label": "Video Projector Screen"
      },
      {
        "key": "virtual_pc",
        "label": "Virtual PC"
      },
      {
        "key": "virtual_server",
        "label": "Virtual Server"
      },
      {
        "key": "virus",
        "label": "Virus"
      },
      {
        "key": "web_server",
        "label": "Web Server"
      },
      {
        "key": "wireless_hub",
        "label": "Wireless Hub"
      },
      {
        "key": "wireless_modem",
        "label": "Wireless Modem"
      }
    ]
  },
  {
    "id": "network2025",
    "label": "Networking",
    "icons": [
      {
        "key": "router",
        "label": "Router",
        "suggestedTypes": [
          "router"
        ]
      },
      {
        "key": "firewall",
        "label": "Firewall",
        "suggestedTypes": [
          "firewall"
        ]
      },
      {
        "key": "hub",
        "label": "Hub"
      },
      {
        "key": "server",
        "label": "Server",
        "suggestedTypes": [
          "server"
        ]
      },
      {
        "key": "mainframe",
        "label": "Mainframe"
      },
      {
        "key": "global_server",
        "label": "Global Server"
      },
      {
        "key": "data_storage",
        "label": "Storage",
        "suggestedTypes": [
          "nas"
        ]
      },
      {
        "key": "mail_server",
        "label": "Mail Server"
      },
      {
        "key": "load_balancer",
        "label": "Load Balancer"
      },
      {
        "key": "desktop_pc",
        "label": "Desktop PC",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "laptop",
        "label": "Laptop",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "mobile_phone",
        "label": "Mobile Phone"
      },
      {
        "key": "modem",
        "label": "Modem"
      },
      {
        "key": "cloud",
        "label": "Cloud"
      },
      {
        "key": "internet",
        "label": "Internet"
      },
      {
        "key": "internet_security",
        "label": "Internet Security"
      },
      {
        "key": "lan",
        "label": "LAN"
      },
      {
        "key": "cctv",
        "label": "CCTV",
        "suggestedTypes": [
          "camera"
        ]
      },
      {
        "key": "antenna",
        "label": "Antenna"
      },
      {
        "key": "biometric_reader",
        "label": "Biometric Reader"
      },
      {
        "key": "big_data",
        "label": "Big Data"
      },
      {
        "key": "encryption",
        "label": "Encryption"
      },
      {
        "key": "lock",
        "label": "Lock"
      },
      {
        "key": "mobile_network",
        "label": "Mobile Network"
      },
      {
        "key": "antenna_shadow",
        "label": "antenna shadow"
      },
      {
        "key": "application",
        "label": "application"
      },
      {
        "key": "application_shadow",
        "label": "application shadow"
      },
      {
        "key": "big_data_shadow",
        "label": "big data shadow"
      },
      {
        "key": "biohazard",
        "label": "biohazard"
      },
      {
        "key": "biohazard_shadow",
        "label": "biohazard shadow"
      },
      {
        "key": "biometric_reader_shadow",
        "label": "biometric reader shadow"
      },
      {
        "key": "cctv_shadow",
        "label": "cctv shadow"
      },
      {
        "key": "cloud_shadow",
        "label": "cloud shadow"
      },
      {
        "key": "community",
        "label": "community"
      },
      {
        "key": "community_shadow",
        "label": "community shadow"
      },
      {
        "key": "copier",
        "label": "copier"
      },
      {
        "key": "copier_shadow",
        "label": "copier shadow"
      },
      {
        "key": "data_management",
        "label": "data management"
      },
      {
        "key": "data_management_shadow",
        "label": "data management shadow"
      },
      {
        "key": "data_storage_shadow",
        "label": "data storage shadow"
      },
      {
        "key": "desktop_pc_shadow",
        "label": "desktop pc shadow"
      },
      {
        "key": "encryption_shadow",
        "label": "encryption shadow"
      },
      {
        "key": "external_storage",
        "label": "external storage"
      },
      {
        "key": "external_storage_shadow",
        "label": "external storage shadow"
      },
      {
        "key": "firewall_shadow",
        "label": "firewall shadow"
      },
      {
        "key": "gamepad",
        "label": "gamepad"
      },
      {
        "key": "gamepad_shadow",
        "label": "gamepad shadow"
      },
      {
        "key": "global_server_shadow",
        "label": "global server shadow"
      },
      {
        "key": "globe",
        "label": "globe"
      },
      {
        "key": "globe_shadow",
        "label": "globe shadow"
      },
      {
        "key": "hub_shadow",
        "label": "hub shadow"
      },
      {
        "key": "internet_shadow",
        "label": "internet shadow"
      },
      {
        "key": "internet_security_shadow",
        "label": "internet security shadow"
      },
      {
        "key": "lan_shadow",
        "label": "lan shadow"
      },
      {
        "key": "laptop_shadow",
        "label": "laptop shadow"
      },
      {
        "key": "load_balancer_shadow",
        "label": "load balancer shadow"
      },
      {
        "key": "lock_shadow",
        "label": "lock shadow"
      },
      {
        "key": "mail_server_shadow",
        "label": "mail server shadow"
      },
      {
        "key": "mainframe_shadow",
        "label": "mainframe shadow"
      },
      {
        "key": "mobile_network_shadow",
        "label": "mobile network shadow"
      },
      {
        "key": "mobile_phone_shadow",
        "label": "mobile phone shadow"
      },
      {
        "key": "modem_shadow",
        "label": "modem shadow"
      },
      {
        "key": "monitor",
        "label": "monitor"
      },
      {
        "key": "monitor_shadow",
        "label": "monitor shadow"
      },
      {
        "key": "nas_filer",
        "label": "nas filer"
      },
      {
        "key": "nas_filer_shadow",
        "label": "nas filer shadow"
      },
      {
        "key": "network",
        "label": "network"
      },
      {
        "key": "network_shadow",
        "label": "network shadow"
      },
      {
        "key": "network_security",
        "label": "network security"
      },
      {
        "key": "network_security_shadow",
        "label": "network security shadow"
      },
      {
        "key": "patch_panel",
        "label": "patch panel"
      },
      {
        "key": "patch_panel_shadow",
        "label": "patch panel shadow"
      },
      {
        "key": "pc",
        "label": "pc"
      },
      {
        "key": "pc_shadow",
        "label": "pc shadow"
      },
      {
        "key": "phone",
        "label": "phone"
      },
      {
        "key": "phone_shadow",
        "label": "phone shadow"
      },
      {
        "key": "printer",
        "label": "printer"
      },
      {
        "key": "printer_shadow",
        "label": "printer shadow"
      },
      {
        "key": "projector_canvas",
        "label": "projector canvas"
      },
      {
        "key": "projector_canvas_shadow",
        "label": "projector canvas shadow"
      },
      {
        "key": "rack_cabinet",
        "label": "rack cabinet"
      },
      {
        "key": "rack_cabinet_shadow",
        "label": "rack cabinet shadow"
      },
      {
        "key": "router_shadow",
        "label": "router shadow"
      },
      {
        "key": "satellite_dish",
        "label": "satellite dish"
      },
      {
        "key": "satellite_dish_shadow",
        "label": "satellite dish shadow"
      },
      {
        "key": "satellite",
        "label": "satellite"
      },
      {
        "key": "satellite_shadow",
        "label": "satellite shadow"
      },
      {
        "key": "scanner",
        "label": "scanner"
      },
      {
        "key": "scanner_shadow",
        "label": "scanner shadow"
      },
      {
        "key": "server_shadow",
        "label": "server shadow"
      },
      {
        "key": "social_media",
        "label": "social media"
      },
      {
        "key": "social_media_shadow",
        "label": "social media shadow"
      },
      {
        "key": "tablet",
        "label": "tablet"
      },
      {
        "key": "tablet_shadow",
        "label": "tablet shadow"
      },
      {
        "key": "terminal",
        "label": "terminal"
      },
      {
        "key": "terminal_shadow",
        "label": "terminal shadow"
      },
      {
        "key": "threat",
        "label": "threat"
      },
      {
        "key": "threat_shadow",
        "label": "threat shadow"
      },
      {
        "key": "ups",
        "label": "ups"
      },
      {
        "key": "ups_shadow",
        "label": "ups shadow"
      },
      {
        "key": "user_female",
        "label": "user female"
      },
      {
        "key": "user_female_shadow",
        "label": "user female shadow"
      },
      {
        "key": "user_male",
        "label": "user male"
      },
      {
        "key": "user_male_shadow",
        "label": "user male shadow"
      },
      {
        "key": "users",
        "label": "users"
      },
      {
        "key": "users_shadow",
        "label": "users shadow"
      },
      {
        "key": "video_projector",
        "label": "video projector"
      },
      {
        "key": "video_projector_shadow",
        "label": "video projector shadow"
      },
      {
        "key": "vr",
        "label": "vr"
      },
      {
        "key": "vr_shadow",
        "label": "vr shadow"
      },
      {
        "key": "web_hosting",
        "label": "web hosting"
      },
      {
        "key": "web_hosting_shadow",
        "label": "web hosting shadow"
      },
      {
        "key": "wireless_hub",
        "label": "wireless hub"
      },
      {
        "key": "wireless_hub_shadow",
        "label": "wireless hub shadow"
      }
    ]
  },
  {
    "id": "cisco",
    "label": "Cisco (classic)",
    "icons": [
      {
        "key": "router",
        "label": "Router",
        "suggestedTypes": [
          "router"
        ]
      },
      {
        "key": "broadcast_router",
        "label": "Broadcast Router"
      },
      {
        "key": "l3_switch",
        "label": "Layer 3 Switch",
        "suggestedTypes": [
          "switch"
        ]
      },
      {
        "key": "l2_switch",
        "label": "Switch",
        "suggestedTypes": [
          "switch"
        ]
      },
      {
        "key": "atm_switch",
        "label": "ATM Switch"
      },
      {
        "key": "firewall",
        "label": "Firewall",
        "suggestedTypes": [
          "firewall"
        ]
      },
      {
        "key": "pix_firewall",
        "label": "PIX Firewall"
      },
      {
        "key": "lock",
        "label": "Lock"
      },
      {
        "key": "network_security",
        "label": "Network Security"
      },
      {
        "key": "server_with_router",
        "label": "Server With Router"
      },
      {
        "key": "fileserver",
        "label": "File Server"
      },
      {
        "key": "file_server",
        "label": "File Server (alt)"
      },
      {
        "key": "host",
        "label": "Host",
        "suggestedTypes": [
          "server"
        ]
      },
      {
        "key": "iptv_server",
        "label": "IPTV Server"
      },
      {
        "key": "pc",
        "label": "PC",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "macintosh",
        "label": "Macintosh",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "laptop",
        "label": "Laptop",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "printer",
        "label": "Printer"
      },
      {
        "key": "mainframe",
        "label": "IBM Mainframe"
      },
      {
        "key": "antenna",
        "label": "Antenna"
      },
      {
        "key": "wireless",
        "label": "Wireless"
      },
      {
        "key": "wireless_bridge",
        "label": "Wireless Bridge"
      },
      {
        "key": "radio_tower",
        "label": "Radio Tower"
      },
      {
        "key": "satellite_dish",
        "label": "Satellite Dish"
      },
      {
        "key": "cloud",
        "label": "Cloud"
      },
      {
        "key": "tape_array",
        "label": "Tape Array"
      },
      {
        "key": "10700",
        "label": "10700"
      },
      {
        "key": "atm_router",
        "label": "ATM Router"
      },
      {
        "key": "atm_tag_switch_router",
        "label": "ATM Tag Switch Router"
      },
      {
        "key": "content_service_router",
        "label": "Content Service Router"
      },
      {
        "key": "gigabit_switch_atm_tag_router",
        "label": "Gigabit Switch ATM Tag Router"
      },
      {
        "key": "iad_router",
        "label": "IAD Router"
      },
      {
        "key": "ip_telephony_router",
        "label": "IP Telephony Router"
      },
      {
        "key": "isci_router",
        "label": "ISCI Router"
      },
      {
        "key": "mobile_access_router",
        "label": "Mobile Access Router"
      },
      {
        "key": "nce_router",
        "label": "NCE Router"
      },
      {
        "key": "netflow_router",
        "label": "Netflow Router"
      },
      {
        "key": "optical_services_router",
        "label": "Optical Services Router"
      },
      {
        "key": "router_in_building",
        "label": "Router In Building"
      },
      {
        "key": "router_with_silicon_switch",
        "label": "Router With Silicon Switch"
      },
      {
        "key": "service_router",
        "label": "Service Router"
      },
      {
        "key": "space_router",
        "label": "Space Router"
      },
      {
        "key": "storage_router",
        "label": "Storage Router"
      },
      {
        "key": "tdm_router",
        "label": "TDM Router"
      },
      {
        "key": "voice_router",
        "label": "Voice Router"
      },
      {
        "key": "wavelength_router",
        "label": "Wavelength Router"
      },
      {
        "key": "wireless_router",
        "label": "Wireless Router"
      },
      {
        "key": "atm_fast_gigabit_etherswitch",
        "label": "ATM Fast Gigabit Etherswitch"
      },
      {
        "key": "class_4_5_switch",
        "label": "Class 4 5 Switch"
      },
      {
        "key": "content_service_switch_1100",
        "label": "Content Service Switch 1100"
      },
      {
        "key": "content_switch",
        "label": "Content Switch"
      },
      {
        "key": "fibre_channel_fabric_switch",
        "label": "Fibre Channel Fabric Switch"
      },
      {
        "key": "generic_softswitch",
        "label": "Generic Softswitch"
      },
      {
        "key": "intelliswitch_stack",
        "label": "Intelliswitch Stack"
      },
      {
        "key": "isdn_switch",
        "label": "ISDN Switch"
      },
      {
        "key": "layer_2_remote_switch",
        "label": "Layer 2 Remote Switch"
      },
      {
        "key": "mgx_8000_multiservice_switch",
        "label": "MGX 8000 Multiservice Switch"
      },
      {
        "key": "multi_fabric_server_switch",
        "label": "Multi-Fabric Server Switch"
      },
      {
        "key": "multiswitch_device",
        "label": "Multiswitch Device"
      },
      {
        "key": "pbx_switch",
        "label": "PBX Switch"
      },
      {
        "key": "programmable_switch",
        "label": "Programmable Switch"
      },
      {
        "key": "server_switch",
        "label": "Server Switch"
      },
      {
        "key": "simultilayer_switch",
        "label": "Simultilayer Switch"
      },
      {
        "key": "softswitch_pgw_mgc",
        "label": "Softswitch PGW MGC"
      },
      {
        "key": "virtual_layer_switch",
        "label": "Virtual Layer Switch"
      },
      {
        "key": "voice_atm_switch",
        "label": "Voice ATM Switch"
      },
      {
        "key": "voice_switch",
        "label": "Voice Switch"
      },
      {
        "key": "workgroup_switch",
        "label": "Workgroup Switch"
      },
      {
        "key": "centri_firewall",
        "label": "Centri Firewall"
      },
      {
        "key": "cisco_security",
        "label": "Cisco Security"
      },
      {
        "key": "gatekeeper",
        "label": "Gatekeeper"
      },
      {
        "key": "guard",
        "label": "Guard"
      },
      {
        "key": "ios_firewall",
        "label": "IOS Firewall"
      },
      {
        "key": "network_security_2",
        "label": "Network Security 2"
      },
      {
        "key": "router_firewall",
        "label": "Router Firewall"
      },
      {
        "key": "cisco_unified_presence_server",
        "label": "Cisco Unified Presence Server"
      },
      {
        "key": "communications_server",
        "label": "Communications Server"
      },
      {
        "key": "directory_server",
        "label": "Directory Server"
      },
      {
        "key": "microwebserver",
        "label": "Microwebserver"
      },
      {
        "key": "moh_server",
        "label": "MOH Server"
      },
      {
        "key": "sip_proxy_server",
        "label": "SIP Proxy Server"
      },
      {
        "key": "software_based_server",
        "label": "Software Based Server"
      },
      {
        "key": "standard_host",
        "label": "Standard Host"
      },
      {
        "key": "storage_server",
        "label": "Storage Server"
      },
      {
        "key": "unity_server",
        "label": "Unity Server"
      },
      {
        "key": "voice_commserver",
        "label": "Voice Commserver"
      },
      {
        "key": "www_server",
        "label": "WWW Server"
      },
      {
        "key": "cisco_file_engine",
        "label": "Cisco File Engine"
      },
      {
        "key": "diskette",
        "label": "Diskette"
      },
      {
        "key": "fc_storage",
        "label": "FC Storage"
      },
      {
        "key": "fibre_channel_disk_subsystem",
        "label": "Fibre Channel Disk Subsystem"
      },
      {
        "key": "file_cabinet",
        "label": "File Cabinet"
      },
      {
        "key": "relational_database",
        "label": "Relational Database"
      },
      {
        "key": "web_cluster",
        "label": "Web Cluster"
      },
      {
        "key": "ground_terminal",
        "label": "Ground Terminal"
      },
      {
        "key": "satellite",
        "label": "Satellite"
      },
      {
        "key": "wi_fi_tag",
        "label": "Wi-Fi Tag"
      },
      {
        "key": "wireless_location_appliance",
        "label": "Wireless Location Appliance"
      },
      {
        "key": "wireless_transport",
        "label": "Wireless Transport"
      },
      {
        "key": "wlan_controller",
        "label": "WLAN Controller"
      },
      {
        "key": "ibm_mini_as400",
        "label": "IBM Mini AS400"
      },
      {
        "key": "ibm_tower",
        "label": "IBM Tower"
      },
      {
        "key": "microphone",
        "label": "Microphone"
      },
      {
        "key": "pc_adapter_card",
        "label": "PC Adapter Card"
      },
      {
        "key": "pc_routercard",
        "label": "PC Routercard"
      },
      {
        "key": "scanner",
        "label": "Scanner"
      },
      {
        "key": "speaker",
        "label": "Speaker"
      },
      {
        "key": "sun_workstation",
        "label": "Sun Workstation"
      },
      {
        "key": "supercomputer",
        "label": "Supercomputer"
      },
      {
        "key": "tablet",
        "label": "Tablet"
      },
      {
        "key": "terminal",
        "label": "Terminal"
      },
      {
        "key": "upc",
        "label": "UPC"
      },
      {
        "key": "video_camera",
        "label": "Video Camera"
      },
      {
        "key": "web_browser",
        "label": "Web Browser"
      },
      {
        "key": "workstation",
        "label": "Workstation"
      },
      {
        "key": "100baset_hub",
        "label": "100BaseT Hub"
      },
      {
        "key": "cisco_hub",
        "label": "Cisco Hub"
      },
      {
        "key": "generic_gateway",
        "label": "Generic Gateway"
      },
      {
        "key": "hub",
        "label": "Hub"
      },
      {
        "key": "mas_gateway",
        "label": "MAS Gateway"
      },
      {
        "key": "small_hub",
        "label": "Small Hub"
      },
      {
        "key": "universal_gateway",
        "label": "Universal Gateway"
      },
      {
        "key": "vpn_gateway",
        "label": "VPN Gateway"
      },
      {
        "key": "cable_modem",
        "label": "Cable Modem"
      },
      {
        "key": "cell_phone",
        "label": "Cell Phone"
      },
      {
        "key": "fax",
        "label": "Fax"
      },
      {
        "key": "hootphone",
        "label": "Hootphone"
      },
      {
        "key": "ip_phone",
        "label": "IP Phone"
      },
      {
        "key": "mobile_access_ip_phone",
        "label": "Mobile Access IP Phone"
      },
      {
        "key": "mobile_access_ip_phone_2",
        "label": "Mobile Access IP Phone 2"
      },
      {
        "key": "modem",
        "label": "Modem"
      },
      {
        "key": "phone_fax",
        "label": "Phone-fax"
      },
      {
        "key": "phone",
        "label": "Phone"
      },
      {
        "key": "rf_modem",
        "label": "RF Modem"
      },
      {
        "key": "softphone",
        "label": "Softphone"
      },
      {
        "key": "15200",
        "label": "15200"
      },
      {
        "key": "6700_series",
        "label": "6700 Series"
      },
      {
        "key": "7500ars_7513",
        "label": "7500ars (7513)"
      },
      {
        "key": "access_point",
        "label": "Access Point"
      },
      {
        "key": "ace",
        "label": "ACE"
      },
      {
        "key": "acs",
        "label": "ACS"
      },
      {
        "key": "adm",
        "label": "ADM"
      },
      {
        "key": "asa_5500",
        "label": "ASA 5500"
      },
      {
        "key": "asic_processor",
        "label": "Asic Processor"
      },
      {
        "key": "asr_1000_series",
        "label": "ASR 1000 Series"
      },
      {
        "key": "ata",
        "label": "ATA"
      },
      {
        "key": "atm_3800",
        "label": "ATM 3800"
      },
      {
        "key": "avs",
        "label": "AVS"
      },
      {
        "key": "axp",
        "label": "AXP"
      },
      {
        "key": "bbsm",
        "label": "BBSM"
      },
      {
        "key": "breakout_box",
        "label": "Breakout Box"
      },
      {
        "key": "bridge",
        "label": "Bridge"
      },
      {
        "key": "bts_10200",
        "label": "BTS 10200"
      },
      {
        "key": "call_manager",
        "label": "Call Manager"
      },
      {
        "key": "car",
        "label": "Car"
      },
      {
        "key": "carrier_routing_system",
        "label": "Carrier Routing System"
      },
      {
        "key": "cddi_fddi",
        "label": "CDDI FDDI"
      },
      {
        "key": "cdm",
        "label": "CDM"
      },
      {
        "key": "cisco_1000",
        "label": "Cisco 1000"
      },
      {
        "key": "cisco_ca",
        "label": "Cisco CA"
      },
      {
        "key": "cisco_unity_express",
        "label": "Cisco Unity Express"
      },
      {
        "key": "cisco_works",
        "label": "Cisco Works"
      },
      {
        "key": "contact_acquirer",
        "label": "Contact Acquirer"
      },
      {
        "key": "contact_center",
        "label": "Contact Center"
      },
      {
        "key": "content_transformation_engine_cte",
        "label": "Content Transformation Engine (CTE)"
      },
      {
        "key": "cs_mars",
        "label": "CS-MARS"
      },
      {
        "key": "csm_s",
        "label": "CSM-S"
      },
      {
        "key": "csu_dsu",
        "label": "CSU DSU"
      },
      {
        "key": "cube",
        "label": "CUBE"
      },
      {
        "key": "detector",
        "label": "Detector"
      },
      {
        "key": "dot_dot",
        "label": "Dot-dot"
      },
      {
        "key": "dpt",
        "label": "DPT"
      },
      {
        "key": "dslam",
        "label": "DSLAM"
      },
      {
        "key": "dual_mode",
        "label": "Dual Mode"
      },
      {
        "key": "dwdm_filter",
        "label": "DWDM Filter"
      },
      {
        "key": "fddi_ring",
        "label": "FDDI Ring"
      },
      {
        "key": "front_end_processor",
        "label": "Front End Processor"
      },
      {
        "key": "general_appliance",
        "label": "General Appliance"
      },
      {
        "key": "generic_processor",
        "label": "Generic Processor"
      },
      {
        "key": "handheld",
        "label": "Handheld"
      },
      {
        "key": "hp_mini",
        "label": "HP Mini"
      },
      {
        "key": "h_323",
        "label": "H 323"
      },
      {
        "key": "icm",
        "label": "ICM"
      },
      {
        "key": "ics",
        "label": "ICS"
      },
      {
        "key": "internet_streamer",
        "label": "Internet Streamer"
      },
      {
        "key": "ios_slb",
        "label": "IOS SLB"
      },
      {
        "key": "ip",
        "label": "IP"
      },
      {
        "key": "iptc",
        "label": "IPTC"
      },
      {
        "key": "iptv_content_manager",
        "label": "IPTV Content Manager"
      },
      {
        "key": "ip_communicator",
        "label": "IP Communicator"
      },
      {
        "key": "ip_dsl",
        "label": "IP DSL"
      },
      {
        "key": "itp",
        "label": "ITP"
      },
      {
        "key": "jbod",
        "label": "JBOD"
      },
      {
        "key": "key",
        "label": "Key"
      },
      {
        "key": "keys",
        "label": "Keys"
      },
      {
        "key": "lan_to_lan",
        "label": "LAN to LAN"
      },
      {
        "key": "lightweight_ap",
        "label": "Lightweight AP"
      },
      {
        "key": "longreach_cpe",
        "label": "Longreach CPE"
      },
      {
        "key": "mau",
        "label": "MAU"
      },
      {
        "key": "mcu",
        "label": "MCU"
      },
      {
        "key": "me1100",
        "label": "ME1100"
      },
      {
        "key": "mediator",
        "label": "Mediator"
      },
      {
        "key": "meetingplace",
        "label": "Meetingplace"
      },
      {
        "key": "mesh_ap",
        "label": "Mesh AP"
      },
      {
        "key": "metro_1500",
        "label": "Metro 1500"
      },
      {
        "key": "mini_vax",
        "label": "Mini VAX"
      },
      {
        "key": "mobile_streamer",
        "label": "Mobile Streamer"
      },
      {
        "key": "mse",
        "label": "MSE"
      },
      {
        "key": "mux",
        "label": "MUX"
      },
      {
        "key": "mxe",
        "label": "MXE"
      },
      {
        "key": "nac_appliance",
        "label": "NAC Appliance"
      },
      {
        "key": "nce",
        "label": "NCE"
      },
      {
        "key": "netranger",
        "label": "Netranger"
      },
      {
        "key": "netsonar",
        "label": "Netsonar"
      },
      {
        "key": "network_management",
        "label": "Network Management"
      },
      {
        "key": "nexus_1000",
        "label": "Nexus 1000"
      },
      {
        "key": "nexus_2000_fabric_extender",
        "label": "Nexus 2000 Fabric Extender"
      },
      {
        "key": "nexus_5000",
        "label": "Nexus 5000"
      },
      {
        "key": "nexus_7000",
        "label": "Nexus 7000"
      },
      {
        "key": "octel",
        "label": "Octel"
      },
      {
        "key": "ons15500",
        "label": "ONS15500"
      },
      {
        "key": "optical_amplifier",
        "label": "Optical Amplifier"
      },
      {
        "key": "optical_transport",
        "label": "Optical Transport"
      },
      {
        "key": "pad_1",
        "label": "PAD 1"
      },
      {
        "key": "pad_2",
        "label": "PAD 2"
      },
      {
        "key": "page_icon",
        "label": "Page Icon"
      },
      {
        "key": "pbx",
        "label": "PBX"
      },
      {
        "key": "pc_software",
        "label": "PC Software"
      },
      {
        "key": "pc_video",
        "label": "PC Video"
      },
      {
        "key": "pda",
        "label": "PDA"
      },
      {
        "key": "pmc",
        "label": "PMC"
      },
      {
        "key": "protocol_translator",
        "label": "Protocol Translator"
      },
      {
        "key": "pxf",
        "label": "PXF"
      },
      {
        "key": "ratemux",
        "label": "Ratemux"
      },
      {
        "key": "repeater",
        "label": "Repeater"
      },
      {
        "key": "route_switch_processor",
        "label": "Route Switch Processor"
      },
      {
        "key": "rpsrps",
        "label": "RPSRPS"
      },
      {
        "key": "services",
        "label": "Services"
      },
      {
        "key": "service_control",
        "label": "Service Control"
      },
      {
        "key": "set_top_box",
        "label": "Set Top Box"
      },
      {
        "key": "ssc",
        "label": "SSC"
      },
      {
        "key": "ssl_terminator",
        "label": "SSL Terminator"
      },
      {
        "key": "stb",
        "label": "STB"
      },
      {
        "key": "stp",
        "label": "STP"
      },
      {
        "key": "streamer",
        "label": "Streamer"
      },
      {
        "key": "svx",
        "label": "SVX"
      },
      {
        "key": "telecommuter_icon",
        "label": "Telecommuter Icon"
      },
      {
        "key": "telepresence",
        "label": "Telepresence"
      },
      {
        "key": "token",
        "label": "Token"
      },
      {
        "key": "token_2",
        "label": "Token 2"
      },
      {
        "key": "tp_mcu",
        "label": "TP MCU"
      },
      {
        "key": "transpath",
        "label": "Transpath"
      },
      {
        "key": "truck",
        "label": "Truck"
      },
      {
        "key": "turret",
        "label": "Turret"
      },
      {
        "key": "tv",
        "label": "TV"
      },
      {
        "key": "ubr910",
        "label": "UBR910"
      },
      {
        "key": "umg_series",
        "label": "UMG Series"
      },
      {
        "key": "ups",
        "label": "UPS"
      },
      {
        "key": "vault",
        "label": "Vault"
      },
      {
        "key": "vip",
        "label": "VIP"
      },
      {
        "key": "vpn_concentrator",
        "label": "VPN Concentrator"
      },
      {
        "key": "vss",
        "label": "VSS"
      },
      {
        "key": "wae",
        "label": "WAE"
      },
      {
        "key": "wism",
        "label": "WISM"
      }
    ]
  },
  {
    "id": "cisco19",
    "label": "Cisco (19)",
    "icons": [
      {
        "key": "router",
        "label": "Router",
        "suggestedTypes": [
          "router"
        ]
      },
      {
        "key": "l3_switch",
        "label": "Layer 3 Switch",
        "suggestedTypes": [
          "switch"
        ]
      },
      {
        "key": "l2_switch",
        "label": "Layer 2 Switch",
        "suggestedTypes": [
          "switch"
        ]
      },
      {
        "key": "workgroup_switch",
        "label": "Workgroup Switch"
      },
      {
        "key": "asa_5500",
        "label": "ASA 5500",
        "suggestedTypes": [
          "firewall"
        ]
      },
      {
        "key": "firewall",
        "label": "Firewall",
        "suggestedTypes": [
          "firewall"
        ]
      },
      {
        "key": "server",
        "label": "Server",
        "suggestedTypes": [
          "server"
        ]
      },
      {
        "key": "blade_server",
        "label": "Blade Server",
        "suggestedTypes": [
          "server"
        ]
      },
      {
        "key": "storage",
        "label": "Storage",
        "suggestedTypes": [
          "nas"
        ]
      },
      {
        "key": "cloud",
        "label": "Cloud"
      },
      {
        "key": "cloud_alt",
        "label": "Cloud (alt)"
      },
      {
        "key": "wireless_access_point",
        "label": "Wireless AP",
        "suggestedTypes": [
          "access_point"
        ]
      },
      {
        "key": "camera",
        "label": "Camera",
        "suggestedTypes": [
          "camera"
        ]
      },
      {
        "key": "cell_phone",
        "label": "Cell Phone"
      },
      {
        "key": "ip_phone",
        "label": "IP Phone",
        "suggestedTypes": [
          "phone"
        ]
      },
      {
        "key": "laptop",
        "label": "Laptop",
        "suggestedTypes": [
          "workstation"
        ]
      },
      {
        "key": "printer",
        "label": "Printer"
      },
      {
        "key": "router_with_firewall",
        "label": "Router With Firewall"
      },
      {
        "key": "asr_1000",
        "label": "ASR 1000"
      },
      {
        "key": "asr_9000",
        "label": "ASR 9000"
      },
      {
        "key": "branch",
        "label": "Branch"
      },
      {
        "key": "data_center",
        "label": "Data Center"
      },
      {
        "key": "3g_4g_indicator",
        "label": "3g 4g indicator"
      },
      {
        "key": "6500_vss",
        "label": "6500 vss"
      },
      {
        "key": "6500_vss2",
        "label": "6500 vss2"
      },
      {
        "key": "access_control_and_trustsec",
        "label": "access control and trustsec"
      },
      {
        "key": "aci",
        "label": "aci"
      },
      {
        "key": "aci2",
        "label": "aci2"
      },
      {
        "key": "acibg",
        "label": "aciBg"
      },
      {
        "key": "acs",
        "label": "acs"
      },
      {
        "key": "ad_decoder",
        "label": "ad decoder"
      },
      {
        "key": "ad_encoder",
        "label": "ad encoder"
      },
      {
        "key": "analysis_correlation",
        "label": "analysis correlation"
      },
      {
        "key": "anomaly_detection",
        "label": "anomaly detection"
      },
      {
        "key": "anti_malware",
        "label": "anti malware"
      },
      {
        "key": "anti_malware2",
        "label": "anti malware2"
      },
      {
        "key": "appnav",
        "label": "appnav"
      },
      {
        "key": "avc_application_visibility_control",
        "label": "avc application visibility control"
      },
      {
        "key": "avc_application_visibility_control2",
        "label": "avc application visibility control2"
      },
      {
        "key": "bg1",
        "label": "bg1"
      },
      {
        "key": "bg10",
        "label": "bg10"
      },
      {
        "key": "bg2",
        "label": "bg2"
      },
      {
        "key": "bg3",
        "label": "bg3"
      },
      {
        "key": "bg4",
        "label": "bg4"
      },
      {
        "key": "bg5",
        "label": "bg5"
      },
      {
        "key": "bg6",
        "label": "bg6"
      },
      {
        "key": "bg7",
        "label": "bg7"
      },
      {
        "key": "bg8",
        "label": "bg8"
      },
      {
        "key": "bg9",
        "label": "bg9"
      },
      {
        "key": "branch2",
        "label": "branch2"
      },
      {
        "key": "camera2",
        "label": "camera2"
      },
      {
        "key": "cell_phone2",
        "label": "cell phone2"
      },
      {
        "key": "cisco_15800",
        "label": "cisco 15800"
      },
      {
        "key": "cisco_dna",
        "label": "cisco dna"
      },
      {
        "key": "cisco_dna_center",
        "label": "cisco dna center"
      },
      {
        "key": "cisco_meetingplace_express",
        "label": "cisco meetingplace express"
      },
      {
        "key": "cisco_security_manager",
        "label": "cisco security manager"
      },
      {
        "key": "cisco_unified_contact_center_enterprise_and_hosted",
        "label": "cisco unified contact center enterprise and hosted"
      },
      {
        "key": "cisco_unified_presence_service",
        "label": "cisco unified presence service"
      },
      {
        "key": "clock",
        "label": "clock"
      },
      {
        "key": "cognitive",
        "label": "cognitive"
      },
      {
        "key": "collab1",
        "label": "collab1"
      },
      {
        "key": "collab2",
        "label": "collab2"
      },
      {
        "key": "collab3",
        "label": "collab3"
      },
      {
        "key": "collab4",
        "label": "collab4"
      },
      {
        "key": "communications_manager",
        "label": "communications manager"
      },
      {
        "key": "contact_center_express",
        "label": "contact center express"
      },
      {
        "key": "content_recording_streaming_server",
        "label": "content recording streaming server"
      },
      {
        "key": "content_router",
        "label": "content router"
      },
      {
        "key": "csr_1000v",
        "label": "csr 1000v"
      },
      {
        "key": "database_relational",
        "label": "database relational"
      },
      {
        "key": "data_center2",
        "label": "data center2"
      },
      {
        "key": "da_decoder",
        "label": "da decoder"
      },
      {
        "key": "da_encoder",
        "label": "da encoder"
      },
      {
        "key": "dns_server",
        "label": "dns server"
      },
      {
        "key": "dns_server2",
        "label": "dns server2"
      },
      {
        "key": "dual_mode_access_point",
        "label": "dual mode access point"
      },
      {
        "key": "email_security",
        "label": "email security"
      },
      {
        "key": "fabric_interconnect",
        "label": "fabric interconnect"
      },
      {
        "key": "fibre_channel_director_mds_9000",
        "label": "fibre channel director mds 9000"
      },
      {
        "key": "fibre_channel_fabric_switch",
        "label": "fibre channel fabric switch"
      },
      {
        "key": "flow_analytics",
        "label": "flow analytics"
      },
      {
        "key": "flow_analytics2",
        "label": "flow analytics2"
      },
      {
        "key": "flow_collector",
        "label": "flow collector"
      },
      {
        "key": "h323",
        "label": "h323"
      },
      {
        "key": "handheld",
        "label": "handheld"
      },
      {
        "key": "handheld2",
        "label": "handheld2"
      },
      {
        "key": "hdtv",
        "label": "hdtv"
      },
      {
        "key": "hdtv2",
        "label": "hdtv2"
      },
      {
        "key": "home_office",
        "label": "home office"
      },
      {
        "key": "home_office2",
        "label": "home office2"
      },
      {
        "key": "host_based_security",
        "label": "host based security"
      },
      {
        "key": "hypervisor",
        "label": "hypervisor"
      },
      {
        "key": "immersive_telepresence_endpoint",
        "label": "immersive telepresence endpoint"
      },
      {
        "key": "ips_ids",
        "label": "ips ids"
      },
      {
        "key": "ip_ip_gateway",
        "label": "ip ip gateway"
      },
      {
        "key": "ip_phone2",
        "label": "ip phone2"
      },
      {
        "key": "ip_telephone_router",
        "label": "ip telephone router"
      },
      {
        "key": "ironport",
        "label": "ironport"
      },
      {
        "key": "ise",
        "label": "ise"
      },
      {
        "key": "joystick_keyboard",
        "label": "joystick keyboard"
      },
      {
        "key": "joystick_keyboard2",
        "label": "joystick keyboard2"
      },
      {
        "key": "key",
        "label": "key"
      },
      {
        "key": "key2",
        "label": "key2"
      },
      {
        "key": "l2_modular",
        "label": "l2 modular"
      },
      {
        "key": "l2_modular2",
        "label": "l2 modular2"
      },
      {
        "key": "l2_switch_with_dual_supervisor",
        "label": "l2 switch with dual supervisor"
      },
      {
        "key": "l3_modular",
        "label": "l3 modular"
      },
      {
        "key": "l3_modular2",
        "label": "l3 modular2"
      },
      {
        "key": "l3_modular3",
        "label": "l3 modular3"
      },
      {
        "key": "l3_switch_with_dual_supervisor",
        "label": "l3 switch with dual supervisor"
      },
      {
        "key": "laptop2",
        "label": "laptop2"
      },
      {
        "key": "laptop_video_client",
        "label": "laptop video client"
      },
      {
        "key": "laptop_video_client2",
        "label": "laptop video client2"
      },
      {
        "key": "layer3_nexus_5k_switch",
        "label": "layer3 nexus 5k switch"
      },
      {
        "key": "ldap",
        "label": "ldap"
      },
      {
        "key": "ldap2",
        "label": "ldap2"
      },
      {
        "key": "load_balancer",
        "label": "load balancer"
      },
      {
        "key": "lock",
        "label": "lock"
      },
      {
        "key": "lock2",
        "label": "lock2"
      },
      {
        "key": "media_server",
        "label": "media server"
      },
      {
        "key": "meeting_scheduling_and_management_server",
        "label": "meeting scheduling and management server"
      },
      {
        "key": "mesh_access_point",
        "label": "mesh access point"
      },
      {
        "key": "monitor",
        "label": "monitor"
      },
      {
        "key": "monitoring",
        "label": "monitoring"
      },
      {
        "key": "multipoint_meeting_server",
        "label": "multipoint meeting server"
      },
      {
        "key": "nac_appliance",
        "label": "nac appliance"
      },
      {
        "key": "nam_virtual_service_blade",
        "label": "nam virtual service blade"
      },
      {
        "key": "netflow_router",
        "label": "netflow router"
      },
      {
        "key": "netflow_router2",
        "label": "netflow router2"
      },
      {
        "key": "netflow_router3",
        "label": "netflow router3"
      },
      {
        "key": "net_mgmt_appliance",
        "label": "net mgmt appliance"
      },
      {
        "key": "next_generation_intrusion_prevention_system",
        "label": "next generation intrusion prevention system"
      },
      {
        "key": "nexus_1010",
        "label": "nexus 1010"
      },
      {
        "key": "nexus_1k",
        "label": "nexus 1k"
      },
      {
        "key": "nexus_1kv_vsm",
        "label": "nexus 1kv vsm"
      },
      {
        "key": "nexus_2000_10ge",
        "label": "nexus 2000 10ge"
      },
      {
        "key": "nexus_2k",
        "label": "nexus 2k"
      },
      {
        "key": "nexus_3k",
        "label": "nexus 3k"
      },
      {
        "key": "nexus_4k",
        "label": "nexus 4k"
      },
      {
        "key": "nexus_5k",
        "label": "nexus 5k"
      },
      {
        "key": "nexus_5k_with_integrated_vsm",
        "label": "nexus 5k with integrated vsm"
      },
      {
        "key": "nexus_7k",
        "label": "nexus 7k"
      },
      {
        "key": "nexus_9300",
        "label": "nexus 9300"
      },
      {
        "key": "nexus_9500",
        "label": "nexus 9500"
      },
      {
        "key": "operations_manager",
        "label": "operations manager"
      },
      {
        "key": "phone_polycom",
        "label": "phone polycom"
      },
      {
        "key": "phone_polycom2",
        "label": "phone polycom2"
      },
      {
        "key": "policy_configuration",
        "label": "policy configuration"
      },
      {
        "key": "pos",
        "label": "pos"
      },
      {
        "key": "pos2",
        "label": "pos2"
      },
      {
        "key": "posture_assessment",
        "label": "posture assessment"
      },
      {
        "key": "primary_codec",
        "label": "primary codec"
      },
      {
        "key": "printer2",
        "label": "printer2"
      },
      {
        "key": "router_with_firewall2",
        "label": "router with firewall2"
      },
      {
        "key": "router_with_voice",
        "label": "router with voice"
      },
      {
        "key": "rps",
        "label": "rps"
      },
      {
        "key": "secondary_codec",
        "label": "secondary codec"
      },
      {
        "key": "secure_catalyst_switch_color",
        "label": "secure catalyst switch color"
      },
      {
        "key": "secure_catalyst_switch_color2",
        "label": "secure catalyst switch color2"
      },
      {
        "key": "secure_catalyst_switch_color3",
        "label": "secure catalyst switch color3"
      },
      {
        "key": "secure_catalyst_switch_subdued",
        "label": "secure catalyst switch subdued"
      },
      {
        "key": "secure_catalyst_switch_subdued2",
        "label": "secure catalyst switch subdued2"
      },
      {
        "key": "secure_endpoints",
        "label": "secure endpoints"
      },
      {
        "key": "secure_endpoints2",
        "label": "secure endpoints2"
      },
      {
        "key": "secure_endpoint_pc",
        "label": "secure endpoint pc"
      },
      {
        "key": "secure_endpoint_pc2",
        "label": "secure endpoint pc2"
      },
      {
        "key": "secure_router",
        "label": "secure router"
      },
      {
        "key": "secure_server",
        "label": "secure server"
      },
      {
        "key": "secure_server2",
        "label": "secure server2"
      },
      {
        "key": "secure_switch",
        "label": "secure switch"
      },
      {
        "key": "security_management",
        "label": "security management"
      },
      {
        "key": "server2",
        "label": "server2"
      },
      {
        "key": "service_ready_engine",
        "label": "service ready engine"
      },
      {
        "key": "set_top",
        "label": "set top"
      },
      {
        "key": "set_top2",
        "label": "set top2"
      },
      {
        "key": "shield",
        "label": "shield"
      },
      {
        "key": "ssl_terminator",
        "label": "ssl terminator"
      },
      {
        "key": "stealthwatch_management_console_smc",
        "label": "stealthwatch management console smc"
      },
      {
        "key": "stealthwatch_management_console_smc2",
        "label": "stealthwatch management console smc2"
      },
      {
        "key": "surveillance_camera",
        "label": "surveillance camera"
      },
      {
        "key": "surveillance_camera2",
        "label": "surveillance camera2"
      },
      {
        "key": "tablet",
        "label": "tablet"
      },
      {
        "key": "tablet2",
        "label": "tablet2"
      },
      {
        "key": "telepresence_endpoint",
        "label": "telepresence endpoint"
      },
      {
        "key": "telepresence_endpoint_twin_data_display",
        "label": "telepresence endpoint twin data display"
      },
      {
        "key": "telepresence_exchange",
        "label": "telepresence exchange"
      },
      {
        "key": "threat_intelligence",
        "label": "threat intelligence"
      },
      {
        "key": "transcoder",
        "label": "transcoder"
      },
      {
        "key": "ucs_5108_blade_chassis",
        "label": "ucs 5108 blade chassis"
      },
      {
        "key": "ucs_c_series_server",
        "label": "ucs c series server"
      },
      {
        "key": "ucs_express",
        "label": "ucs express"
      },
      {
        "key": "unity",
        "label": "unity"
      },
      {
        "key": "upc_unified_personal_communicator",
        "label": "upc unified personal communicator"
      },
      {
        "key": "upc_unified_personal_communicator2",
        "label": "upc unified personal communicator2"
      },
      {
        "key": "ups",
        "label": "ups"
      },
      {
        "key": "user",
        "label": "user"
      },
      {
        "key": "user2",
        "label": "user2"
      },
      {
        "key": "vbond",
        "label": "vbond"
      },
      {
        "key": "video_analytics",
        "label": "video analytics"
      },
      {
        "key": "video_call_server",
        "label": "video call server"
      },
      {
        "key": "video_gateway",
        "label": "video gateway"
      },
      {
        "key": "virtual_desktop_service",
        "label": "virtual desktop service"
      },
      {
        "key": "virtual_matrix_switch",
        "label": "virtual matrix switch"
      },
      {
        "key": "virtual_private_network",
        "label": "virtual private network"
      },
      {
        "key": "virtual_private_network2",
        "label": "virtual private network2"
      },
      {
        "key": "virtual_private_network_connector",
        "label": "virtual private network connector"
      },
      {
        "key": "vmanage",
        "label": "vmanage"
      },
      {
        "key": "vpn_concentrator",
        "label": "vpn concentrator"
      },
      {
        "key": "vsmart",
        "label": "vsmart"
      },
      {
        "key": "vts",
        "label": "vts"
      },
      {
        "key": "vts2",
        "label": "vts2"
      },
      {
        "key": "webex",
        "label": "webex"
      },
      {
        "key": "web_application_firewall",
        "label": "web application firewall"
      },
      {
        "key": "web_reputation_filtering",
        "label": "web reputation filtering"
      },
      {
        "key": "web_reputation_filtering_2",
        "label": "web reputation filtering 2"
      },
      {
        "key": "web_security",
        "label": "web security"
      },
      {
        "key": "web_security_services",
        "label": "web security services"
      },
      {
        "key": "web_security_services2",
        "label": "web security services2"
      },
      {
        "key": "wifi_indicator",
        "label": "wifi indicator"
      },
      {
        "key": "wireless_access_point2",
        "label": "wireless access point2"
      },
      {
        "key": "wireless_bridge",
        "label": "wireless bridge"
      },
      {
        "key": "wireless_bridge2",
        "label": "wireless bridge2"
      },
      {
        "key": "wireless_connector",
        "label": "wireless connector"
      },
      {
        "key": "wireless_intrusion_prevention",
        "label": "wireless intrusion prevention"
      },
      {
        "key": "wireless_lan_controller",
        "label": "wireless lan controller"
      },
      {
        "key": "wireless_location_appliance",
        "label": "wireless location appliance"
      },
      {
        "key": "wireless_router",
        "label": "wireless router"
      },
      {
        "key": "workstation",
        "label": "workstation"
      },
      {
        "key": "workstation2",
        "label": "workstation2"
      },
      {
        "key": "x509_certificate",
        "label": "x509 certificate"
      },
      {
        "key": "x509_certificate2",
        "label": "x509 certificate2"
      }
    ]
  }
];

export function libraryIconUrl(libraryId: string, iconKey: string): string {
  return `/icon-libraries/${libraryId}/${iconKey}.svg`;
}

export function findLibrary(libraryId: string): IconLibrary | undefined {
  return ICON_LIBRARIES.find(l => l.id === libraryId);
}

export function findLibraryIcon(libraryId: string, iconKey: string): IconLibraryEntry | undefined {
  return findLibrary(libraryId)?.icons.find(i => i.key === iconKey);
}
