#!/usr/bin/env bash
# Generates a configurable volume of demo data (projects, subnets, devices,
# agents, and their connections) for scale / load testing.
#
# Usage:
#   scripts/scale-data.sh --projects 5 --subnets 3 --devices 20 --agents 4
#   scripts/scale-data.sh                         # prompts for any missing values
#   API=https://host/api scripts/scale-data.sh    # override API base URL
#
# Each run uses a unique timestamped tag so repeated runs never collide.

set -e

API="${API:-http://localhost:3001/api}"

# ── Output helpers ────────────────────────────────────────────────────────────

info()    { echo "  $*"; }
success() { echo "✓ $*"; }
error()   { echo "✗ $*" >&2; exit 1; }
header()  { echo; echo "── $* ──"; }

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Creates demo data at whatever scale you need.

Options:
  --projects N   Number of projects to create
  --subnets N    Subnets per project
  --devices N    Devices per project
  --agents N     Agents per project
  -h, --help     Show this help

Any option not provided will be prompted interactively.

Environment:
  API            Base URL (default: http://localhost:3001/api)
EOF
}

# ── Request helpers ───────────────────────────────────────────────────────────

post() {
  local url="$1" data="$2"
  curl -skf -X POST -H "Content-Type: application/json" -d "$data" "$url" 2>/dev/null \
    || { echo "✗ POST $url failed" >&2; return 1; }
}

extract_id() {
  grep -o '"id":[0-9]*' | head -1 | grep -o '[0-9]*'
}

# ── Argument parsing ──────────────────────────────────────────────────────────

PROJECTS=""; SUBNETS=""; DEVICES=""; AGENTS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --projects) PROJECTS="$2"; shift 2 ;;
    --subnets)  SUBNETS="$2";  shift 2 ;;
    --devices)  DEVICES="$2";  shift 2 ;;
    --agents)   AGENTS="$2";   shift 2 ;;
    -h|--help)  usage; exit 0 ;;
    *)          echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

# Prompt for any count not supplied; re-prompt on non-numeric/negative.
prompt_count() {
  local current="$1" label="$2" default="$3"
  local value="$current"
  while ! [[ "$value" =~ ^[0-9]+$ ]]; do
    read -r -p "  $label [$default]: " value
    [[ -z "$value" ]] && value="$default"
    if ! [[ "$value" =~ ^[0-9]+$ ]]; then
      echo "    must be a non-negative integer" >&2
    fi
  done
  echo "$value"
}

if [[ -z "$PROJECTS" || -z "$SUBNETS" || -z "$DEVICES" || -z "$AGENTS" ]]; then
  header "How much data would you like?"
fi
PROJECTS=$(prompt_count "$PROJECTS" "projects"            3)
SUBNETS=$(prompt_count  "$SUBNETS"  "subnets per project" 3)
DEVICES=$(prompt_count  "$DEVICES"  "devices per project" 10)
AGENTS=$(prompt_count   "$AGENTS"   "agents per project"  4)

if (( PROJECTS < 1 )); then
  error "--projects must be at least 1"
fi

# ── Preflight ─────────────────────────────────────────────────────────────────

header "Checking server"
if ! curl -skf "$API/projects" > /dev/null 2>&1; then
  error "Server is not running at $API. Start it first (systemctl --user start network-manager)"
fi
success "Server is reachable at $API"

RUN_TAG="scale-$(date +%Y%m%d-%H%M%S)"
RUN_LABEL="Scale Test $(date '+%Y-%m-%d %H:%M')"
success "Run tag: $RUN_TAG"

# ── Data pools ────────────────────────────────────────────────────────────────

DEVICE_TYPES=(router switch server workstation nas firewall access_point iot camera)
# Weighted status list — mostly up, some warning, a few down/unknown.
DEVICE_STATUSES=(up up up up up up up warning warning down unknown)
AGENT_TYPE_KEYS=(wazuh zabbix prometheus elk)
AGENT_TYPE_LABELS=(Wazuh Zabbix Prometheus ELK)
AGENT_STATUSES=(active active active inactive error unknown)

pick() {  # pick <array-name> <index>
  local -n arr="$1"
  local idx=$(( $2 % ${#arr[@]} ))
  echo "${arr[$idx]}"
}

# ── Main loop ─────────────────────────────────────────────────────────────────

TOTAL_SUBNETS=0
TOTAL_DEVICES=0
TOTAL_AGENTS=0
TOTAL_CONNS=0
TOTAL_AGENT_CONNS=0

for (( p=1; p<=PROJECTS; p++ )); do
  header "Project $p of $PROJECTS"

  PSLUG="${RUN_TAG}-p${p}"
  PNAME="${RUN_LABEL} / Project ${p}"
  PID=$(post "$API/projects" "{
    \"name\": \"$PNAME\",
    \"slug\": \"$PSLUG\",
    \"description\": \"Auto-generated by scale-data.sh (${SUBNETS} subnets, ${DEVICES} devices, ${AGENTS} agents)\"
  }" | extract_id)
  [[ -z "$PID" ]] && error "Failed to create project $p"
  success "Project: $PNAME (id: $PID)"
  P="$API/projects/$PID"

  # Seed builtin agent types (needed before any agent can reference them)
  if (( AGENTS > 0 )); then
    for i in "${!AGENT_TYPE_KEYS[@]}"; do
      key="${AGENT_TYPE_KEYS[$i]}"
      label="${AGENT_TYPE_LABELS[$i]}"
      post "$P/agent-types" "{
        \"label\": \"$label\",
        \"key\": \"$key\",
        \"icon_source\": \"builtin\",
        \"icon_builtin_key\": \"$key\"
      }" > /dev/null
    done
    info "Seeded ${#AGENT_TYPE_KEYS[@]} agent types"
  fi

  # ── Subnets ────────────────────────────────────────────────────────────────
  SUBNET_IDS=()
  # Use project index modulo 250 for the second octet so it stays a valid IPv4 byte
  P_OCTET=$(( (p - 1) % 250 + 1 ))
  for (( s=1; s<=SUBNETS; s++ )); do
    S_OCTET=$(( s - 1 ))
    CIDR="10.${P_OCTET}.${S_OCTET}.0/24"
    VLAN=$(( P_OCTET * 100 + s ))
    SID=$(post "$P/subnets" "{
      \"name\": \"P${p}-Subnet-${s}\",
      \"cidr\": \"$CIDR\",
      \"vlan_id\": $VLAN,
      \"description\": \"Generated subnet $s for project $p\"
    }" | extract_id)
    [[ -z "$SID" ]] && error "Failed to create subnet $s for project $p"
    SUBNET_IDS+=("$SID")
  done
  (( SUBNETS > 0 )) && info "Created $SUBNETS subnets"
  TOTAL_SUBNETS=$(( TOTAL_SUBNETS + SUBNETS ))

  # ── Devices ────────────────────────────────────────────────────────────────
  DEVICE_IDS=()
  for (( d=1; d<=DEVICES; d++ )); do
    dtype=$(pick DEVICE_TYPES $(( d - 1 )))
    dstatus=$(pick DEVICE_STATUSES $(( (d * 7 + p * 3) )))
    DNAME=$(printf "P%d-Device-%03d" "$p" "$d")

    # Assign a subnet (if any) round-robin
    subnet_field=""
    ips_field="[]"
    if (( SUBNETS > 0 )); then
      sidx=$(( (d - 1) % SUBNETS ))
      SID="${SUBNET_IDS[$sidx]}"
      subnet_field=",\"subnet_id\": $SID"
      # Pack up to ~240 devices per subnet by wrapping the host octet
      host_octet=$(( 10 + (d - 1) / SUBNETS % 240 ))
      IP="10.${P_OCTET}.${sidx}.${host_octet}"
      ips_field="[{\"ip_address\": \"$IP\", \"is_primary\": true}]"
    fi

    DID=$(post "$P/devices" "{
      \"name\": \"$DNAME\",
      \"type\": \"$dtype\",
      \"hosting_type\": \"baremetal\",
      \"status\": \"$dstatus\",
      \"ips\": $ips_field
      $subnet_field
    }" | extract_id)
    [[ -z "$DID" ]] && error "Failed to create device $d for project $p"
    DEVICE_IDS+=("$DID")

    # Every 3rd device gets a few open ports
    if (( d % 3 == 0 )); then
      for port_svc in "22:ssh" "80:http" "443:https"; do
        IFS=: read -r pnum svc <<< "$port_svc"
        post "$P/devices/$DID/ports" "{\"port_number\": $pnum, \"state\": \"OPEN\", \"service\": \"$svc\"}" > /dev/null
      done
    fi

    # Every 5th device gets an SSH credential
    if (( d % 5 == 0 )); then
      post "$P/credentials" "{
        \"device_id\": $DID,
        \"username\": \"admin\",
        \"password\": \"changeme-$d\",
        \"type\": \"SSH\",
        \"source\": \"scale-data.sh\"
      }" > /dev/null
    fi
  done
  (( DEVICES > 0 )) && info "Created $DEVICES devices (+ periodic ports/credentials)"
  TOTAL_DEVICES=$(( TOTAL_DEVICES + DEVICES ))

  # ── Device connections (random tree: each device linked to a prior one) ────
  CONN_COUNT=0
  if (( DEVICES >= 2 )); then
    for (( d=1; d<DEVICES; d++ )); do
      parent_idx=$(( RANDOM % d ))
      SRC="${DEVICE_IDS[$parent_idx]}"
      TGT="${DEVICE_IDS[$d]}"
      post "$P/connections" "{
        \"source_device_id\": $SRC,
        \"target_device_id\": $TGT,
        \"connection_type\": \"ethernet\",
        \"label\": \"link-$d\"
      }" > /dev/null
      CONN_COUNT=$(( CONN_COUNT + 1 ))
    done
    info "Created $CONN_COUNT device connections"
  fi
  TOTAL_CONNS=$(( TOTAL_CONNS + CONN_COUNT ))

  # ── Agents ─────────────────────────────────────────────────────────────────
  AGENT_IDS=()
  for (( a=1; a<=AGENTS; a++ )); do
    atype=$(pick AGENT_TYPE_KEYS $(( a - 1 )))
    astatus=$(pick AGENT_STATUSES $(( a + p )))
    ANAME=$(printf "P%d-Agent-%02d" "$p" "$a")

    device_field=""
    if (( DEVICES > 0 )); then
      # Pseudo-random device assignment
      didx=$(( (a * 13 + p) % DEVICES ))
      device_field=",\"device_id\": ${DEVICE_IDS[$didx]}"
    fi

    AID=$(post "$P/agents" "{
      \"name\": \"$ANAME\",
      \"agent_type\": \"$atype\",
      \"status\": \"$astatus\",
      \"checkin_schedule\": \"every 60s\",
      \"version\": \"1.0.${a}\"
      $device_field
    }" | extract_id)
    [[ -z "$AID" ]] && error "Failed to create agent $a for project $p"
    AGENT_IDS+=("$AID")
  done
  (( AGENTS > 0 )) && info "Created $AGENTS agents"
  TOTAL_AGENTS=$(( TOTAL_AGENTS + AGENTS ))

  # ── Agent connections (chain each agent to the previous one) ───────────────
  AGENT_CONN_COUNT=0
  if (( AGENTS >= 2 )); then
    for (( a=1; a<AGENTS; a++ )); do
      SRC="${AGENT_IDS[$((a-1))]}"
      TGT="${AGENT_IDS[$a]}"
      post "$P/agent-connections" "{
        \"source_agent_id\": $SRC,
        \"target_agent_id\": $TGT,
        \"connection_type\": \"link\",
        \"label\": \"chain-$a\"
      }" > /dev/null
      AGENT_CONN_COUNT=$(( AGENT_CONN_COUNT + 1 ))
    done
    info "Created $AGENT_CONN_COUNT agent connections"
  fi
  TOTAL_AGENT_CONNS=$(( TOTAL_AGENT_CONNS + AGENT_CONN_COUNT ))

  # ── Diagram auto-layout ────────────────────────────────────────────────────
  if (( DEVICES > 0 || SUBNETS > 0 )); then
    post "$P/diagram/auto-generate" '{}' > /dev/null
    info "Diagram auto-layout applied"
  fi

  success "Project $p done"
done

# ── Summary ───────────────────────────────────────────────────────────────────

header "Summary"
echo "  Run tag:           $RUN_TAG"
echo "  Projects:          $PROJECTS"
echo "  Subnets:           $TOTAL_SUBNETS"
echo "  Devices:           $TOTAL_DEVICES"
echo "  Device connections: $TOTAL_CONNS"
echo "  Agents:            $TOTAL_AGENTS"
echo "  Agent connections: $TOTAL_AGENT_CONNS"
echo
success "Done. Filter projects by slug prefix '$RUN_TAG' to find this run."
