import { useState, useCallback, useRef, useEffect, useMemo } from 'react';
import { toPng } from 'html-to-image';
import { MonitorUp, Network as NetworkIcon, Grid3x3, Share2, Image as ImageIcon, Wand2, KeyRound, List } from 'lucide-react';
import {
  ReactFlow,
  Controls,
  Background,
  BackgroundVariant,
  addEdge,
  applyNodeChanges,
  applyEdgeChanges,
  reconnectEdge,
  type Node,
  type Edge,
  type Connection as RFConnection,
  type OnNodesChange,
  type OnEdgesChange,
  type OnConnect,
  type NodeChange,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { fetchDiagram, updatePositions, removeDeviceFromDiagram, removeSubnetFromDiagram, autoGenerateDiagram, updateNodePrefs, updateLegendItems } from '../../api/diagram';
import { fetchDevices } from '../../api/devices';
import { fetchSubnets } from '../../api/subnets';
import { createConnection, updateConnection, deleteConnection } from '../../api/connections';
import { useConfirmDialog } from '../ui/ConfirmDialog';
import { useProject } from '../../contexts/ProjectContext';
import DeviceNode from './nodes/DeviceNode';
import SubnetGroupNode from './nodes/SubnetGroupNode';
import PropertiesPanel, { type SelectedElement } from './PropertiesPanel';
import DiagramLegend from './DiagramLegend';
import ContextMenu from './ContextMenu';
import type { DiagramData, NodePrefs, LegendItem } from 'shared/types';

type AllNodePrefs = Record<string, NodePrefs>;

const nodeTypes = {
  server: DeviceNode,
  workstation: DeviceNode,
  router: DeviceNode,
  switch: DeviceNode,
  nas: DeviceNode,
  firewall: DeviceNode,
  access_point: DeviceNode,
  iot: DeviceNode,
  camera: DeviceNode,
  phone: DeviceNode,
  subnetGroup: SubnetGroupNode,
};

function toDiagramNodes(data: DiagramData, prefs: AllNodePrefs, hideHandles: boolean, showCredentials: boolean): Node[] {
  const subnetNodes: Node[] = data.subnets.map(s => {
    const p = prefs[`subnet-${s.id}`] || {};
    return {
      id: `subnet-${s.id}`,
      type: 'subnetGroup',
      position: { x: s.x, y: s.y },
      style: { width: s.width, height: s.height },
      data: {
        label: s.name,
        cidr: s.cidr,
        vlanId: s.vlan_id,
        description: s.description,
        borderColor: p.borderColor || null,
        bgColor: p.bgColor || null,
        labelColor: p.labelColor || null,
        favourite: p.favourite || false,
        borderStyle: p.borderStyle || null,
        borderRadius: p.borderRadius || null,
        borderWidth: p.borderWidth || null,
      },
    };
  });

  const deviceNodes: Node[] = data.devices.map(d => {
    const p = prefs[`device-${d.id}`] || {};
    return {
      id: `device-${d.id}`,
      type: d.type,
      position: { x: d.x, y: d.y },
      data: {
        label: d.name,
        ip: d.primary_ip || '',
        deviceType: d.type,
        os: d.os,
        hostingType: d.hosting_type,
        deviceId: d.id,
        macAddress: d.mac_address,
        location: d.location,
        notes: d.notes,
        ips: d.ips,
        borderColor: p.borderColor || null,
        bgColor: p.bgColor || null,
        labelColor: p.labelColor || null,
        customIcon: p.icon || null,
        favourite: p.favourite || false,
        hideHandles,
        hasCredentials: d.has_credentials,
        showCredentials,
      },
      ...(d.subnet_id ? { parentId: `subnet-${d.subnet_id}`, extent: 'parent' as const } : {}),
    };
  });

  return [...subnetNodes, ...deviceNodes];
}

const EDGE_BASE_WIDTHS: Record<string, number> = {
  solid: 2, dashed: 2, dotted: 2, thick: 4, animated: 2,
};
const EDGE_DASH_PATTERNS: Record<string, string | undefined> = {
  dashed: '8 4', dotted: '2 4', animated: '8 4',
};

function toDiagramEdges(data: DiagramData): Edge[] {
  const connectionEdges: Edge[] = data.connections.map(c => {
    const stroke = c.edge_color || '#64748b';
    const strokeWidth = c.edge_width ?? EDGE_BASE_WIDTHS[c.connection_type || 'solid'] ?? 2;
    const strokeDasharray = EDGE_DASH_PATTERNS[c.connection_type || 'solid'];
    const style: React.CSSProperties = { stroke, strokeWidth, ...(strokeDasharray ? { strokeDasharray } : {}) };

    const labelStyle = c.label_color ? { fill: c.label_color } : undefined;
    const labelBgStyle = c.label_bg_color ? { fill: c.label_bg_color } : { fill: 'transparent' };

    return {
      id: `edge-${c.id}`,
      source: `device-${c.source_device_id}`,
      target: `device-${c.target_device_id}`,
      sourceHandle: c.source_handle || null,
      targetHandle: c.target_handle || null,
      label: c.label || undefined,
      type: (c as any).edge_type || 'default',
      animated: c.connection_type === 'animated',
      style,
      labelStyle,
      labelBgStyle,
      labelBgPadding: [6, 3] as [number, number],
      labelBgBorderRadius: 4,
      markerEnd: { type: 'arrowclosed' as any, width: 12, height: 12 },
    };
  });
  const membershipEdges: Edge[] = data.subnet_memberships.map(m => ({
    id: `membership-${m.device_id}-${m.subnet_id}`,
    source: `device-${m.device_id}`,
    target: `subnet-${m.subnet_id}`,
    type: 'straight',
    style: { strokeDasharray: '5 5', stroke: '#94a3b8', strokeWidth: 1.5 },
    selectable: false,
    deletable: false,
  }));
  return [...connectionEdges, ...membershipEdges];
}

type ContextMenuState =
  | { x: number; y: number; kind: 'node'; nodeId: string; nodeType: 'device' | 'subnet' }
  | { x: number; y: number; kind: 'edge'; edgeId: string };

export default function NetworkDiagram() {
  const { projectId, project } = useProject();
  const base = `/p/${project.slug}`;
  const confirm = useConfirmDialog();
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const [nodes, setNodes] = useState<Node[]>([]);
  const [edges, setEdges] = useState<Edge[]>([]);
  const [addDeviceId, setAddDeviceId] = useState('');
  const [addSubnetId, setAddSubnetId] = useState('');
  const [selectedElement, setSelectedElement] = useState<SelectedElement | null>(null);
  const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null);
  const [nodePrefs, setNodePrefs] = useState<AllNodePrefs>({});
  const [showGrid, setShowGrid] = useState(() => localStorage.getItem(`diagram-show-grid-${project.slug}`) !== 'false');
  const [showEdges, setShowEdges] = useState(() => localStorage.getItem(`diagram-show-edges-${project.slug}`) !== 'false');
  const [showCredentials, setShowCredentials] = useState(() => localStorage.getItem(`diagram-show-credentials-${project.slug}`) !== 'false');
  const [showLegend, setShowLegend] = useState(() => localStorage.getItem(`diagram-show-legend-${project.slug}`) !== 'false');
  const [searchQuery, setSearchQuery] = useState('');
  const [addDeviceOpen, setAddDeviceOpen] = useState(false);
  const [addSubnetOpen, setAddSubnetOpen] = useState(false);
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const nodePrefsRef = useRef<AllNodePrefs>({});
  const showEdgesRef = useRef(showEdges);
  const showCredentialsRef = useRef(showCredentials);
  const edgeReconnectSuccessful = useRef(true);

  // Reset state when project changes
  useEffect(() => {
    setShowGrid(localStorage.getItem(`diagram-show-grid-${project.slug}`) !== 'false');
    setShowEdges(localStorage.getItem(`diagram-show-edges-${project.slug}`) !== 'false');
    setShowCredentials(localStorage.getItem(`diagram-show-credentials-${project.slug}`) !== 'false');
    setShowLegend(localStorage.getItem(`diagram-show-legend-${project.slug}`) !== 'false');
    setSelectedElement(null);
    setContextMenu(null);
    setSearchQuery('');
  }, [project.slug]);

  const { data: diagramData } = useQuery({ queryKey: ['diagram', projectId], queryFn: () => fetchDiagram(projectId) });
  const { data: allDevices } = useQuery({ queryKey: ['devices', projectId], queryFn: () => fetchDevices(projectId) });
  const { data: allSubnets } = useQuery({ queryKey: ['subnets', projectId], queryFn: () => fetchSubnets(projectId) });

  // Load node preferences from server when diagram data arrives
  useEffect(() => {
    if (diagramData?.node_preferences) {
      setNodePrefs(diagramData.node_preferences);
    }
  }, [diagramData]);

  // Keep refs in sync so effects below can read latest values without depending on them
  useEffect(() => { nodePrefsRef.current = nodePrefs; }, [nodePrefs]);
  useEffect(() => { showEdgesRef.current = showEdges; }, [showEdges]);
  useEffect(() => { showCredentialsRef.current = showCredentials; }, [showCredentials]);

  // Rebuild nodes from DB data when diagram loads.
  // Intentionally does NOT include nodePrefs, showEdges, or showCredentials — those changes
  // are handled by separate effects below to avoid resetting React Flow positions.
  useEffect(() => {
    if (diagramData) {
      setNodes(toDiagramNodes(diagramData, nodePrefsRef.current, !showEdgesRef.current, showCredentialsRef.current));
      setEdges(toDiagramEdges(diagramData));
    }
  }, [diagramData]); // eslint-disable-line react-hooks/exhaustive-deps

  // Patch hideHandles when showEdges toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, hideHandles: !showEdges } };
    }));
  }, [showEdges]);

  // Patch showCredentials when it toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, showCredentials } };
    }));
  }, [showCredentials]);

  // When nodePrefs change (colour, favourite, icon), patch only node data fields.
  // Using the functional updater preserves React Flow's internal node positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      const p = nodePrefs[n.id] || {};
      if (n.id.startsWith('subnet-')) {
        return {
          ...n,
          data: {
            ...n.data,
            borderColor: p.borderColor || null,
            bgColor: p.bgColor || null,
            labelColor: p.labelColor || null,
            favourite: p.favourite || false,
            borderStyle: p.borderStyle || null,
            borderRadius: p.borderRadius || null,
            borderWidth: p.borderWidth || null,
          },
        };
      }
      return {
        ...n,
        data: {
          ...n.data,
          borderColor: p.borderColor || null,
          bgColor: p.bgColor || null,
          labelColor: p.labelColor || null,
          favourite: p.favourite || false,
          customIcon: p.icon || null,
        },
      };
    }));
  }, [nodePrefs]);

  const savePositions = useCallback((updatedNodes: Node[]) => {
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      const devices = updatedNodes
        .filter(n => n.id.startsWith('device-'))
        .map(n => ({ id: parseInt(n.id.replace('device-', '')), x: n.position.x, y: n.position.y }));
      const subnets = updatedNodes
        .filter(n => n.id.startsWith('subnet-'))
        .map(n => ({
          id: parseInt(n.id.replace('subnet-', '')),
          x: n.position.x, y: n.position.y,
          width: (n.style?.width as number) || 400,
          height: (n.style?.height as number) || 300,
        }));
      updatePositions(projectId, { devices, subnets });
    }, 500);
  }, [projectId]);

  const onNodesChange: OnNodesChange = useCallback((changes: NodeChange[]) => {
    setNodes(nds => {
      const updated = applyNodeChanges(changes, nds);
      const hasDragEnd = changes.some(c => c.type === 'position' && !('dragging' in c && c.dragging));
      const hasResizeEnd = changes.some(c => c.type === 'dimensions' && !('resizing' in c && c.resizing));
      if (hasDragEnd || hasResizeEnd) savePositions(updated);
      return updated;
    });
  }, [savePositions]);

  const onEdgesChange: OnEdgesChange = useCallback((changes) => {
    setEdges(eds => applyEdgeChanges(changes, eds));
  }, []);

  const onConnect: OnConnect = useCallback(async (connection) => {
    if (!connection.source || !connection.target) return;
    const sourceId = parseInt(connection.source.replace('device-', ''));
    const targetId = parseInt(connection.target.replace('device-', ''));
    try {
      const newConn = await createConnection(projectId, {
        source_device_id: sourceId,
        target_device_id: targetId,
        source_handle: connection.sourceHandle ?? undefined,
        target_handle: connection.targetHandle ?? undefined,
      });
      setEdges(eds => addEdge({ ...connection, id: `edge-${newConn.id}` }, eds));
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch (err) {
      console.error('Failed to create connection:', err);
    }
  }, [projectId, queryClient]);

  const handleAddDevice = async () => {
    if (!addDeviceId) return;
    await updatePositions(projectId, { devices: [{ id: parseInt(addDeviceId), x: 100, y: 100 }] });
    queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    setAddDeviceId('');
  };

  const handleAddSubnet = async () => {
    if (!addSubnetId) return;
    await updatePositions(projectId, { subnets: [{ id: parseInt(addSubnetId), x: 50, y: 50, width: 400, height: 300 }] });
    queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    setAddSubnetId('');
  };

  const handleDeleteEdge = useCallback(async (edgeId: string) => {
    if (edgeId.startsWith('membership-')) return;
    const connId = parseInt(edgeId.replace('edge-', ''));
    await deleteConnection(projectId, connId);
    setEdges(eds => eds.filter(e => e.id !== edgeId));
  }, [projectId]);

  const onReconnectStart = useCallback(() => {
    edgeReconnectSuccessful.current = false;
  }, []);

  const onReconnect = useCallback((oldEdge: Edge, newConnection: RFConnection) => {
    edgeReconnectSuccessful.current = true;
    setEdges(eds => reconnectEdge(oldEdge, newConnection, eds));
    const connId = parseInt(oldEdge.id.replace('edge-', ''));
    updateConnection(projectId, connId, {
      source_handle: newConnection.sourceHandle ?? null,
      target_handle: newConnection.targetHandle ?? null,
    });
  }, [projectId]);

  const onReconnectEnd = useCallback((_: MouseEvent | TouchEvent, edge: Edge) => {
    if (!edgeReconnectSuccessful.current) {
      handleDeleteEdge(edge.id);
    }
    edgeReconnectSuccessful.current = true;
  }, [handleDeleteEdge]);

  const onNodeClick = useCallback((_e: React.MouseEvent, node: Node) => {
    if (node.id.startsWith('device-')) {
      setSelectedElement({ type: 'device', id: node.id, data: node.data });
    } else if (node.id.startsWith('subnet-')) {
      setSelectedElement({ type: 'subnet', id: node.id, data: node.data });
    }
  }, []);

  const onEdgeClick = useCallback((_e: React.MouseEvent, edge: Edge) => {
    if (!diagramData) return;
    const conn = diagramData.connections.find(c => `edge-${c.id}` === edge.id);
    const sourceDevice = diagramData.devices.find(d => d.id === conn?.source_device_id);
    const targetDevice = diagramData.devices.find(d => d.id === conn?.target_device_id);
    setSelectedElement({
      type: 'edge',
      id: edge.id,
      data: {
        connId: conn?.id,
        label: conn?.label,
        connectionType: conn?.connection_type,
        edgeType: (conn as any)?.edge_type || 'default',
        edgeColor: conn?.edge_color,
        edgeWidth: conn?.edge_width,
        labelColor: conn?.label_color,
        labelBgColor: conn?.label_bg_color,
        createdAt: conn?.created_at,
        sourceName: sourceDevice?.name || 'Unknown',
        targetName: targetDevice?.name || 'Unknown',
        sourceDeviceId: conn?.source_device_id,
        targetDeviceId: conn?.target_device_id,
      },
    });
  }, [diagramData]);

  const onPaneClick = useCallback(() => {
    setSelectedElement(null);
    setContextMenu(null);
  }, []);

  useEffect(() => {
    const handleKeyDown = async (e: KeyboardEvent) => {
      if (e.key !== 'Delete' && e.key !== 'Backspace') return;
      const tag = (e.target as HTMLElement).tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;
      if (selectedElement?.type === 'edge') {
        if (await confirm('Delete this connection?')) handleDeleteEdge(selectedElement.id);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedElement, handleDeleteEdge, confirm]);

  const onNodeContextMenu = useCallback((e: React.MouseEvent, node: Node) => {
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    const nodeType = node.id.startsWith('device-') ? 'device' as const : 'subnet' as const;
    setContextMenu({ x, y, kind: 'node', nodeId: node.id, nodeType });
  }, []);

  const onEdgeContextMenu = useCallback((e: React.MouseEvent, edge: Edge) => {
    if (edge.id.startsWith('membership-')) return;
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    setContextMenu({ x, y, kind: 'edge', edgeId: edge.id });
  }, []);

  const handleRemoveFromDiagram = useCallback(async (nodeId: string, nodeType: 'device' | 'subnet') => {
    const numId = parseInt(nodeId.replace(/^(device|subnet)-/, ''));
    if (!await confirm('Remove this from the diagram?')) return;
    if (nodeType === 'device') {
      await removeDeviceFromDiagram(projectId, numId);
    } else {
      await removeSubnetFromDiagram(projectId, numId);
    }
    queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
  }, [projectId, queryClient, confirm]);

  const handleConnectionUpdate = useCallback(async (connId: number, data: { label?: string | null; connection_type?: string; edge_type?: string }) => {
    await updateConnection(projectId, connId, data);
    queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
  }, [projectId, queryClient]);

  const handleExportPng = useCallback(async () => {
    const container = containerRef.current;
    if (!container) return;
    const dataUrl = await toPng(container, {
      backgroundColor: 'var(--color-surface)',
      pixelRatio: 2,
      filter: (node: Element) => !node.classList?.contains('react-flow__controls'),
    });
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = 'network-diagram.png';
    a.click();
  }, []);

  const handleAutoLayout = useCallback(async () => {
    if (!await confirm('This will clear the current diagram and auto-place all devices and subnets. Continue?')) return;
    await autoGenerateDiagram(projectId);
    queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
  }, [projectId, queryClient, confirm]);

  const displayNodes = useMemo(() => {
    if (!searchQuery.trim()) return nodes;
    const q = searchQuery.toLowerCase();
    return nodes.map(n => ({
      ...n,
      style: {
        ...n.style,
        opacity: (String(n.data?.label ?? '').toLowerCase().includes(q) || String(n.data?.ip ?? '').includes(q)) ? 1 : 0.1,
      },
    }));
  }, [nodes, searchQuery]);

  const handlePrefChange = useCallback((nodeId: string, key: keyof NodePrefs, value: any) => {
    setNodePrefs(prev => {
      const existing = prev[nodeId] || {};
      let next: AllNodePrefs;
      if (value === null || value === undefined || value === false) {
        const updated = { ...existing };
        delete updated[key];
        next = Object.keys(updated).length > 0
          ? { ...prev, [nodeId]: updated }
          : { ...prev };
        if (!Object.keys(updated).length) delete next[nodeId];
      } else {
        next = { ...prev, [nodeId]: { ...existing, [key]: value } };
      }
      const updatedPrefs = next[nodeId] || {};
      updateNodePrefs(projectId, nodeId, updatedPrefs);
      return next;
    });
  }, [projectId]);

  const handleLegendUpdate = useCallback(async (items: LegendItem[]) => {
    await updateLegendItems(projectId, items);
    queryClient.setQueryData(['diagram', projectId], (old: DiagramData | undefined) =>
      old ? { ...old, legend_items: items } : old
    );
  }, [projectId, queryClient]);

  const getContextMenuItems = useCallback(() => {
    if (!contextMenu) return [];
    const items: { label: string; onClick: () => void; danger?: boolean }[] = [];

    if (contextMenu.kind === 'edge') {
      items.push({
        label: 'Delete Connection',
        onClick: async () => { if (await confirm('Delete this connection?')) handleDeleteEdge(contextMenu.edgeId); },
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'device') {
      const deviceId = parseInt(contextMenu.nodeId.replace('device-', ''));
      items.push({ label: 'Open Device Page', onClick: () => navigate(`${base}/devices/${deviceId}`) });
    }

    items.push({
      label: 'Remove from Diagram',
      onClick: () => handleRemoveFromDiagram(contextMenu.nodeId, contextMenu.nodeType),
      danger: true,
    });

    return items;
  }, [contextMenu, base, navigate, handleRemoveFromDiagram, handleDeleteEdge, confirm]);

  // Devices not yet on diagram
  const diagramDeviceIds = new Set(diagramData?.devices.map(d => d.id) || []);
  const unplacedDevices = allDevices?.filter(d => !diagramDeviceIds.has(d.id)) || [];

  const diagramSubnetIds = new Set(diagramData?.subnets.map(s => s.id) || []);
  const unplacedSubnets = allSubnets?.filter(s => !diagramSubnetIds.has(s.id)) || [];

  const selectedPrefs = selectedElement ? nodePrefs[selectedElement.id] || {} : {};

  return (
    <div className="diagram-page">
      <div className="page-header">
        <h2>Network Diagram</h2>
      </div>

      <div className="diagram-toolbar">
        {/* Add Device */}
        <div style={{ position: 'relative' }}>
          <button
            className={`diagram-tb-btn${addDeviceOpen ? ' active' : ''}`}
            data-tooltip="Add Device"
            onClick={() => { setAddDeviceOpen(v => !v); setAddSubnetOpen(false); }}
          >
            <MonitorUp size={17} />
          </button>
          {addDeviceOpen && (
            <div className="diagram-tb-popover">
              <select value={addDeviceId} onChange={e => setAddDeviceId(e.target.value)}>
                <option value="">Select device...</option>
                {unplacedDevices.map(d => <option key={d.id} value={d.id}>{d.name} ({d.type})</option>)}
              </select>
              <button className="btn btn-primary btn-sm" disabled={!addDeviceId} onClick={() => { handleAddDevice(); setAddDeviceOpen(false); }}>
                Add
              </button>
            </div>
          )}
        </div>

        {/* Add Subnet */}
        <div style={{ position: 'relative' }}>
          <button
            className={`diagram-tb-btn${addSubnetOpen ? ' active' : ''}`}
            data-tooltip="Add Subnet"
            onClick={() => { setAddSubnetOpen(v => !v); setAddDeviceOpen(false); }}
          >
            <NetworkIcon size={17} />
          </button>
          {addSubnetOpen && (
            <div className="diagram-tb-popover">
              <select value={addSubnetId} onChange={e => setAddSubnetId(e.target.value)}>
                <option value="">Select subnet...</option>
                {unplacedSubnets.map(s => <option key={s.id} value={s.id}>{s.name} ({s.cidr})</option>)}
              </select>
              <button className="btn btn-primary btn-sm" disabled={!addSubnetId} onClick={() => { handleAddSubnet(); setAddSubnetOpen(false); }}>
                Add
              </button>
            </div>
          )}
        </div>

        {/* Toggle Grid */}
        <button
          className={`diagram-tb-btn${showGrid ? ' active' : ''}`}
          data-tooltip="Toggle Grid"
          onClick={() => setShowGrid(v => { localStorage.setItem(`diagram-show-grid-${project.slug}`, String(!v)); return !v; })}
        >
          <Grid3x3 size={17} />
        </button>

        {/* Toggle Connections */}
        <button
          className={`diagram-tb-btn${showEdges ? ' active' : ''}`}
          data-tooltip="Toggle Connections"
          onClick={() => setShowEdges(v => { localStorage.setItem(`diagram-show-edges-${project.slug}`, String(!v)); return !v; })}
        >
          <Share2 size={17} />
        </button>

        {/* Export PNG */}
        <button className="diagram-tb-btn" data-tooltip="Export PNG" onClick={handleExportPng}>
          <ImageIcon size={17} />
        </button>

        {/* Auto Layout */}
        <button className="diagram-tb-btn" data-tooltip="Auto Layout" onClick={handleAutoLayout}>
          <Wand2 size={17} />
        </button>

        {/* Toggle Credentials */}
        <button
          className={`diagram-tb-btn${showCredentials ? ' active' : ''}`}
          data-tooltip="Toggle Credentials"
          onClick={() => setShowCredentials(v => { localStorage.setItem(`diagram-show-credentials-${project.slug}`, String(!v)); return !v; })}
        >
          <KeyRound size={17} />
        </button>

        {/* Toggle Legend */}
        <button
          className={`diagram-tb-btn${showLegend ? ' active' : ''}`}
          data-tooltip="Toggle Legend"
          onClick={() => setShowLegend(v => { localStorage.setItem(`diagram-show-legend-${project.slug}`, String(!v)); return !v; })}
        >
          <List size={17} />
        </button>

        {/* Search */}
        <input
          type="text"
          className="diagram-search"
          placeholder="Search devices..."
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          style={{ marginLeft: 'auto' }}
        />
      </div>

      <div className="diagram-container" ref={containerRef} style={{ position: 'relative' }}>
        <ReactFlow
          nodes={displayNodes}
          edges={showEdges ? edges : []}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          onNodeClick={onNodeClick}
          onEdgeClick={onEdgeClick}
          onPaneClick={onPaneClick}
          onNodeContextMenu={onNodeContextMenu}
          onEdgeContextMenu={onEdgeContextMenu}
          onReconnectStart={onReconnectStart}
          onReconnect={onReconnect}
          onReconnectEnd={onReconnectEnd}

          nodeTypes={nodeTypes}
          deleteKeyCode={null}
          proOptions={{ hideAttribution: true }}
          fitView
          snapToGrid
          snapGrid={[15, 15]}
        >
          <Controls />
          {showGrid && <Background variant={BackgroundVariant.Dots} gap={15} size={1} />}
        </ReactFlow>
        {showLegend && (
          <DiagramLegend items={diagramData?.legend_items ?? []} onUpdate={handleLegendUpdate} />
        )}
        {selectedElement && (
          <PropertiesPanel
            selected={selectedElement}
            onClose={() => setSelectedElement(null)}
            nodePrefs={selectedPrefs}
            onPrefChange={(key: keyof NodePrefs, value: any) => handlePrefChange(selectedElement.id, key, value)}
            onConnectionUpdate={handleConnectionUpdate}
            projectBase={base}
          />
        )}
        {contextMenu && (
          <ContextMenu
            position={{ x: contextMenu.x, y: contextMenu.y }}
            items={getContextMenuItems()}
            onClose={() => setContextMenu(null)}
            {... (contextMenu.kind === 'node' ? {
              onColourChange: (colour: string | null) => handlePrefChange(contextMenu.nodeId, 'borderColor', colour),
              currentColour: nodePrefs[contextMenu.nodeId]?.borderColor || null,
            } : {})}
          />
        )}
      </div>
    </div>
  );
}
