import { useState, useCallback, useRef, useEffect, useMemo } from 'react';
import { toPng, toSvg } from 'html-to-image';
import { MonitorUp, Network as NetworkIcon, Grid3x3, Share2, Image as ImageIcon, ImagePlus, FileType, Wand2, KeyRound, List, Map, Maximize, Undo2, Redo2, Type, Layers, Plus, Trash2, Pencil, MousePointer2 } from 'lucide-react';
import {
  ReactFlow,
  ReactFlowProvider,
  Controls,
  MiniMap,
  Background,
  BackgroundVariant,
  addEdge,
  applyNodeChanges,
  applyEdgeChanges,
  reconnectEdge,
  useReactFlow,
  type Node,
  type Edge,
  type Connection as RFConnection,
  type OnNodesChange,
  type OnEdgesChange,
  type OnConnect,
  type NodeChange,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { fetchDiagram, updatePositions, removeDeviceFromDiagram, removeSubnetFromDiagram, autoGenerateDiagram, updateNodePrefs, updateLegendItems, createAnnotation, updateAnnotation, deleteAnnotation, createView, deleteView, updateView } from '../../api/diagram';
import { deviceIconOverrideUrl, typeDefaultIconUrl, uploadDeviceIconOverride, deleteDeviceIconOverride, createDiagramImage, updateDiagramImage, deleteDiagramImage, diagramImageUrl } from '../../api/diagramIcons';
import { fetchDevices } from '../../api/devices';
import { fetchSubnets } from '../../api/subnets';
import { createConnection, updateConnection, deleteConnection } from '../../api/connections';
import { useConfirmDialog } from '../ui/ConfirmDialog';
import { useToast } from '../ui/Toast';
import { useProject } from '../../contexts/ProjectContext';
import DeviceNode from './nodes/DeviceNode';
import SubnetGroupNode from './nodes/SubnetGroupNode';
import AnnotationNode from './nodes/AnnotationNode';
import ImageNode from './nodes/ImageNode';
import PropertiesPanel, { type SelectedElement } from './PropertiesPanel';
import DiagramLegend from './DiagramLegend';
import ContextMenu from './ContextMenu';
import { useUndoRedo } from './useUndoRedo';
import type { DiagramData, DiagramAnnotation, DiagramImage as DiagramImageType, DiagramView, NodePrefs, LegendItem } from 'shared/types';

type AllNodePrefs = Record<string, NodePrefs>;

const nodeTypes = {
  server: DeviceNode,
  workstation: DeviceNode,
  router: DeviceNode,
  switch: DeviceNode,
  nas: DeviceNode,
  firewall: DeviceNode,
  access_point: DeviceNode,
  iot: DeviceNode,
  camera: DeviceNode,
  phone: DeviceNode,
  subnetGroup: SubnetGroupNode,
  annotation: AnnotationNode,
  diagramImage: ImageNode,
};

function toDiagramNodes(
  data: DiagramData, prefs: AllNodePrefs, hideHandles: boolean, showCredentials: boolean, projectId: number,
  annotationCallbacks?: { onTextChange: (id: number, text: string) => void; onDelete: (id: number) => void },
  imageCallbacks?: { onDelete: (id: number) => void },
): Node[] {
  const iconOverrideSet = new Set(data.device_icon_overrides || []);
  const typeDefaultSet = new Set(data.type_default_icons || []);

  const subnetNodes: Node[] = data.subnets.map(s => {
    const p = prefs[`subnet-${s.id}`] || {};
    return {
      id: `subnet-${s.id}`,
      type: 'subnetGroup',
      position: { x: s.x, y: s.y },
      style: { width: s.width, height: s.height },
      data: {
        label: s.name,
        cidr: s.cidr,
        vlanId: s.vlan_id,
        description: s.description,
        borderColor: p.borderColor || null,
        bgColor: p.bgColor || null,
        labelColor: p.labelColor || null,
        favourite: p.favourite || false,
        borderStyle: p.borderStyle || null,
        borderRadius: p.borderRadius || null,
        borderWidth: p.borderWidth || null,
      },
    };
  });

  const deviceNodes: Node[] = data.devices.map(d => {
    const p = prefs[`device-${d.id}`] || {};
    return {
      id: `device-${d.id}`,
      type: d.type,
      position: { x: d.x, y: d.y },
      data: {
        label: d.name,
        ip: d.primary_ip || '',
        deviceType: d.type,
        os: d.os,
        hostingType: d.hosting_type,
        deviceId: d.id,
        macAddress: d.mac_address,
        location: d.location,
        notes: d.notes,
        ips: d.ips,
        borderColor: p.borderColor || null,
        bgColor: p.bgColor || null,
        labelColor: p.labelColor || null,
        customIcon: p.icon || null,
        iconOverrideUrl: iconOverrideSet.has(d.id) ? deviceIconOverrideUrl(projectId, d.id) : null,
        typeDefaultIconUrl: typeDefaultSet.has(d.type) ? typeDefaultIconUrl(projectId, d.type) : null,
        favourite: p.favourite || false,
        hideHandles,
        hasCredentials: d.has_credentials,
        showCredentials,
        status: d.status,
      },
      ...(d.subnet_id ? { parentId: `subnet-${d.subnet_id}`, extent: 'parent' as const } : {}),
    };
  });

  const annotationNodes: Node[] = (data.annotations || []).map(a => ({
    id: `annotation-${a.id}`,
    type: 'annotation',
    position: { x: a.x, y: a.y },
    data: {
      text: a.text,
      fontSize: a.font_size,
      color: a.color,
      onTextChange: (text: string) => annotationCallbacks?.onTextChange(a.id, text),
      onDelete: () => annotationCallbacks?.onDelete(a.id),
    },
    dragHandle: '.annotation-node',
  }));

  const imageNodes: Node[] = (data.diagram_images || []).map(img => ({
    id: `image-${img.id}`,
    type: 'diagramImage',
    position: { x: img.x, y: img.y },
    data: {
      imageUrl: diagramImageUrl(projectId, img.id),
      width: img.width,
      height: img.height,
      label: img.label,
      onDelete: () => imageCallbacks?.onDelete(img.id),
    },
    dragHandle: '.image-node',
  }));

  return [...subnetNodes, ...deviceNodes, ...annotationNodes, ...imageNodes];
}

const EDGE_BASE_WIDTHS: Record<string, number> = {
  solid: 2, dashed: 2, dotted: 2, thick: 4, animated: 2,
};
const EDGE_DASH_PATTERNS: Record<string, string | undefined> = {
  dashed: '8 4', dotted: '2 4', animated: '8 4',
};

function toDiagramEdges(data: DiagramData): Edge[] {
  const connectionEdges: Edge[] = data.connections.map(c => {
    const isSubnetConn = !!(c.source_subnet_id || c.target_subnet_id);
    const stroke = c.edge_color || (isSubnetConn ? '#8b5cf6' : '#64748b');
    const baseWidth = isSubnetConn ? 3 : (EDGE_BASE_WIDTHS[c.connection_type || 'solid'] ?? 2);
    const strokeWidth = c.edge_width ?? baseWidth;
    const strokeDasharray = EDGE_DASH_PATTERNS[c.connection_type || 'solid'];
    const style: React.CSSProperties = { stroke, strokeWidth, ...(strokeDasharray ? { strokeDasharray } : {}) };

    const labelStyle = c.label_color ? { fill: c.label_color } : undefined;
    const labelBgStyle = c.label_bg_color ? { fill: c.label_bg_color } : { fill: 'transparent' };

    // Resolve source/target node IDs (device or subnet)
    const source = c.source_device_id ? `device-${c.source_device_id}` : `subnet-${c.source_subnet_id}`;
    const target = c.target_device_id ? `device-${c.target_device_id}` : `subnet-${c.target_subnet_id}`;

    return {
      id: `edge-${c.id}`,
      source,
      target,
      sourceHandle: c.source_handle || null,
      targetHandle: c.target_handle || null,
      label: (() => {
        const parts: string[] = [];
        if (c.source_port || c.target_port) {
          parts.push([c.source_port, c.target_port].filter(Boolean).join(' → '));
        }
        if (c.label) parts.push(c.label);
        return parts.length > 0 ? parts.join(' | ') : undefined;
      })(),
      type: c.edge_type || 'default',
      animated: c.connection_type === 'animated',
      style,
      labelStyle,
      labelBgStyle,
      labelBgPadding: [6, 3] as [number, number],
      labelBgBorderRadius: 4,
      markerEnd: { type: 'arrowclosed' as any, width: 12, height: 12 },
    };
  });
  // Skip membership edges for devices already contained inside their subnet (via parentId)
  const containedPairs = new Set(
    data.devices.filter(d => d.subnet_id != null).map(d => `${d.id}-${d.subnet_id}`)
  );
  const membershipEdges: Edge[] = data.subnet_memberships
    .filter(m => !containedPairs.has(`${m.device_id}-${m.subnet_id}`))
    .map(m => ({
      id: `membership-${m.device_id}-${m.subnet_id}`,
      source: `device-${m.device_id}`,
      target: `subnet-${m.subnet_id}`,
      type: 'straight',
      style: { strokeDasharray: '5 5', stroke: '#94a3b8', strokeWidth: 1.5 },
      selectable: false,
      deletable: false,
    }));
  return [...connectionEdges, ...membershipEdges];
}

type ContextMenuState =
  | { x: number; y: number; kind: 'node'; nodeId: string; nodeType: 'device' | 'subnet' | 'annotation' | 'image' }
  | { x: number; y: number; kind: 'edge'; edgeId: string };

function NetworkDiagramInner() {
  const { projectId, project } = useProject();
  const base = `/p/${project.slug}`;
  const confirm = useConfirmDialog();
  const toast = useToast();
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const reactFlowInstance = useReactFlow();
  const [nodes, setNodes] = useState<Node[]>([]);
  const [edges, setEdges] = useState<Edge[]>([]);
  const [addDeviceId, setAddDeviceId] = useState('');
  const [addSubnetId, setAddSubnetId] = useState('');
  const [selectedElement, setSelectedElement] = useState<SelectedElement | null>(null);
  const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null);
  const [nodePrefs, setNodePrefs] = useState<AllNodePrefs>({});
  const [showGrid, setShowGrid] = useState(() => localStorage.getItem(`diagram-show-grid-${project.slug}`) !== 'false');
  const [showEdges, setShowEdges] = useState(() => localStorage.getItem(`diagram-show-edges-${project.slug}`) !== 'false');
  const [showCredentials, setShowCredentials] = useState(() => localStorage.getItem(`diagram-show-credentials-${project.slug}`) !== 'false');
  const [showLegend, setShowLegend] = useState(() => localStorage.getItem(`diagram-show-legend-${project.slug}`) !== 'false');
  const [showMinimap, setShowMinimap] = useState(() => localStorage.getItem(`diagram-show-minimap-${project.slug}`) === 'true');
  const [selectMode, setSelectMode] = useState(() => localStorage.getItem(`diagram-select-mode-${project.slug}`) === 'true');
  const [searchQuery, setSearchQuery] = useState('');
  const [currentViewId, setCurrentViewId] = useState<number | undefined>(undefined);
  const [addDeviceOpen, setAddDeviceOpen] = useState(false);
  const [addSubnetOpen, setAddSubnetOpen] = useState(false);
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingPositionsRef = useRef<{ devices: { id: number; x: number; y: number }[]; subnets: { id: number; x: number; y: number; width: number; height: number }[] } | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const nodePrefsRef = useRef<AllNodePrefs>({});
  const annotationCallbacksRef = useRef<{ onTextChange: (id: number, text: string) => void; onDelete: (id: number) => void } | undefined>(undefined);
  const showEdgesRef = useRef(showEdges);
  const showCredentialsRef = useRef(showCredentials);
  const viewIdRef = useRef<number | undefined>(currentViewId);
  const edgeReconnectSuccessful = useRef(true);
  const { takeSnapshot, undo, redo, pushRedo, canUndo, canRedo } = useUndoRedo();
  const [savedViewport] = useState(() => {
    try {
      const v = localStorage.getItem(`diagram-viewport-${project.slug}`);
      return v ? JSON.parse(v) : null;
    } catch { return null; }
  });

  const onMoveEnd = useCallback((_event: any, viewport: { x: number; y: number; zoom: number }) => {
    localStorage.setItem(`diagram-viewport-${project.slug}`, JSON.stringify(viewport));
  }, [project.slug]);

  // Reset state when project changes
  useEffect(() => {
    setShowGrid(localStorage.getItem(`diagram-show-grid-${project.slug}`) !== 'false');
    setShowEdges(localStorage.getItem(`diagram-show-edges-${project.slug}`) !== 'false');
    setShowCredentials(localStorage.getItem(`diagram-show-credentials-${project.slug}`) !== 'false');
    setShowLegend(localStorage.getItem(`diagram-show-legend-${project.slug}`) !== 'false');
    setShowMinimap(localStorage.getItem(`diagram-show-minimap-${project.slug}`) === 'true');
    setSelectedElement(null);
    setContextMenu(null);
    setSearchQuery('');
  }, [project.slug]);

  const { data: diagramData } = useQuery({ queryKey: ['diagram', projectId, currentViewId], queryFn: () => fetchDiagram(projectId, currentViewId), refetchOnMount: 'always' });
  const { data: allDevices } = useQuery({ queryKey: ['devices', projectId], queryFn: () => fetchDevices(projectId) });
  const { data: allSubnets } = useQuery({ queryKey: ['subnets', projectId], queryFn: () => fetchSubnets(projectId) });

  // Load node preferences from server when diagram data arrives
  useEffect(() => {
    if (diagramData?.node_preferences) {
      setNodePrefs(diagramData.node_preferences);
    }
  }, [diagramData]);

  // Keep refs in sync so effects below can read latest values without depending on them
  useEffect(() => { nodePrefsRef.current = nodePrefs; }, [nodePrefs]);
  useEffect(() => { showEdgesRef.current = showEdges; }, [showEdges]);
  useEffect(() => { showCredentialsRef.current = showCredentials; }, [showCredentials]);
  useEffect(() => { viewIdRef.current = currentViewId; }, [currentViewId]);

  // Rebuild nodes from DB data when diagram loads.
  // Intentionally does NOT include nodePrefs, showEdges, or showCredentials — those changes
  // are handled by separate effects below to avoid resetting React Flow positions.
  useEffect(() => {
    if (diagramData) {
      setNodes(toDiagramNodes(diagramData, nodePrefsRef.current, !showEdgesRef.current, showCredentialsRef.current, projectId, annotationCallbacksRef.current, imageCallbacksRef.current));
      setEdges(toDiagramEdges(diagramData));
    }
  }, [diagramData]); // eslint-disable-line react-hooks/exhaustive-deps

  // Patch hideHandles when showEdges toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, hideHandles: !showEdges } };
    }));
  }, [showEdges]);

  // Patch showCredentials when it toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, showCredentials } };
    }));
  }, [showCredentials]);

  // When nodePrefs change (colour, favourite, icon), patch only node data fields.
  // Using the functional updater preserves React Flow's internal node positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      const p = nodePrefs[n.id] || {};
      if (n.id.startsWith('subnet-')) {
        return {
          ...n,
          data: {
            ...n.data,
            borderColor: p.borderColor || null,
            bgColor: p.bgColor || null,
            labelColor: p.labelColor || null,
            favourite: p.favourite || false,
            borderStyle: p.borderStyle || null,
            borderRadius: p.borderRadius || null,
            borderWidth: p.borderWidth || null,
          },
        };
      }
      return {
        ...n,
        data: {
          ...n.data,
          borderColor: p.borderColor || null,
          bgColor: p.bgColor || null,
          labelColor: p.labelColor || null,
          favourite: p.favourite || false,
          customIcon: p.icon || null,
        },
      };
    }));
  }, [nodePrefs]);

  const flushPositions = useCallback(() => {
    if (saveTimer.current) {
      clearTimeout(saveTimer.current);
      saveTimer.current = null;
    }
    const pending = pendingPositionsRef.current;
    if (!pending) return;
    pendingPositionsRef.current = null;
    updatePositions(projectId, pending, viewIdRef.current).catch(() => {});
  }, [projectId]);

  const savePositions = useCallback((updatedNodes: Node[]) => {
    const devices = updatedNodes
      .filter(n => n.id.startsWith('device-'))
      .map(n => ({ id: parseInt(n.id.replace('device-', '')), x: n.position.x, y: n.position.y }));
    const subnets = updatedNodes
      .filter(n => n.id.startsWith('subnet-'))
      .map(n => ({
        id: parseInt(n.id.replace('subnet-', '')),
        x: n.position.x, y: n.position.y,
        width: (n.style?.width as number) || 400,
        height: (n.style?.height as number) || 300,
      }));
    // Save annotation positions
    const annotations = updatedNodes
      .filter(n => n.id.startsWith('annotation-'))
      .map(n => ({ id: parseInt(n.id.replace('annotation-', '')), x: n.position.x, y: n.position.y }));
    for (const a of annotations) {
      updateAnnotation(projectId, a.id, { x: a.x, y: a.y }).catch(() => {});
    }
    // Save diagram image positions
    const images = updatedNodes
      .filter(n => n.id.startsWith('image-'))
      .map(n => ({ id: parseInt(n.id.replace('image-', '')), x: n.position.x, y: n.position.y }));
    for (const img of images) {
      updateDiagramImage(projectId, img.id, { x: img.x, y: img.y }).catch(() => {});
    }
    pendingPositionsRef.current = { devices, subnets };
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => flushPositions(), 500);
  }, [flushPositions, projectId]);

  // Flush pending position saves on unmount
  useEffect(() => {
    return () => flushPositions();
  }, [flushPositions]);

  // Flush pending position saves on tab close
  useEffect(() => {
    const handler = () => flushPositions();
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [flushPositions]);

  const onNodesChange: OnNodesChange = useCallback((changes: NodeChange[]) => {
    setNodes(nds => {
      const hasDragStart = changes.some(c => c.type === 'position' && 'dragging' in c && c.dragging);
      if (hasDragStart) takeSnapshot(nds, edges);
      const updated = applyNodeChanges(changes, nds);
      const hasDragEnd = changes.some(c => c.type === 'position' && !('dragging' in c && c.dragging));
      const hasResizeEnd = changes.some(c => c.type === 'dimensions' && !('resizing' in c && c.resizing));
      if (hasDragEnd || hasResizeEnd) savePositions(updated);
      return updated;
    });
  }, [savePositions, takeSnapshot, edges]);

  const onEdgesChange: OnEdgesChange = useCallback((changes) => {
    setEdges(eds => applyEdgeChanges(changes, eds));
  }, []);

  const onConnect: OnConnect = useCallback(async (connection) => {
    if (!connection.source || !connection.target) return;
    const isSourceSubnet = connection.source.startsWith('subnet-');
    const isTargetSubnet = connection.target.startsWith('subnet-');
    const sourceDeviceId = !isSourceSubnet ? parseInt(connection.source.replace('device-', '')) : undefined;
    const targetDeviceId = !isTargetSubnet ? parseInt(connection.target.replace('device-', '')) : undefined;
    const sourceSubnetId = isSourceSubnet ? parseInt(connection.source.replace('subnet-', '')) : undefined;
    const targetSubnetId = isTargetSubnet ? parseInt(connection.target.replace('subnet-', '')) : undefined;
    try {
      const newConn = await createConnection(projectId, {
        source_device_id: sourceDeviceId as number,
        target_device_id: targetDeviceId as number,
        source_handle: connection.sourceHandle ?? undefined,
        target_handle: connection.targetHandle ?? undefined,
        source_subnet_id: sourceSubnetId,
        target_subnet_id: targetSubnetId,
      } as any);
      setEdges(eds => addEdge({ ...connection, id: `edge-${newConn.id}` }, eds));
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
    } catch {
      toast('Failed to create connection', 'error');
    }
  }, [projectId, queryClient, currentViewId]);

  const handleAddDevice = async () => {
    if (!addDeviceId) return;
    try {
      const center = reactFlowInstance.screenToFlowPosition({
        x: window.innerWidth / 2, y: window.innerHeight / 2,
      });
      await updatePositions(projectId, { devices: [{ id: parseInt(addDeviceId), x: center.x, y: center.y }] }, viewIdRef.current);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setAddDeviceId('');
    } catch { toast('Failed to add device to diagram', 'error'); }
  };

  const handleAddSubnet = async () => {
    if (!addSubnetId) return;
    try {
      const center = reactFlowInstance.screenToFlowPosition({
        x: window.innerWidth / 2, y: window.innerHeight / 2,
      });
      await updatePositions(projectId, { subnets: [{ id: parseInt(addSubnetId), x: center.x - 200, y: center.y - 150, width: 400, height: 300 }] }, viewIdRef.current);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setAddSubnetId('');
    } catch { toast('Failed to add subnet to diagram', 'error'); }
  };

  const handleDeleteEdge = useCallback(async (edgeId: string) => {
    if (edgeId.startsWith('membership-')) return;
    try {
      const connId = parseInt(edgeId.replace('edge-', ''));
      await deleteConnection(projectId, connId);
      setEdges(eds => eds.filter(e => e.id !== edgeId));
    } catch { toast('Failed to delete connection', 'error'); }
  }, [projectId, toast]);

  const onReconnectStart = useCallback(() => {
    edgeReconnectSuccessful.current = false;
  }, []);

  const onReconnect = useCallback((oldEdge: Edge, newConnection: RFConnection) => {
    edgeReconnectSuccessful.current = true;
    setEdges(eds => reconnectEdge(oldEdge, newConnection, eds));
    const connId = parseInt(oldEdge.id.replace('edge-', ''));
    updateConnection(projectId, connId, {
      source_handle: newConnection.sourceHandle ?? null,
      target_handle: newConnection.targetHandle ?? null,
    });
  }, [projectId]);

  const onReconnectEnd = useCallback(() => {
    edgeReconnectSuccessful.current = true;
  }, []);

  const onNodeClick = useCallback((_e: React.MouseEvent, node: Node) => {
    if (node.id.startsWith('device-')) {
      setSelectedElement({ type: 'device', id: node.id, data: node.data });
    } else if (node.id.startsWith('subnet-')) {
      setSelectedElement({ type: 'subnet', id: node.id, data: node.data });
    }
  }, []);

  const onEdgeClick = useCallback((_e: React.MouseEvent, edge: Edge) => {
    if (!diagramData) return;
    const conn = diagramData.connections.find(c => `edge-${c.id}` === edge.id);
    const sourceDevice = diagramData.devices.find(d => d.id === conn?.source_device_id);
    const targetDevice = diagramData.devices.find(d => d.id === conn?.target_device_id);
    const sourceSubnet = diagramData.subnets.find(s => s.id === conn?.source_subnet_id);
    const targetSubnet = diagramData.subnets.find(s => s.id === conn?.target_subnet_id);
    setSelectedElement({
      type: 'edge',
      id: edge.id,
      data: {
        connId: conn?.id,
        label: conn?.label,
        connectionType: conn?.connection_type,
        edgeType: conn?.edge_type || 'default',
        edgeColor: conn?.edge_color,
        edgeWidth: conn?.edge_width,
        labelColor: conn?.label_color,
        labelBgColor: conn?.label_bg_color,
        createdAt: conn?.created_at,
        sourceName: sourceDevice?.name || sourceSubnet?.name || 'Unknown',
        targetName: targetDevice?.name || targetSubnet?.name || 'Unknown',
        sourceDeviceId: conn?.source_device_id,
        targetDeviceId: conn?.target_device_id,
        sourcePort: conn?.source_port,
        targetPort: conn?.target_port,
      },
    });
  }, [diagramData]);

  const onPaneClick = useCallback(() => {
    setSelectedElement(null);
    setContextMenu(null);
  }, []);

  const handleUndo = useCallback(() => {
    const snapshot = undo();
    if (!snapshot) return;
    pushRedo(nodes, edges);
    setNodes(snapshot.nodes);
    setEdges(snapshot.edges);
    savePositions(snapshot.nodes);
  }, [undo, pushRedo, nodes, edges, savePositions]);

  const handleRedo = useCallback(() => {
    const snapshot = redo();
    if (!snapshot) return;
    takeSnapshot(nodes, edges);
    setNodes(snapshot.nodes);
    setEdges(snapshot.edges);
    savePositions(snapshot.nodes);
  }, [redo, takeSnapshot, nodes, edges, savePositions]);

  useEffect(() => {
    const handleKeyDown = async (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement).tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;
      // Undo/Redo
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) {
        e.preventDefault();
        handleUndo();
        return;
      }
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Z' || (e.key === 'z' && e.shiftKey))) {
        e.preventDefault();
        handleRedo();
        return;
      }
      // Delete edge
      if (e.key !== 'Delete' && e.key !== 'Backspace') return;
      if (selectedElement?.type === 'edge') {
        if (await confirm('Delete this connection?')) handleDeleteEdge(selectedElement.id);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedElement, handleDeleteEdge, confirm, handleUndo, handleRedo]);

  const onNodeContextMenu = useCallback((e: React.MouseEvent, node: Node) => {
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    const nodeType = node.id.startsWith('device-') ? 'device' as const : node.id.startsWith('annotation-') ? 'annotation' as const : node.id.startsWith('image-') ? 'image' as const : 'subnet' as const;
    setContextMenu({ x, y, kind: 'node', nodeId: node.id, nodeType });
  }, []);

  const onEdgeContextMenu = useCallback((e: React.MouseEvent, edge: Edge) => {
    if (edge.id.startsWith('membership-')) return;
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    setContextMenu({ x, y, kind: 'edge', edgeId: edge.id });
  }, []);

  const handleRemoveFromDiagram = useCallback(async (nodeId: string, nodeType: 'device' | 'subnet') => {
    const numId = parseInt(nodeId.replace(/^(device|subnet)-/, ''));
    if (!await confirm('Remove this from the diagram?')) return;
    try {
      if (nodeType === 'device') {
        await removeDeviceFromDiagram(projectId, numId, viewIdRef.current);
      } else {
        await removeSubnetFromDiagram(projectId, numId, viewIdRef.current);
      }
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
    } catch { toast('Failed to remove from diagram', 'error'); }
  }, [projectId, queryClient, currentViewId, confirm, toast]);

  const handleConnectionUpdate = useCallback(async (connId: number, data: { label?: string | null; connection_type?: string; edge_type?: string; edge_color?: string | null; edge_width?: number | null; label_color?: string | null; label_bg_color?: string | null; source_port?: string | null; target_port?: string | null }) => {
    try {
      const updated = await updateConnection(projectId, connId, data);
      // Update edge locally instead of full refetch
      setEdges(eds => eds.map(e => {
        if (e.id !== `edge-${connId}`) return e;
        const ct = updated.connection_type || 'solid';
        const stroke = updated.edge_color || '#64748b';
        const strokeWidth = updated.edge_width ?? EDGE_BASE_WIDTHS[ct] ?? 2;
        const strokeDasharray = EDGE_DASH_PATTERNS[ct];
        const labelParts: string[] = [];
        if (updated.source_port || updated.target_port) {
          labelParts.push([updated.source_port, updated.target_port].filter(Boolean).join(' → '));
        }
        if (updated.label) labelParts.push(updated.label);
        return {
          ...e,
          label: labelParts.length > 0 ? labelParts.join(' | ') : undefined,
          type: updated.edge_type || 'default',
          animated: ct === 'animated',
          style: { stroke, strokeWidth, ...(strokeDasharray ? { strokeDasharray } : {}) },
          labelStyle: updated.label_color ? { fill: updated.label_color } : undefined,
          labelBgStyle: updated.label_bg_color ? { fill: updated.label_bg_color } : { fill: 'transparent' },
        };
      }));
      // Update query cache so PropertiesPanel stays in sync
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, connections: old.connections.map(c => c.id === connId ? { ...c, ...data } : c) };
      });
    } catch { toast('Failed to update connection', 'error'); }
  }, [projectId, queryClient, toast]);

  const handleExportPng = useCallback(async () => {
    try {
      const container = containerRef.current;
      if (!container) return;
      const dataUrl = await toPng(container, {
        backgroundColor: 'var(--color-surface)',
        pixelRatio: 2,
        filter: (node: Element) => !node.classList?.contains('react-flow__controls'),
      });
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = 'network-diagram.png';
      a.click();
    } catch { toast('Failed to export PNG', 'error'); }
  }, [toast]);

  const handleAutoLayoutGrid = useCallback(async () => {
    if (!await confirm('This will clear the current diagram (including annotations and images) and auto-place all devices and subnets in a grid. Continue?')) return;
    try {
      await autoGenerateDiagram(projectId, viewIdRef.current);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
    } catch { toast('Failed to auto-layout diagram', 'error'); }
  }, [projectId, queryClient, currentViewId, confirm, toast]);

  const handleExportSvg = useCallback(async () => {
    try {
      const container = containerRef.current;
      if (!container) return;
      const svgData = await toSvg(container, {
        filter: (node: Element) => !node.classList?.contains('react-flow__controls'),
      });
      const a = document.createElement('a');
      a.href = svgData;
      a.download = 'network-diagram.svg';
      a.click();
    } catch { toast('Failed to export SVG', 'error'); }
  }, [toast]);

  // Annotation handlers
  const handleAnnotationTextChange = useCallback(async (id: number, text: string) => {
    try {
      await updateAnnotation(projectId, id, { text });
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, annotations: old.annotations.map(a => a.id === id ? { ...a, text } : a) };
      });
    } catch { toast('Failed to update annotation', 'error'); }
  }, [projectId, queryClient, toast]);

  const handleAnnotationDelete = useCallback(async (id: number) => {
    try {
      await deleteAnnotation(projectId, id);
      setNodes(nds => nds.filter(n => n.id !== `annotation-${id}`));
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, annotations: old.annotations.filter(a => a.id !== id) };
      });
    } catch { toast('Failed to delete annotation', 'error'); }
  }, [projectId, queryClient, toast]);

  const handleAddAnnotation = useCallback(async () => {
    try {
      const center = reactFlowInstance.screenToFlowPosition({
        x: window.innerWidth / 2, y: window.innerHeight / 2,
      });
      await createAnnotation(projectId, { x: center.x, y: center.y, view_id: viewIdRef.current });
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
    } catch { toast('Failed to add annotation', 'error'); }
  }, [projectId, queryClient, currentViewId, reactFlowInstance, toast]);

  const annotationCallbacks = useMemo(() => ({
    onTextChange: handleAnnotationTextChange,
    onDelete: handleAnnotationDelete,
  }), [handleAnnotationTextChange, handleAnnotationDelete]);
  useEffect(() => { annotationCallbacksRef.current = annotationCallbacks; }, [annotationCallbacks]);

  // Image handlers
  const imageFileInputRef = useRef<HTMLInputElement>(null);
  const iconFileInputRef = useRef<HTMLInputElement>(null);
  const iconTargetDeviceRef = useRef<number | null>(null);

  const handleImageDelete = useCallback(async (id: number) => {
    try {
      await deleteDiagramImage(projectId, id);
      setNodes(nds => nds.filter(n => n.id !== `image-${id}`));
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, diagram_images: old.diagram_images.filter(img => img.id !== id) };
      });
    } catch (err) { toast(err instanceof Error ? err.message : 'Failed to delete image', 'error'); }
  }, [projectId, queryClient, toast, currentViewId]);

  const handleAddImage = useCallback(() => {
    imageFileInputRef.current?.click();
  }, []);

  const handleImageFileSelected = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    e.target.value = '';
    const reader = new FileReader();
    reader.onload = async () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      try {
        const center = reactFlowInstance.screenToFlowPosition({
          x: window.innerWidth / 2, y: window.innerHeight / 2,
        });
        await createDiagramImage(projectId, {
          x: center.x, y: center.y,
          filename: file.name, mime_type: file.type, data: base64,
          view_id: viewIdRef.current,
        });
        queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      } catch (err) { toast(err instanceof Error ? err.message : 'Failed to add image', 'error'); }
    };
    reader.readAsDataURL(file);
  }, [projectId, queryClient, currentViewId, reactFlowInstance, toast]);

  const handleIconFileSelected = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    const deviceId = iconTargetDeviceRef.current;
    if (!file || !deviceId) return;
    e.target.value = '';
    const reader = new FileReader();
    reader.onload = async () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      try {
        await uploadDeviceIconOverride(projectId, deviceId, {
          filename: file.name, mime_type: file.type, data: base64,
        });
        queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      } catch (err) { toast(err instanceof Error ? err.message : 'Failed to set custom icon', 'error'); }
    };
    reader.readAsDataURL(file);
  }, [projectId, queryClient, currentViewId, toast]);

  const imageCallbacks = useMemo(() => ({
    onDelete: handleImageDelete,
  }), [handleImageDelete]);
  const imageCallbacksRef = useRef(imageCallbacks);
  useEffect(() => { imageCallbacksRef.current = imageCallbacks; }, [imageCallbacks]);

  // Multi-select
  // View management
  const [viewMenuOpen, setViewMenuOpen] = useState(false);
  const views = diagramData?.views || [];

  const handleCreateView = useCallback(async () => {
    const name = prompt('New view name:');
    if (!name?.trim()) return;
    try {
      const newView = await createView(projectId, name.trim());
      setCurrentViewId(newView.id);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch { toast('Failed to create view', 'error'); }
  }, [projectId, queryClient, toast]);

  const handleDeleteView = useCallback(async (viewId: number) => {
    if (!await confirm('Delete this view? All positions in this view will be lost.')) return;
    try {
      await deleteView(projectId, viewId);
      setCurrentViewId(undefined);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch { toast('Failed to delete view', 'error'); }
  }, [projectId, queryClient, confirm, toast]);

  const handleRenameView = useCallback(async (viewId: number, currentName: string) => {
    const name = prompt('Rename view:', currentName);
    if (!name?.trim() || name.trim() === currentName) return;
    try {
      await updateView(projectId, viewId, name.trim());
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch { toast('Failed to rename view', 'error'); }
  }, [projectId, queryClient, toast]);

  const [selectedNodeIds, setSelectedNodeIds] = useState<string[]>([]);
  const onSelectionChange = useCallback(({ nodes: sel }: { nodes: Node[] }) => {
    setSelectedNodeIds(sel.map(n => n.id));
  }, []);

  const handleBulkRemove = useCallback(async () => {
    if (!await confirm(`Remove ${selectedNodeIds.length} items from the diagram?`)) return;
    try {
      for (const nodeId of selectedNodeIds) {
        const numId = parseInt(nodeId.replace(/^(device|subnet)-/, ''));
        if (nodeId.startsWith('device-')) {
          await removeDeviceFromDiagram(projectId, numId, viewIdRef.current);
        } else if (nodeId.startsWith('subnet-')) {
          await removeSubnetFromDiagram(projectId, numId, viewIdRef.current);
        }
      }
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setSelectedNodeIds([]);
    } catch { toast('Failed to remove items', 'error'); }
  }, [selectedNodeIds, projectId, queryClient, currentViewId, confirm, toast]);

  const displayNodes = useMemo(() => {
    if (!searchQuery.trim()) return nodes;
    const q = searchQuery.toLowerCase();
    return nodes.map(n => ({
      ...n,
      style: {
        ...n.style,
        opacity: (String(n.data?.label ?? '').toLowerCase().includes(q) || String(n.data?.ip ?? '').includes(q)) ? 1 : 0.1,
      },
    }));
  }, [nodes, searchQuery]);

  // UX 10: Zoom to search results
  useEffect(() => {
    if (!searchQuery.trim()) return;
    const q = searchQuery.toLowerCase();
    const matchedIds = nodes
      .filter(n => String(n.data?.label ?? '').toLowerCase().includes(q) || String(n.data?.ip ?? '').includes(q))
      .map(n => ({ id: n.id }));
    if (matchedIds.length === 0) return;
    const timer = setTimeout(() => {
      reactFlowInstance.fitView({ nodes: matchedIds, padding: 0.5, duration: 300 });
    }, 300);
    return () => clearTimeout(timer);
  }, [searchQuery]); // eslint-disable-line react-hooks/exhaustive-deps

  const handlePrefChange = useCallback((nodeId: string, key: keyof NodePrefs, value: any) => {
    setNodePrefs(prev => {
      const existing = prev[nodeId] || {};
      let next: AllNodePrefs;
      if (value === null || value === undefined || value === false) {
        const updated = { ...existing };
        delete updated[key];
        next = Object.keys(updated).length > 0
          ? { ...prev, [nodeId]: updated }
          : { ...prev };
        if (!Object.keys(updated).length) delete next[nodeId];
      } else {
        next = { ...prev, [nodeId]: { ...existing, [key]: value } };
      }
      const updatedPrefs = next[nodeId] || {};
      updateNodePrefs(projectId, nodeId, updatedPrefs);
      // Targeted single-node update instead of waiting for the full useEffect pass
      const dataKey = key === 'icon' ? 'customIcon' : key;
      reactFlowInstance.updateNodeData(nodeId, { [dataKey]: value || null });
      return next;
    });
  }, [projectId, reactFlowInstance]);

  const handleLegendUpdate = useCallback(async (items: LegendItem[]) => {
    await updateLegendItems(projectId, items);
    queryClient.setQueryData(['diagram', projectId], (old: DiagramData | undefined) =>
      old ? { ...old, legend_items: items } : old
    );
  }, [projectId, queryClient]);

  const getContextMenuItems = useCallback(() => {
    if (!contextMenu) return [];
    const items: { label: string; onClick: () => void; danger?: boolean }[] = [];

    if (contextMenu.kind === 'edge') {
      items.push({
        label: 'Delete Connection',
        onClick: async () => { if (await confirm('Delete this connection?')) handleDeleteEdge(contextMenu.edgeId); },
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'annotation') {
      const annotationId = parseInt(contextMenu.nodeId.replace('annotation-', ''));
      items.push({
        label: 'Delete Text',
        onClick: () => handleAnnotationDelete(annotationId),
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'image') {
      const imageId = parseInt(contextMenu.nodeId.replace('image-', ''));
      items.push({
        label: 'Delete Image',
        onClick: () => handleImageDelete(imageId),
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'device') {
      const deviceId = parseInt(contextMenu.nodeId.replace('device-', ''));
      items.push({ label: 'Open Device Page', onClick: () => navigate(`${base}/devices/${deviceId}`) });
      items.push({
        label: 'Set Custom Icon',
        onClick: () => { iconTargetDeviceRef.current = deviceId; iconFileInputRef.current?.click(); },
      });
      const hasOverride = diagramData?.device_icon_overrides?.includes(deviceId);
      if (hasOverride) {
        items.push({
          label: 'Reset Icon',
          onClick: async () => {
            try {
              await deleteDeviceIconOverride(projectId, deviceId);
              queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
            } catch (err) { toast(err instanceof Error ? err.message : 'Failed to reset icon', 'error'); }
          },
        });
      }
    }

    items.push({
      label: 'Remove from Diagram',
      onClick: () => handleRemoveFromDiagram(contextMenu.nodeId, contextMenu.nodeType as 'device' | 'subnet'),
      danger: true,
    });

    return items;
  }, [contextMenu, base, navigate, handleRemoveFromDiagram, handleAnnotationDelete, handleImageDelete, handleDeleteEdge, confirm, diagramData, projectId, queryClient, currentViewId, toast]);

  // Devices not yet on diagram
  const diagramDeviceIds = new Set(diagramData?.devices.map(d => d.id) || []);
  const unplacedDevices = allDevices?.filter(d => !diagramDeviceIds.has(d.id)) || [];

  const diagramSubnetIds = new Set(diagramData?.subnets.map(s => s.id) || []);
  const unplacedSubnets = allSubnets?.filter(s => !diagramSubnetIds.has(s.id)) || [];

  const selectedPrefs = selectedElement ? nodePrefs[selectedElement.id] || {} : {};

  return (
    <div className="diagram-page">
      <div className="page-header">
        <h2>Network Diagram</h2>
      </div>

      <div className="diagram-toolbar">
        {/* Group: Views */}
        {views.length > 0 && (
          <div className="diagram-tb-group">
            <div style={{ position: 'relative' }}>
              <button
                className={`diagram-tb-btn${viewMenuOpen ? ' active' : ''}`}
                data-tooltip="Views"
                onClick={() => setViewMenuOpen(v => !v)}
              >
                <Layers size={17} />
              </button>
              {viewMenuOpen && (
                <div className="diagram-tb-popover" style={{ minWidth: 200 }}>
                  {views.map(v => (
                    <div key={v.id} style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', padding: '0.15rem 0' }}>
                      <button
                        className={`btn btn-sm${(currentViewId ?? diagramData?.current_view_id) === v.id ? ' btn-primary' : ' btn-secondary'}`}
                        style={{ flex: 1, textAlign: 'left', justifyContent: 'flex-start', whiteSpace: 'nowrap' }}
                        onClick={() => { setCurrentViewId(v.id); setViewMenuOpen(false); }}
                      >
                        {v.name}{v.is_default ? ' (default)' : ''}
                      </button>
                      {!v.is_default && (
                        <>
                          <button className="btn btn-sm" title="Rename" onClick={() => handleRenameView(v.id, v.name)}>
                            <Pencil size={13} />
                          </button>
                          <button className="btn btn-sm btn-danger" title="Delete" onClick={() => handleDeleteView(v.id)}>
                            <Trash2 size={13} />
                          </button>
                        </>
                      )}
                    </div>
                  ))}
                  <button className="btn btn-sm btn-secondary" style={{ width: '100%', marginTop: '0.3rem', whiteSpace: 'nowrap' }} onClick={handleCreateView}>
                    <Plus size={13} /> New View
                  </button>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Group: Add to Diagram */}
        <div className="diagram-tb-group">
          <div style={{ position: 'relative' }}>
            <button
              className={`diagram-tb-btn${addDeviceOpen ? ' active' : ''}`}
              data-tooltip="Add Device"
              onClick={() => { setAddDeviceOpen(v => !v); setAddSubnetOpen(false); }}
            >
              <MonitorUp size={17} />
            </button>
            {addDeviceOpen && (
              <div className="diagram-tb-popover">
                <select value={addDeviceId} onChange={e => setAddDeviceId(e.target.value)}>
                  <option value="">Select device...</option>
                  {unplacedDevices.map(d => <option key={d.id} value={d.id}>{d.name} ({d.type})</option>)}
                </select>
                <button className="btn btn-primary btn-sm" disabled={!addDeviceId} onClick={() => { handleAddDevice(); setAddDeviceOpen(false); }}>
                  Add
                </button>
              </div>
            )}
          </div>
          <div style={{ position: 'relative' }}>
            <button
              className={`diagram-tb-btn${addSubnetOpen ? ' active' : ''}`}
              data-tooltip="Add Subnet"
              onClick={() => { setAddSubnetOpen(v => !v); setAddDeviceOpen(false); }}
            >
              <NetworkIcon size={17} />
            </button>
            {addSubnetOpen && (
              <div className="diagram-tb-popover">
                <select value={addSubnetId} onChange={e => setAddSubnetId(e.target.value)}>
                  <option value="">Select subnet...</option>
                  {unplacedSubnets.map(s => <option key={s.id} value={s.id}>{s.name} ({s.cidr})</option>)}
                </select>
                <button className="btn btn-primary btn-sm" disabled={!addSubnetId} onClick={() => { handleAddSubnet(); setAddSubnetOpen(false); }}>
                  Add
                </button>
              </div>
            )}
          </div>
          <button className="diagram-tb-btn" data-tooltip="Add Text" onClick={handleAddAnnotation}>
            <Type size={17} />
          </button>
          <button className="diagram-tb-btn" data-tooltip="Add Image" onClick={handleAddImage}>
            <ImagePlus size={17} />
          </button>
        </div>

        {/* Group: Interaction Mode */}
        <div className="diagram-tb-group">
          <button
            className={`diagram-tb-btn${selectMode ? ' active' : ''}`}
            data-tooltip={selectMode ? 'Selection Mode (click for Pan)' : 'Pan Mode (click for Select)'}
            onClick={() => setSelectMode(v => { const next = !v; localStorage.setItem(`diagram-select-mode-${project.slug}`, String(next)); return next; })}
          >
            <MousePointer2 size={17} />
          </button>
        </div>

        {/* Group: Display Toggles */}
        <div className="diagram-tb-group">
          <button
            className={`diagram-tb-btn${showGrid ? ' active' : ''}`}
            data-tooltip="Toggle Grid"
            onClick={() => setShowGrid(v => { localStorage.setItem(`diagram-show-grid-${project.slug}`, String(!v)); return !v; })}
          >
            <Grid3x3 size={17} />
          </button>
          <button
            className={`diagram-tb-btn${showEdges ? ' active' : ''}`}
            data-tooltip="Toggle Connections"
            onClick={() => setShowEdges(v => { localStorage.setItem(`diagram-show-edges-${project.slug}`, String(!v)); return !v; })}
          >
            <Share2 size={17} />
          </button>
          <button
            className={`diagram-tb-btn${showCredentials ? ' active' : ''}`}
            data-tooltip="Toggle Credentials"
            onClick={() => setShowCredentials(v => { localStorage.setItem(`diagram-show-credentials-${project.slug}`, String(!v)); return !v; })}
          >
            <KeyRound size={17} />
          </button>
          <button
            className={`diagram-tb-btn${showLegend ? ' active' : ''}`}
            data-tooltip="Toggle Legend"
            onClick={() => setShowLegend(v => { localStorage.setItem(`diagram-show-legend-${project.slug}`, String(!v)); return !v; })}
          >
            <List size={17} />
          </button>
          <button
            className={`diagram-tb-btn${showMinimap ? ' active' : ''}`}
            data-tooltip="Toggle Minimap"
            onClick={() => setShowMinimap(v => { localStorage.setItem(`diagram-show-minimap-${project.slug}`, String(!v)); return !v; })}
          >
            <Map size={17} />
          </button>
        </div>

        {/* Group: Layout & View */}
        <div className="diagram-tb-group">
          <button className="diagram-tb-btn" data-tooltip="Auto Layout" onClick={handleAutoLayoutGrid}>
            <Wand2 size={17} />
          </button>
          <button
            className="diagram-tb-btn"
            data-tooltip="Fit to View"
            onClick={() => reactFlowInstance.fitView({ duration: 300 })}
          >
            <Maximize size={17} />
          </button>
        </div>

        {/* Group: Export */}
        <div className="diagram-tb-group">
          <button className="diagram-tb-btn" data-tooltip="Export PNG" onClick={handleExportPng}>
            <ImageIcon size={17} />
          </button>
          <button className="diagram-tb-btn" data-tooltip="Export SVG" onClick={handleExportSvg}>
            <FileType size={17} />
          </button>
        </div>

        {/* Group: Undo/Redo */}
        <div className="diagram-tb-group">
          <button
            className="diagram-tb-btn"
            data-tooltip="Undo (Ctrl+Z)"
            onClick={handleUndo}
            disabled={!canUndo()}
          >
            <Undo2 size={17} />
          </button>
          <button
            className="diagram-tb-btn"
            data-tooltip="Redo (Ctrl+Shift+Z)"
            onClick={handleRedo}
            disabled={!canRedo()}
          >
            <Redo2 size={17} />
          </button>
        </div>

        {/* Search */}
        <input
          type="text"
          className="diagram-search"
          placeholder="Search devices..."
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          style={{ marginLeft: 'auto' }}
        />
      </div>

      <div className="diagram-layout">
        <div className="diagram-container" ref={containerRef} style={{ position: 'relative' }}>
          <ReactFlow
            nodes={displayNodes}
            edges={showEdges ? edges : []}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            onNodeClick={onNodeClick}
            onEdgeClick={onEdgeClick}
            onPaneClick={onPaneClick}
            onNodeContextMenu={onNodeContextMenu}
            onEdgeContextMenu={onEdgeContextMenu}
            onReconnectStart={onReconnectStart}
            onReconnect={onReconnect}
            onReconnectEnd={onReconnectEnd}
            onSelectionChange={onSelectionChange}

            onMoveEnd={onMoveEnd}
            nodeTypes={nodeTypes}
            deleteKeyCode={null}
            proOptions={{ hideAttribution: true }}
            fitView={!savedViewport}
            defaultViewport={savedViewport || undefined}
            snapToGrid
            snapGrid={[15, 15]}
            selectionOnDrag={selectMode}
            panOnDrag={selectMode ? [1] : [0, 1]}
          >
            <Controls />
            {showMinimap && <MiniMap pannable zoomable />}
            {showGrid && <Background variant={BackgroundVariant.Dots} gap={15} size={1} />}
          </ReactFlow>
          {showLegend && (
            <DiagramLegend items={diagramData?.legend_items ?? []} onUpdate={handleLegendUpdate} />
          )}
          {contextMenu && (
            <ContextMenu
              position={{ x: contextMenu.x, y: contextMenu.y }}
              items={getContextMenuItems()}
              onClose={() => setContextMenu(null)}
              {... (contextMenu.kind === 'node' ? {
                onColourChange: (colour: string | null) => handlePrefChange(contextMenu.nodeId, 'borderColor', colour),
                currentColour: nodePrefs[contextMenu.nodeId]?.borderColor || null,
              } : {})}
            />
          )}
          {selectedNodeIds.length > 1 && (
            <div className="diagram-bulk-bar">
              <span>{selectedNodeIds.length} selected</span>
              <button className="btn btn-sm btn-danger" onClick={handleBulkRemove}>Remove from Diagram</button>
            </div>
          )}
        </div>
        {selectedElement && (
          <PropertiesPanel
            selected={selectedElement}
            onClose={() => setSelectedElement(null)}
            nodePrefs={selectedPrefs}
            onPrefChange={(key: keyof NodePrefs, value: any) => handlePrefChange(selectedElement.id, key, value)}
            onConnectionUpdate={handleConnectionUpdate}
            projectBase={base}
          />
        )}
      </div>
      <input ref={imageFileInputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={handleImageFileSelected} />
      <input ref={iconFileInputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={handleIconFileSelected} />
    </div>
  );
}

export default function NetworkDiagram() {
  return (
    <ReactFlowProvider>
      <NetworkDiagramInner />
    </ReactFlowProvider>
  );
}
