import { useState, useCallback, useRef, useEffect, useLayoutEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { toPng, toSvg } from 'html-to-image';
import { Trash2, Lock } from 'lucide-react';
import {
  ReactFlow,
  ReactFlowProvider,
  Controls,
  MiniMap,
  Background,
  BackgroundVariant,
  addEdge,
  applyNodeChanges,
  applyEdgeChanges,
  reconnectEdge,
  useReactFlow,
  useStoreApi,
  type Node,
  type Edge,
  type Connection as RFConnection,
  type OnNodesChange,
  type OnEdgesChange,
  type OnConnect,
  type NodeChange,
  MarkerType,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { fetchDiagram, updatePositions, removeDeviceFromDiagram, removeSubnetFromDiagram, autoGenerateDiagram, updateNodePrefs, updateLegendItems, createAnnotation, updateAnnotation, deleteAnnotation, createView, deleteView, updateView, exportDiagram, importDiagram } from '../../api/diagram';
import { deviceIconOverrideUrl, typeDefaultIconUrl, agentTypeDefaultIconUrl, uploadDeviceIconOverride, deleteDeviceIconOverride, createDiagramImage, deleteDiagramImage, diagramImageUrl } from '../../api/diagramIcons';
import { DEFAULT_AGENT_ICONS } from '../../assets/agent-icons';
import { fetchDevices } from '../../api/devices';
import { fetchSubnets } from '../../api/subnets';
import { createConnection, updateConnection, deleteConnection } from '../../api/connections';
import { useConfirmDialog } from '../ui/ConfirmDialog';
import { useInputDialog } from '../ui/InputDialog';
import { useToast } from '../ui/Toast';
import { useProject } from '../../contexts/ProjectContext';
import DeviceNode from './nodes/DeviceNode';
import SubnetGroupNode from './nodes/SubnetGroupNode';
import AnnotationNode from './nodes/AnnotationNode';
import ImageNode from './nodes/ImageNode';
import PropertiesPanel, { type SelectedElement } from './PropertiesPanel';
import DiagramLegend from './DiagramLegend';
import ContextMenu from './ContextMenu';
import ImageLibraryModal from './ImageLibraryModal';
import ErrorBoundary from '../ui/ErrorBoundary';
import { useUndoRedo } from './useUndoRedo';
import { useDiagramPositionSave } from './useDiagramPositionSave';
import DiagramToolbar from './DiagramToolbar';
import type { DiagramData, NodePrefs, LegendItem } from 'shared/types';
import { getStorage, setStorage, removeStorage } from '../../utils/storage';

type AllNodePrefs = Record<string, NodePrefs>;

const nodeTypes = {
  server: DeviceNode,
  workstation: DeviceNode,
  router: DeviceNode,
  switch: DeviceNode,
  nas: DeviceNode,
  firewall: DeviceNode,
  access_point: DeviceNode,
  iot: DeviceNode,
  camera: DeviceNode,
  phone: DeviceNode,
  subnetGroup: SubnetGroupNode,
  annotation: AnnotationNode,
  diagramImage: ImageNode,
};

function toDiagramNodes(
  data: DiagramData, prefs: AllNodePrefs, hideHandles: boolean, showCredentials: boolean, showAv: boolean, showAgents: boolean, projectId: number,
  annotationCallbacks?: { onTextChange: (id: number, text: string) => void; onDelete: (id: number) => void },
  imageCallbacks?: { onDelete: (id: number) => void },
): Node[] {
  const iconOverrideSet = new Set(data.device_icon_overrides || []);
  const typeDefaultSet = new Set(data.type_default_icons || []);
  const agentTypeDefaultSet = new Set(data.agent_type_default_icons || []);

  const subnetNodes: Node[] = data.subnets.map(s => {
    const p = prefs[`subnet-${s.id}`] || {};
    return {
      id: `subnet-${s.id}`,
      type: 'subnetGroup',
      position: { x: s.x, y: s.y },
      style: { width: s.width, height: s.height },
      data: {
        label: s.name,
        subnetId: s.id,
        cidr: s.cidr,
        vlanId: s.vlan_id,
        description: s.description,
        borderColor: p.borderColor || null,
        bgColor: p.bgColor || null,
        labelColor: p.labelColor || null,
        favourite: p.favourite || false,
        borderStyle: p.borderStyle || null,
        borderRadius: p.borderRadius || null,
        borderWidth: p.borderWidth || null,
      },
    };
  });

  const deviceNodes: Node[] = data.devices.map(d => {
    const p = prefs[`device-${d.id}`] || {};
    return {
      id: `device-${d.id}`,
      type: d.type,
      position: { x: d.x, y: d.y },
      data: {
        label: d.name,
        ip: d.primary_ip || '',
        deviceType: d.type,
        os: d.os,
        hostingType: d.hosting_type,
        deviceId: d.id,
        macAddress: d.mac_address,
        location: d.location,
        notes: d.notes,
        ips: d.ips,
        borderColor: p.borderColor || null,
        bgColor: p.bgColor || null,
        labelColor: p.labelColor || null,
        customIcon: p.icon || null,
        iconOverrideUrl: iconOverrideSet.has(d.id) ? deviceIconOverrideUrl(projectId, d.id) : null,
        typeDefaultIconUrl: (d.hosting_type === 'hypervisor' && typeDefaultSet.has('hypervisor'))
          ? typeDefaultIconUrl(projectId, 'hypervisor')
          : typeDefaultSet.has(d.type) ? typeDefaultIconUrl(projectId, d.type) : null,
        favourite: p.favourite || false,
        hideHandles,
        hasCredentials: d.has_credentials,
        anyCredentialUsed: d.any_credential_used,
        showCredentials,
        status: d.status,
        av: d.av,
        showAv,
        agents: (d.agents || []).map(a => ({
          id: a.id,
          name: a.name,
          agentType: a.agent_type,
          iconUrl: agentTypeDefaultSet.has(a.agent_type)
            ? agentTypeDefaultIconUrl(projectId, a.agent_type)
            : (DEFAULT_AGENT_ICONS[a.agent_type] || DEFAULT_AGENT_ICONS.custom),
        })),
        showAgents,
      },
      ...(d.subnet_id ? { parentId: `subnet-${d.subnet_id}`, extent: 'parent' as const } : {}),
    };
  });

  const annotationNodes: Node[] = (data.annotations || []).map(a => ({
    id: `annotation-${a.id}`,
    type: 'annotation',
    position: { x: a.x, y: a.y },
    data: {
      text: a.text,
      fontSize: a.font_size,
      color: a.color,
      onTextChange: (text: string) => annotationCallbacks?.onTextChange(a.id, text),
      onDelete: () => annotationCallbacks?.onDelete(a.id),
    },
    dragHandle: '.annotation-node',
  }));

  const imageNodes: Node[] = (data.diagram_images || []).map(img => ({
    id: `image-${img.id}`,
    type: 'diagramImage',
    position: { x: img.x, y: img.y },
    style: { width: img.width, height: img.height },
    data: {
      imageUrl: diagramImageUrl(projectId, img.id),
      label: img.label,
      onDelete: () => imageCallbacks?.onDelete(img.id),
    },
    dragHandle: '.image-node',
  }));

  return [...subnetNodes, ...deviceNodes, ...annotationNodes, ...imageNodes];
}

const EDGE_BASE_WIDTHS: Record<string, number> = {
  solid: 2, dashed: 2, dotted: 2, thick: 4, animated: 2,
};
const EDGE_DASH_PATTERNS: Record<string, string | undefined> = {
  dashed: '8 4', dotted: '2 4', animated: '8 4',
};

function toDiagramEdges(data: DiagramData): Edge[] {
  const connectionEdges: Edge[] = data.connections.map(c => {
    const isSubnetConn = !!(c.source_subnet_id || c.target_subnet_id);
    const stroke = c.edge_color || (isSubnetConn ? '#8b5cf6' : '#64748b');
    const baseWidth = isSubnetConn ? 3 : (EDGE_BASE_WIDTHS[c.connection_type || 'solid'] ?? 2);
    const strokeWidth = c.edge_width ?? baseWidth;
    const strokeDasharray = EDGE_DASH_PATTERNS[c.connection_type || 'solid'];
    const style: React.CSSProperties = { stroke, strokeWidth, ...(strokeDasharray ? { strokeDasharray } : {}) };

    const labelStyle = c.label_color ? { fill: c.label_color } : undefined;
    const labelBgStyle = c.label_bg_color ? { fill: c.label_bg_color } : { fill: 'transparent' };

    // Resolve source/target node IDs (device or subnet)
    const source = c.source_device_id ? `device-${c.source_device_id}` : `subnet-${c.source_subnet_id}`;
    const target = c.target_device_id ? `device-${c.target_device_id}` : `subnet-${c.target_subnet_id}`;

    return {
      id: `edge-${c.id}`,
      source,
      target,
      sourceHandle: c.source_handle || null,
      targetHandle: c.target_handle || null,
      label: (() => {
        const parts: string[] = [];
        if (c.source_port || c.target_port) {
          parts.push([c.source_port, c.target_port].filter(Boolean).join(' → '));
        }
        if (c.label) parts.push(c.label);
        return parts.length > 0 ? parts.join(' | ') : undefined;
      })(),
      type: c.edge_type || 'default',
      animated: c.connection_type === 'animated',
      style,
      labelStyle,
      labelBgStyle,
      labelBgPadding: [6, 3] as [number, number],
      labelBgBorderRadius: 4,
      markerEnd: { type: MarkerType.ArrowClosed, width: 12, height: 12 },
    };
  });
  // Skip membership edges for devices already contained inside their subnet (via parentId)
  const containedPairs = new Set(
    data.devices.filter(d => d.subnet_id != null).map(d => `${d.id}-${d.subnet_id}`)
  );
  const membershipEdges: Edge[] = data.subnet_memberships
    .filter(m => !containedPairs.has(`${m.device_id}-${m.subnet_id}`))
    .map(m => ({
      id: `membership-${m.device_id}-${m.subnet_id}`,
      source: `device-${m.device_id}`,
      target: `subnet-${m.subnet_id}`,
      type: 'straight',
      style: { strokeDasharray: '5 5', stroke: '#94a3b8', strokeWidth: 1.5 },
      selectable: false,
      deletable: false,
    }));
  return [...connectionEdges, ...membershipEdges];
}

type ContextMenuState =
  | { x: number; y: number; kind: 'node'; nodeId: string; nodeType: 'device' | 'subnet' | 'annotation' | 'image' }
  | { x: number; y: number; kind: 'edge'; edgeId: string }
  | { x: number; y: number; kind: 'selection' };


function NetworkDiagramInner() {
  const { projectId, project } = useProject();
  const base = `/p/${project.slug}`;
  const confirm = useConfirmDialog();
  const inputDialog = useInputDialog();
  const toast = useToast();
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const reactFlowInstance = useReactFlow();
  const storeApi = useStoreApi();
  const [nodes, setNodes] = useState<Node[]>([]);
  const [edges, setEdges] = useState<Edge[]>([]);
  const [addDeviceId, setAddDeviceId] = useState('');
  const [addSubnetId, setAddSubnetId] = useState('');
  const [selectedElement, setSelectedElement] = useState<SelectedElement | null>(null);
  const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null);
  const [nodePrefs, setNodePrefs] = useState<AllNodePrefs>({});
  const [showGrid, setShowGrid] = useState(() => getStorage(`diagram-show-grid-${project.slug}`) !== 'false');
  const [showEdges, setShowEdges] = useState(() => getStorage(`diagram-show-edges-${project.slug}`) !== 'false');
  const [showCredentials, setShowCredentials] = useState(() => getStorage(`diagram-show-credentials-${project.slug}`) !== 'false');
  const [showAv, setShowAv] = useState(() => getStorage(`diagram-show-av-${project.slug}`) !== 'false');
  const [showAgents, setShowAgents] = useState(() => getStorage(`diagram-show-agents-${project.slug}`) !== 'false');
  const [showLegend, setShowLegend] = useState(() => getStorage(`diagram-show-legend-${project.slug}`) !== 'false');
  const [showMinimap, setShowMinimap] = useState(() => getStorage(`diagram-show-minimap-${project.slug}`) === 'true');
  const [selectMode, setSelectMode] = useState(() => getStorage(`diagram-select-mode-${project.slug}`) === 'true');
  const [locked, setLocked] = useState(true);
  const [showLockHint, setShowLockHint] = useState(() => getStorage('diagram-lock-hint-seen') !== 'true');

  // Set initial lock state directly in the React Flow store before the browser
  // paints. NetworkDiagramInner is a parent of <ReactFlow>, so its
  // useLayoutEffect fires after all of React Flow's internal effects but before
  // the first paint — giving us the final say on the store values.
  useLayoutEffect(() => {
    storeApi.setState({ nodesDraggable: !locked, nodesConnectable: !locked, elementsSelectable: !locked });
  }, [locked, storeApi]);

  useEffect(() => {
    if (locked) {
      setAddDeviceOpen(false);
      setAddSubnetOpen(false);
      setPlacingAnnotation(false);
    } else if (showLockHint) {
      // Auto-dismiss hint the first time the user unlocks
      setShowLockHint(false);
      setStorage('diagram-lock-hint-seen', 'true');
    }
  }, [locked]); // eslint-disable-line react-hooks/exhaustive-deps

  const dismissLockHint = useCallback(() => {
    setShowLockHint(false);
    setStorage('diagram-lock-hint-seen', 'true');
  }, []);

  const [searchQuery, setSearchQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState<string[]>(() => {
    const raw = getStorage(`diagram-type-filter-${project.slug}`);
    if (!raw) return [];
    try { return JSON.parse(raw) as string[]; } catch { return []; }
  });
  const [typeFilterMenuOpen, setTypeFilterMenuOpen] = useState(false);
  const toggleTypeFilter = useCallback((t: string) => {
    setTypeFilter(prev => {
      const next = prev.includes(t) ? prev.filter(x => x !== t) : [...prev, t];
      setStorage(`diagram-type-filter-${project.slug}`, JSON.stringify(next));
      return next;
    });
  }, [project.slug]);
  const clearTypeFilter = useCallback(() => {
    setTypeFilter([]);
    setStorage(`diagram-type-filter-${project.slug}`, '[]');
  }, [project.slug]);
  const [currentViewId, setCurrentViewIdState] = useState<number | undefined>(() => {
    const stored = getStorage(`diagram-view-${project.slug}`);
    return stored ? Number(stored) : undefined;
  });
  const setCurrentViewId = useCallback((id: number | undefined) => {
    setCurrentViewIdState(id);
    if (id === undefined) {
      removeStorage(`diagram-view-${project.slug}`);
    } else {
      setStorage(`diagram-view-${project.slug}`, String(id));
    }
  }, [project.slug]);
  const [addDeviceOpen, setAddDeviceOpen] = useState(false);
  const [imageLibraryOpen, setImageLibraryOpen] = useState(false);
  const [addSubnetOpen, setAddSubnetOpen] = useState(false);
  const [placingAnnotation, setPlacingAnnotation] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const suppressSaveRef = useRef(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const nodePrefsRef = useRef<AllNodePrefs>({});
  const annotationCallbacksRef = useRef<{ onTextChange: (id: number, text: string) => void; onDelete: (id: number) => void } | undefined>(undefined);
  const showEdgesRef = useRef(showEdges);
  const showCredentialsRef = useRef(showCredentials);
  const showAvRef = useRef(showAv);
  const showAgentsRef = useRef(showAgents);
  const edgeReconnectSuccessful = useRef(true);
  const viewIdRef = useRef<number | undefined>(currentViewId);
  useEffect(() => { viewIdRef.current = currentViewId; }, [currentViewId]);
  const { takeSnapshot, undo, redo, pushRedo, canUndo, canRedo } = useUndoRedo();
  // Snapshot helper: captures current nodes/edges from the store without needing them in deps
  const snapshot = useCallback(() => {
    const { nodes: n, edges: e } = storeApi.getState();
    takeSnapshot(n, e);
  }, [storeApi, takeSnapshot]);
  const { savePositions, cancelPending, saveStatus } = useDiagramPositionSave({ projectId, currentViewId });
  const [savedViewport] = useState(() => {
    try {
      const v = getStorage(`diagram-viewport-${project.slug}`);
      return v ? JSON.parse(v) : null;
    } catch { return null; }
  });

  const onMoveEnd = useCallback((_event: any, viewport: { x: number; y: number; zoom: number }) => {
    setStorage(`diagram-viewport-${project.slug}`, JSON.stringify(viewport));
  }, [project.slug]);

  // Reset state when project changes
  useEffect(() => {
    setShowGrid(getStorage(`diagram-show-grid-${project.slug}`) !== 'false');
    setShowEdges(getStorage(`diagram-show-edges-${project.slug}`) !== 'false');
    setShowCredentials(getStorage(`diagram-show-credentials-${project.slug}`) !== 'false');
    setShowAv(getStorage(`diagram-show-av-${project.slug}`) !== 'false');
    setShowAgents(getStorage(`diagram-show-agents-${project.slug}`) !== 'false');
    setShowLegend(getStorage(`diagram-show-legend-${project.slug}`) !== 'false');
    setShowMinimap(getStorage(`diagram-show-minimap-${project.slug}`) === 'true');
    setSelectedElement(null);
    setContextMenu(null);
    setSearchQuery('');
    const storedView = getStorage(`diagram-view-${project.slug}`);
    setCurrentViewIdState(storedView ? Number(storedView) : undefined);
  }, [project.slug]);

  const { data: diagramData } = useQuery({ queryKey: ['diagram', projectId, currentViewId], queryFn: () => fetchDiagram(projectId, currentViewId), refetchOnMount: 'always' });
  const { data: allDevices } = useQuery({ queryKey: ['devices', projectId], queryFn: () => fetchDevices(projectId) });
  const { data: allSubnets } = useQuery({ queryKey: ['subnets', projectId], queryFn: () => fetchSubnets(projectId) });

  // Load node preferences from server when diagram data arrives
  useEffect(() => {
    if (diagramData?.node_preferences) {
      setNodePrefs(diagramData.node_preferences);
    }
  }, [diagramData]);

  // If the locally stored view ID is not in this project's views (e.g. stale
  // from a deleted view or another project), sync to the server's resolved view.
  useEffect(() => {
    if (!diagramData?.views) return;
    if (currentViewId === undefined) return;
    const exists = diagramData.views.some(v => v.id === currentViewId);
    if (!exists) {
      setCurrentViewId(diagramData.current_view_id);
    }
  }, [diagramData, currentViewId, setCurrentViewId]);

  // Keep refs in sync so effects below can read latest values without depending on them
  useEffect(() => { nodePrefsRef.current = nodePrefs; }, [nodePrefs]);
  useEffect(() => { showEdgesRef.current = showEdges; }, [showEdges]);
  useEffect(() => { showCredentialsRef.current = showCredentials; }, [showCredentials]);
  useEffect(() => { showAvRef.current = showAv; }, [showAv]);
  useEffect(() => { showAgentsRef.current = showAgents; }, [showAgents]);

  // Rebuild nodes from DB data when diagram loads.
  // Intentionally does NOT include nodePrefs, showEdges, or showCredentials — those changes
  // are handled by separate effects below to avoid resetting React Flow positions.
  useEffect(() => {
    if (diagramData) {
      setNodes(toDiagramNodes(diagramData, nodePrefsRef.current, !showEdgesRef.current, showCredentialsRef.current, showAvRef.current, showAgentsRef.current, projectId, annotationCallbacksRef.current, imageCallbacksRef.current));
      setEdges(toDiagramEdges(diagramData));
      // Allow position saves again after fresh data has been applied
      suppressSaveRef.current = false;
    }
  }, [diagramData]); // eslint-disable-line react-hooks/exhaustive-deps

  // Patch hideHandles when showEdges toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, hideHandles: !showEdges } };
    }));
  }, [showEdges]);

  // Patch showCredentials when it toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, showCredentials } };
    }));
  }, [showCredentials]);

  // Patch showAv when it toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, showAv } };
    }));
  }, [showAv]);

  // Patch showAgents when it toggles — preserves React Flow positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      if (!n.id.startsWith('device-')) return n;
      return { ...n, data: { ...n.data, showAgents } };
    }));
  }, [showAgents]);

  // When nodePrefs change (colour, favourite, icon), patch only node data fields.
  // Using the functional updater preserves React Flow's internal node positions.
  useEffect(() => {
    setNodes(nds => nds.map(n => {
      const p = nodePrefs[n.id] || {};
      if (n.id.startsWith('subnet-')) {
        return {
          ...n,
          data: {
            ...n.data,
            borderColor: p.borderColor || null,
            bgColor: p.bgColor || null,
            labelColor: p.labelColor || null,
            favourite: p.favourite || false,
            borderStyle: p.borderStyle || null,
            borderRadius: p.borderRadius || null,
            borderWidth: p.borderWidth || null,
          },
        };
      }
      return {
        ...n,
        data: {
          ...n.data,
          borderColor: p.borderColor || null,
          bgColor: p.bgColor || null,
          labelColor: p.labelColor || null,
          favourite: p.favourite || false,
          customIcon: p.icon || null,
        },
      };
    }));
  }, [nodePrefs]);

  const onNodesChange: OnNodesChange = useCallback((changes: NodeChange[]) => {
    setNodes(nds => {
      const hasDragStart = changes.some(c => c.type === 'position' && 'dragging' in c && c.dragging);
      if (hasDragStart) takeSnapshot(nds, edges);
      const updated = applyNodeChanges(changes, nds);
      const hasDragEnd = changes.some(c => c.type === 'position' && !('dragging' in c && c.dragging));
      const hasResizeEnd = changes.some(c => c.type === 'dimensions' && 'resizing' in c && c.resizing === false);
      if ((hasDragEnd || hasResizeEnd) && !suppressSaveRef.current) savePositions(updated);
      return updated;
    });
  }, [savePositions, takeSnapshot, edges]);

  const onEdgesChange: OnEdgesChange = useCallback((changes) => {
    setEdges(eds => {
      const applied = applyEdgeChanges(changes, eds);
      // Boost stroke width on selected edges; restore on deselect
      const hasSelectChange = changes.some(c => c.type === 'select');
      if (!hasSelectChange) return applied;
      return applied.map(edge => {
        const baseWidth = (edge.data as any)?.__baseStrokeWidth ?? edge.style?.strokeWidth ?? 2;
        if (edge.selected) {
          return {
            ...edge,
            data: { ...(edge.data || {}), __baseStrokeWidth: baseWidth },
            style: { ...edge.style, strokeWidth: (baseWidth as number) + 2 },
          };
        }
        return { ...edge, style: { ...edge.style, strokeWidth: baseWidth } };
      });
    });
  }, []);

  const onConnect: OnConnect = useCallback(async (connection) => {
    if (!connection.source || !connection.target) return;
    snapshot();
    const isSourceSubnet = connection.source.startsWith('subnet-');
    const isTargetSubnet = connection.target.startsWith('subnet-');
    const sourceDeviceId = !isSourceSubnet ? parseInt(connection.source.replace('device-', '')) : undefined;
    const targetDeviceId = !isTargetSubnet ? parseInt(connection.target.replace('device-', '')) : undefined;
    const sourceSubnetId = isSourceSubnet ? parseInt(connection.source.replace('subnet-', '')) : undefined;
    const targetSubnetId = isTargetSubnet ? parseInt(connection.target.replace('subnet-', '')) : undefined;
    try {
      const newConn = await createConnection(projectId, {
        source_device_id: sourceDeviceId,
        target_device_id: targetDeviceId,
        source_handle: connection.sourceHandle ?? undefined,
        target_handle: connection.targetHandle ?? undefined,
        source_subnet_id: sourceSubnetId,
        target_subnet_id: targetSubnetId,
      });
      setEdges(eds => addEdge({ ...connection, id: `edge-${newConn.id}` }, eds));
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
    } catch {
      toast('Failed to create connection', 'error');
    }
  }, [projectId, queryClient, currentViewId, snapshot, toast]);

  const handleAddDevice = async () => {
    if (!addDeviceId) return;
    try {
      const center = reactFlowInstance.screenToFlowPosition({
        x: window.innerWidth / 2, y: window.innerHeight / 2,
      });
      await updatePositions(projectId, { devices: [{ id: parseInt(addDeviceId), x: center.x, y: center.y }] }, viewIdRef.current);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setAddDeviceId('');
    } catch { toast('Failed to add device to diagram', 'error'); }
  };

  const handleAddSubnet = async () => {
    if (!addSubnetId) return;
    try {
      const center = reactFlowInstance.screenToFlowPosition({
        x: window.innerWidth / 2, y: window.innerHeight / 2,
      });
      await updatePositions(projectId, { subnets: [{ id: parseInt(addSubnetId), x: center.x - 200, y: center.y - 150, width: 400, height: 300 }] }, viewIdRef.current);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setAddSubnetId('');
    } catch { toast('Failed to add subnet to diagram', 'error'); }
  };

  const handleDeleteEdge = useCallback(async (edgeId: string) => {
    if (edgeId.startsWith('membership-')) return;
    snapshot();
    try {
      const connId = parseInt(edgeId.replace('edge-', ''));
      await deleteConnection(projectId, connId);
      setEdges(eds => eds.filter(e => e.id !== edgeId));
    } catch { toast('Failed to delete connection', 'error'); }
  }, [projectId, toast, snapshot]);

  const onConnectStart = useCallback(() => setIsConnecting(true), []);
  const onConnectEnd = useCallback(() => setIsConnecting(false), []);

  const onReconnectStart = useCallback(() => {
    edgeReconnectSuccessful.current = false;
    setIsConnecting(true);
  }, []);

  const onReconnect = useCallback((oldEdge: Edge, newConnection: RFConnection) => {
    edgeReconnectSuccessful.current = true;
    setEdges(eds => reconnectEdge(oldEdge, newConnection, eds));
    const connId = parseInt(oldEdge.id.replace('edge-', ''));
    updateConnection(projectId, connId, {
      source_handle: newConnection.sourceHandle ?? null,
      target_handle: newConnection.targetHandle ?? null,
    });
  }, [projectId]);

  const onReconnectEnd = useCallback(() => {
    edgeReconnectSuccessful.current = true;
    setIsConnecting(false);
  }, []);

  const onNodeClick = useCallback((_e: React.MouseEvent, node: Node) => {
    if (node.id.startsWith('device-')) {
      setSelectedElement({ type: 'device', id: node.id, data: node.data });
    } else if (node.id.startsWith('subnet-')) {
      setSelectedElement({ type: 'subnet', id: node.id, data: node.data });
    }
  }, []);

  const onEdgeClick = useCallback((_e: React.MouseEvent, edge: Edge) => {
    if (!diagramData) return;
    const conn = diagramData.connections.find(c => `edge-${c.id}` === edge.id);
    const sourceDevice = diagramData.devices.find(d => d.id === conn?.source_device_id);
    const targetDevice = diagramData.devices.find(d => d.id === conn?.target_device_id);
    const sourceSubnet = diagramData.subnets.find(s => s.id === conn?.source_subnet_id);
    const targetSubnet = diagramData.subnets.find(s => s.id === conn?.target_subnet_id);
    setSelectedElement({
      type: 'edge',
      id: edge.id,
      data: {
        connId: conn?.id,
        label: conn?.label,
        connectionType: conn?.connection_type,
        edgeType: conn?.edge_type || 'default',
        edgeColor: conn?.edge_color,
        edgeWidth: conn?.edge_width,
        labelColor: conn?.label_color,
        labelBgColor: conn?.label_bg_color,
        createdAt: conn?.created_at,
        sourceName: sourceDevice?.name || sourceSubnet?.name || 'Unknown',
        targetName: targetDevice?.name || targetSubnet?.name || 'Unknown',
        sourceDeviceId: conn?.source_device_id,
        targetDeviceId: conn?.target_device_id,
        sourcePort: conn?.source_port,
        targetPort: conn?.target_port,
      },
    });
  }, [diagramData]);

  const onPaneClick = useCallback((event: React.MouseEvent) => {
    if (placingAnnotation) {
      const pos = reactFlowInstance.screenToFlowPosition({ x: event.clientX, y: event.clientY });
      createAnnotation(projectId, { x: pos.x, y: pos.y, view_id: viewIdRef.current })
        .then(() => queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] }))
        .catch(() => toast('Failed to add annotation', 'error'));
      setPlacingAnnotation(false);
      return;
    }
    setSelectedElement(null);
    setContextMenu(null);
  }, [placingAnnotation, reactFlowInstance, projectId, queryClient, currentViewId, toast]);

  const handleUndo = useCallback(() => {
    const snapshot = undo();
    if (!snapshot) return;
    pushRedo(nodes, edges);
    setNodes(snapshot.nodes);
    setEdges(snapshot.edges);
    savePositions(snapshot.nodes);
  }, [undo, pushRedo, nodes, edges, savePositions]);

  const handleRedo = useCallback(() => {
    const snapshot = redo();
    if (!snapshot) return;
    takeSnapshot(nodes, edges);
    setNodes(snapshot.nodes);
    setEdges(snapshot.edges);
    savePositions(snapshot.nodes);
  }, [redo, takeSnapshot, nodes, edges, savePositions]);

  const onNodeContextMenu = useCallback((e: React.MouseEvent, node: Node) => {
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    const nodeType = node.id.startsWith('device-') ? 'device' as const : node.id.startsWith('annotation-') ? 'annotation' as const : node.id.startsWith('image-') ? 'image' as const : 'subnet' as const;
    setContextMenu({ x, y, kind: 'node', nodeId: node.id, nodeType });
  }, []);

  const onEdgeContextMenu = useCallback((e: React.MouseEvent, edge: Edge) => {
    if (edge.id.startsWith('membership-')) return;
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    setContextMenu({ x, y, kind: 'edge', edgeId: edge.id });
  }, []);

  const onSelectionContextMenu = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    const containerRect = containerRef.current?.getBoundingClientRect();
    const x = e.clientX - (containerRect?.left || 0);
    const y = e.clientY - (containerRect?.top || 0);
    setContextMenu({ x, y, kind: 'selection' });
  }, []);

  const handleRemoveFromDiagram = useCallback(async (nodeId: string, nodeType: 'device' | 'subnet') => {
    const numId = parseInt(nodeId.replace(/^(device|subnet)-/, ''));
    if (!await confirm('Remove this from the diagram?')) return;
    try {
      if (nodeType === 'device') {
        await removeDeviceFromDiagram(projectId, numId, viewIdRef.current);
      } else {
        await removeSubnetFromDiagram(projectId, numId, viewIdRef.current);
      }
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
    } catch { toast('Failed to remove from diagram', 'error'); }
  }, [projectId, queryClient, currentViewId, confirm, toast]);

  const handleConnectionUpdate = useCallback(async (connId: number, data: { label?: string | null; connection_type?: string; edge_type?: string; edge_color?: string | null; edge_width?: number | null; label_color?: string | null; label_bg_color?: string | null; source_port?: string | null; target_port?: string | null }) => {
    try {
      const updated = await updateConnection(projectId, connId, data);
      // Update edge locally instead of full refetch
      setEdges(eds => eds.map(e => {
        if (e.id !== `edge-${connId}`) return e;
        const ct = updated.connection_type || 'solid';
        const stroke = updated.edge_color || '#64748b';
        const strokeWidth = updated.edge_width ?? EDGE_BASE_WIDTHS[ct] ?? 2;
        const strokeDasharray = EDGE_DASH_PATTERNS[ct];
        const labelParts: string[] = [];
        if (updated.source_port || updated.target_port) {
          labelParts.push([updated.source_port, updated.target_port].filter(Boolean).join(' → '));
        }
        if (updated.label) labelParts.push(updated.label);
        return {
          ...e,
          label: labelParts.length > 0 ? labelParts.join(' | ') : undefined,
          type: updated.edge_type || 'default',
          animated: ct === 'animated',
          style: { stroke, strokeWidth, ...(strokeDasharray ? { strokeDasharray } : {}) },
          labelStyle: updated.label_color ? { fill: updated.label_color } : undefined,
          labelBgStyle: updated.label_bg_color ? { fill: updated.label_bg_color } : { fill: 'transparent' },
        };
      }));
      // Update query cache so PropertiesPanel stays in sync
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, connections: old.connections.map(c => c.id === connId ? { ...c, ...data } : c) };
      });
    } catch { toast('Failed to update connection', 'error'); }
  }, [projectId, queryClient, toast, currentViewId]);

  const handleExportPng = useCallback(async () => {
    try {
      const container = containerRef.current;
      if (!container) return;
      const dataUrl = await toPng(container, {
        backgroundColor: 'var(--color-surface)',
        pixelRatio: 2,
        filter: (node: Element) => !node.classList?.contains('react-flow__controls'),
      });
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = 'network-diagram.png';
      a.click();
    } catch { toast('Failed to export PNG', 'error'); }
  }, [toast]);

  const handleAutoLayoutGrid = useCallback(async () => {
    // Check the project (not the current view) — auto-layout is expected to
    // populate empty views too, so we shouldn't block on the current view being empty.
    const hasContent = (allDevices && allDevices.length > 0) || (allSubnets && allSubnets.length > 0);
    if (!hasContent) { toast('No devices or subnets to lay out.', 'info'); return; }
    if (!await confirm('This will clear the current diagram (including annotations and images) and auto-place all devices and subnets in a grid. Continue?')) return;
    // Cancel any pending debounced position save and suppress saves until fresh data loads
    cancelPending();
    suppressSaveRef.current = true;
    try {
      await autoGenerateDiagram(projectId, viewIdRef.current);
      // Fetch fresh data directly and apply to both query cache and React state
      // (bypasses refetch + useEffect chain which can race with React Flow's internal state)
      const freshData = await fetchDiagram(projectId, viewIdRef.current);
      queryClient.setQueryData(['diagram', projectId, viewIdRef.current], freshData);
      setNodes(toDiagramNodes(freshData, nodePrefsRef.current, !showEdgesRef.current, showCredentialsRef.current, showAvRef.current, showAgentsRef.current, projectId, annotationCallbacksRef.current, imageCallbacksRef.current));
      setEdges(toDiagramEdges(freshData));
      suppressSaveRef.current = false;
    } catch {
      suppressSaveRef.current = false;
      toast('Failed to auto-layout diagram', 'error');
    }
  }, [allDevices, allSubnets, projectId, queryClient, confirm, toast]);

  const handleExportSvg = useCallback(async () => {
    try {
      const container = containerRef.current;
      if (!container) return;
      const svgData = await toSvg(container, {
        filter: (node: Element) => !node.classList?.contains('react-flow__controls'),
      });
      const a = document.createElement('a');
      a.href = svgData;
      a.download = 'network-diagram.svg';
      a.click();
    } catch { toast('Failed to export SVG', 'error'); }
  }, [toast]);

  const importFileRef = useRef<HTMLInputElement>(null);

  const handleExportDiagramJson = useCallback(async () => {
    try {
      await exportDiagram(projectId, currentViewId);
    } catch { toast('Failed to export diagram', 'error'); }
  }, [projectId, currentViewId, toast]);

  const handleImportDiagram = useCallback(async (file: File) => {
    try {
      const text = await file.text();
      const data = JSON.parse(text);
      const result = await importDiagram(projectId, data, currentViewId);
      const unmatched = [...result.unmatchedDevices, ...result.unmatchedSubnets];
      const msg = unmatched.length
        ? `Imported (${result.matchedDevices} devices, ${result.matchedSubnets} subnets). Unmatched: ${unmatched.join(', ')}`
        : `Imported ${result.matchedDevices} devices, ${result.matchedSubnets} subnets`;
      toast(msg, unmatched.length ? 'info' : 'success');
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch (err) {
      toast(err instanceof Error ? err.message : 'Failed to import diagram', 'error');
    }
  }, [projectId, currentViewId, queryClient, toast]);

  // Annotation handlers
  const handleAnnotationTextChange = useCallback(async (id: number, text: string) => {
    snapshot();
    try {
      await updateAnnotation(projectId, id, { text });
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, annotations: old.annotations.map(a => a.id === id ? { ...a, text } : a) };
      });
    } catch { toast('Failed to update annotation', 'error'); }
  }, [projectId, queryClient, toast, snapshot, currentViewId]);

  const handleAnnotationDelete = useCallback(async (id: number) => {
    snapshot();
    try {
      await deleteAnnotation(projectId, id);
      setNodes(nds => nds.filter(n => n.id !== `annotation-${id}`));
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, annotations: old.annotations.filter(a => a.id !== id) };
      });
    } catch { toast('Failed to delete annotation', 'error'); }
  }, [projectId, queryClient, toast, snapshot, currentViewId]);

  const handleAddAnnotation = useCallback(() => {
    setPlacingAnnotation(true);
  }, []);

  const annotationCallbacks = useMemo(() => ({
    onTextChange: handleAnnotationTextChange,
    onDelete: handleAnnotationDelete,
  }), [handleAnnotationTextChange, handleAnnotationDelete]);
  useEffect(() => { annotationCallbacksRef.current = annotationCallbacks; }, [annotationCallbacks]);

  // Image handlers
  const imageFileInputRef = useRef<HTMLInputElement>(null);
  const iconFileInputRef = useRef<HTMLInputElement>(null);
  const iconTargetDeviceRef = useRef<number | null>(null);

  const handleImageDelete = useCallback(async (id: number) => {
    try {
      await deleteDiagramImage(projectId, id);
      setNodes(nds => nds.filter(n => n.id !== `image-${id}`));
      queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) => {
        if (!old) return old;
        return { ...old, diagram_images: old.diagram_images.filter(img => img.id !== id) };
      });
    } catch (err) { toast(err instanceof Error ? err.message : 'Failed to delete image', 'error'); }
  }, [projectId, queryClient, toast, currentViewId]);

  const handleImageFileSelected = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    e.target.value = '';
    const reader = new FileReader();
    reader.onload = async () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      try {
        const center = reactFlowInstance.screenToFlowPosition({
          x: window.innerWidth / 2, y: window.innerHeight / 2,
        });
        await createDiagramImage(projectId, {
          x: center.x, y: center.y,
          filename: file.name, mime_type: file.type, data: base64,
          view_id: viewIdRef.current,
        });
        queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      } catch (err) { toast(err instanceof Error ? err.message : 'Failed to add image', 'error'); }
    };
    reader.readAsDataURL(file);
  }, [projectId, queryClient, currentViewId, reactFlowInstance, toast]);

  const handlePlaceLibraryImage = useCallback(async (payload: { filename: string; mime_type: string; data: string }) => {
    try {
      const center = reactFlowInstance.screenToFlowPosition({
        x: window.innerWidth / 2, y: window.innerHeight / 2,
      });
      await createDiagramImage(projectId, {
        x: center.x, y: center.y,
        filename: payload.filename, mime_type: payload.mime_type, data: payload.data,
        view_id: viewIdRef.current,
      });
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setImageLibraryOpen(false);
    } catch (err) { toast(err instanceof Error ? err.message : 'Failed to place image', 'error'); }
  }, [projectId, queryClient, currentViewId, reactFlowInstance, toast]);

  const handleIconFileSelected = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    const deviceId = iconTargetDeviceRef.current;
    if (!file || !deviceId) return;
    e.target.value = '';
    const reader = new FileReader();
    reader.onload = async () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      try {
        await uploadDeviceIconOverride(projectId, deviceId, {
          filename: file.name, mime_type: file.type, data: base64,
        });
        queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      } catch (err) { toast(err instanceof Error ? err.message : 'Failed to set custom icon', 'error'); }
    };
    reader.readAsDataURL(file);
  }, [projectId, queryClient, currentViewId, toast]);

  const imageCallbacks = useMemo(() => ({
    onDelete: handleImageDelete,
  }), [handleImageDelete]);
  const imageCallbacksRef = useRef(imageCallbacks);
  useEffect(() => { imageCallbacksRef.current = imageCallbacks; }, [imageCallbacks]);

  // Multi-select
  // View management
  const [viewMenuOpen, setViewMenuOpen] = useState(false);
  const [exportMenuOpen, setExportMenuOpen] = useState(false);
  const [editingView, setEditingView] = useState<{ id: number; name: string } | null>(null);
  const [editingViewName, setEditingViewName] = useState('');
  const views = diagramData?.views || [];

  const handleCreateView = useCallback(async () => {
    const name = await inputDialog('Enter a name for the new view', '', 'Create View');
    if (!name) return;
    try {
      const newView = await createView(projectId, name);
      // Invalidate & wait for a refetch so the new view appears in the
      // views list before switching to it. Then switch — which fires a
      // fresh query for the new (empty) view's key.
      await queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
      setCurrentViewId(newView.id);
    } catch { toast('Failed to create view', 'error'); }
  }, [projectId, queryClient, inputDialog, toast, setCurrentViewId]);

  const handleDeleteView = useCallback(async (viewId: number) => {
    if (!await confirm('Delete this view? All positions in this view will be lost.')) return;
    try {
      await deleteView(projectId, viewId);
      setCurrentViewId(undefined);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch { toast('Failed to delete view', 'error'); }
  }, [projectId, queryClient, confirm, toast, setCurrentViewId]);

  const handleRenameView = useCallback(async (viewId: number, _currentName: string, newName: string) => {
    try {
      await updateView(projectId, viewId, newName);
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId] });
    } catch { toast('Failed to rename view', 'error'); }
  }, [projectId, queryClient, toast]);

  const [selectedNodeIds, setSelectedNodeIds] = useState<string[]>([]);
  const onSelectionChange = useCallback(({ nodes: sel }: { nodes: Node[] }) => {
    setSelectedNodeIds(sel.map(n => n.id));
  }, []);

  const handleBulkRemove = useCallback(async () => {
    const count = selectedNodeIds.length;
    if (!await confirm(`Remove ${count} ${count === 1 ? 'item' : 'items'} from the diagram?`)) return;
    try {
      for (const nodeId of selectedNodeIds) {
        const numId = parseInt(nodeId.replace(/^(device|subnet)-/, ''));
        if (nodeId.startsWith('device-')) {
          await removeDeviceFromDiagram(projectId, numId, viewIdRef.current);
        } else if (nodeId.startsWith('subnet-')) {
          await removeSubnetFromDiagram(projectId, numId, viewIdRef.current);
        }
      }
      queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
      setSelectedNodeIds([]);
    } catch { toast('Failed to remove items', 'error'); }
  }, [selectedNodeIds, projectId, queryClient, currentViewId, confirm, toast]);

  // Keyboard shortcuts: Undo/Redo, Delete selected nodes/edges
  useEffect(() => {
    const handleKeyDown = async (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement).tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;
      // Cancel annotation placement
      if (e.key === 'Escape' && placingAnnotation) { setPlacingAnnotation(false); return; }
      // Undo/Redo
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) {
        e.preventDefault();
        handleUndo();
        return;
      }
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Z' || (e.key === 'z' && e.shiftKey))) {
        e.preventDefault();
        handleRedo();
        return;
      }
      // Delete selected items
      if (e.key !== 'Delete' && e.key !== 'Backspace') return;
      if (selectedNodeIds.length > 0) {
        handleBulkRemove();
      } else if (selectedElement?.type === 'edge') {
        if (await confirm('Delete this connection?')) handleDeleteEdge(selectedElement.id);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedElement, selectedNodeIds, placingAnnotation, handleDeleteEdge, handleBulkRemove, confirm, handleUndo, handleRedo]);

  const displayNodes = useMemo(() => {
    let result = nodes;
    const q = searchQuery.trim() ? searchQuery.toLowerCase() : '';
    const typeSet = typeFilter.length > 0 ? new Set(typeFilter) : null;
    if (q || typeSet) {
      result = result.map(n => {
        const matchesSearch = !q
          || String(n.data?.label ?? '').toLowerCase().includes(q)
          || String(n.data?.ip ?? '').includes(q);
        // Only apply the type filter to device nodes; subnets/annotations/images stay as-is.
        const isDeviceNode = typeof n.data?.deviceType === 'string';
        const matchesType = !typeSet || !isDeviceNode || typeSet.has(String(n.data.deviceType));
        return {
          ...n,
          style: {
            ...n.style,
            opacity: matchesSearch && matchesType ? 1 : 0.1,
          },
        };
      });
    }
    if (locked) {
      result = result.map(n => ({ ...n, draggable: false }));
    }
    return result;
  }, [nodes, searchQuery, typeFilter, locked]);

  // UX 10: Zoom to search results
  useEffect(() => {
    if (!searchQuery.trim()) return;
    const q = searchQuery.toLowerCase();
    const matchedIds = nodes
      .filter(n => String(n.data?.label ?? '').toLowerCase().includes(q) || String(n.data?.ip ?? '').includes(q))
      .map(n => ({ id: n.id }));
    if (matchedIds.length === 0) return;
    const timer = setTimeout(() => {
      reactFlowInstance.fitView({ nodes: matchedIds, padding: 0.5, duration: 300 });
    }, 300);
    return () => clearTimeout(timer);
  }, [searchQuery]); // eslint-disable-line react-hooks/exhaustive-deps

  const handlePrefChange = useCallback((nodeId: string, key: keyof NodePrefs, value: any) => {
    snapshot();
    setNodePrefs(prev => {
      const existing = prev[nodeId] || {};
      let next: AllNodePrefs;
      if (value === null || value === undefined || value === false) {
        const updated = { ...existing };
        delete updated[key];
        next = Object.keys(updated).length > 0
          ? { ...prev, [nodeId]: updated }
          : { ...prev };
        if (!Object.keys(updated).length) delete next[nodeId];
      } else {
        next = { ...prev, [nodeId]: { ...existing, [key]: value } };
      }
      const updatedPrefs = next[nodeId] || {};
      updateNodePrefs(projectId, nodeId, updatedPrefs);
      // Targeted single-node update instead of waiting for the full useEffect pass
      const dataKey = key === 'icon' ? 'customIcon' : key;
      reactFlowInstance.updateNodeData(nodeId, { [dataKey]: value || null });
      return next;
    });
  }, [projectId, reactFlowInstance, snapshot]);

  const handleLegendUpdate = useCallback(async (items: LegendItem[]) => {
    await updateLegendItems(projectId, items);
    queryClient.setQueryData(['diagram', projectId, currentViewId], (old: DiagramData | undefined) =>
      old ? { ...old, legend_items: items } : old
    );
  }, [projectId, queryClient, currentViewId]);

  const getContextMenuItems = useCallback(() => {
    if (!contextMenu) return [];
    const items: { label: string; onClick: () => void; danger?: boolean }[] = [];

    if (contextMenu.kind === 'selection') {
      const count = selectedNodeIds.length;
      if (count > 0) {
        items.push({
          label: `Remove ${count} ${count === 1 ? 'item' : 'items'} from Diagram`,
          onClick: () => handleBulkRemove(),
          danger: true,
        });
      }
      return items;
    }

    if (contextMenu.kind === 'edge') {
      items.push({
        label: 'Delete Connection',
        onClick: async () => { if (await confirm('Delete this connection?')) handleDeleteEdge(contextMenu.edgeId); },
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'annotation') {
      const annotationId = parseInt(contextMenu.nodeId.replace('annotation-', ''));
      items.push({
        label: 'Delete Text',
        onClick: async () => { if (await confirm('Delete this annotation?')) handleAnnotationDelete(annotationId); },
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'image') {
      const imageId = parseInt(contextMenu.nodeId.replace('image-', ''));
      items.push({
        label: 'Delete Image',
        onClick: async () => { if (await confirm('Delete this image?')) handleImageDelete(imageId); },
        danger: true,
      });
      return items;
    }

    if (contextMenu.nodeType === 'device') {
      const deviceId = parseInt(contextMenu.nodeId.replace('device-', ''));
      items.push({ label: 'Open Device Page', onClick: () => navigate(`${base}/devices/${deviceId}`) });
      items.push({
        label: 'Set Custom Icon',
        onClick: () => { iconTargetDeviceRef.current = deviceId; iconFileInputRef.current?.click(); },
      });
      const hasOverride = diagramData?.device_icon_overrides?.includes(deviceId);
      if (hasOverride) {
        items.push({
          label: 'Reset Icon',
          onClick: async () => {
            if (!await confirm('Reset this icon to default?')) return;
            try {
              await deleteDeviceIconOverride(projectId, deviceId);
              queryClient.invalidateQueries({ queryKey: ['diagram', projectId, currentViewId] });
            } catch (err) { toast(err instanceof Error ? err.message : 'Failed to reset icon', 'error'); }
          },
        });
      }
    }

    items.push({
      label: 'Remove from Diagram',
      onClick: () => handleRemoveFromDiagram(contextMenu.nodeId, contextMenu.nodeType as 'device' | 'subnet'),
      danger: true,
    });

    return items;
  }, [contextMenu, base, navigate, handleRemoveFromDiagram, handleBulkRemove, selectedNodeIds, handleAnnotationDelete, handleImageDelete, handleDeleteEdge, confirm, diagramData, projectId, queryClient, currentViewId, toast]);

  // Devices not yet on diagram
  const diagramDeviceIds = new Set(diagramData?.devices.map(d => d.id) || []);
  const unplacedDevices = allDevices?.filter(d => !diagramDeviceIds.has(d.id)) || [];

  const diagramSubnetIds = new Set(diagramData?.subnets.map(s => s.id) || []);
  const unplacedSubnets = allSubnets?.filter(s => !diagramSubnetIds.has(s.id)) || [];

  const selectedPrefs = selectedElement ? nodePrefs[selectedElement.id] || {} : {};

  return (
    <div className="diagram-page">
      <div className="page-header">
        <h2>Network Diagram</h2>
      </div>

      <DiagramToolbar
        projectSlug={project.slug}
        views={views}
        activeViewId={currentViewId ?? diagramData?.current_view_id}
        setCurrentViewId={setCurrentViewId}
        viewMenuOpen={viewMenuOpen}
        setViewMenuOpen={setViewMenuOpen}
        setEditingView={setEditingView}
        setEditingViewName={setEditingViewName}
        onCreateView={handleCreateView}
        locked={locked}
        setLocked={setLocked}
        showLockHint={showLockHint}
        addDeviceOpen={addDeviceOpen}
        setAddDeviceOpen={setAddDeviceOpen}
        addSubnetOpen={addSubnetOpen}
        setAddSubnetOpen={setAddSubnetOpen}
        addDeviceId={addDeviceId}
        setAddDeviceId={setAddDeviceId}
        addSubnetId={addSubnetId}
        setAddSubnetId={setAddSubnetId}
        unplacedDevices={unplacedDevices}
        unplacedSubnets={unplacedSubnets}
        onAddDevice={handleAddDevice}
        onAddSubnet={handleAddSubnet}
        placingAnnotation={placingAnnotation}
        onAddAnnotation={handleAddAnnotation}
        imageFileInputRef={imageFileInputRef}
        setImageLibraryOpen={setImageLibraryOpen}
        selectMode={selectMode}
        setSelectMode={setSelectMode}
        showGrid={showGrid}
        setShowGrid={setShowGrid}
        showEdges={showEdges}
        setShowEdges={setShowEdges}
        showCredentials={showCredentials}
        setShowCredentials={setShowCredentials}
        showAv={showAv}
        setShowAv={setShowAv}
        showAgents={showAgents}
        setShowAgents={setShowAgents}
        showLegend={showLegend}
        setShowLegend={setShowLegend}
        showMinimap={showMinimap}
        setShowMinimap={setShowMinimap}
        onAutoLayoutGrid={handleAutoLayoutGrid}
        onFitView={() => reactFlowInstance.fitView({ duration: 300 })}
        exportMenuOpen={exportMenuOpen}
        setExportMenuOpen={setExportMenuOpen}
        onExportPng={handleExportPng}
        onExportSvg={handleExportSvg}
        onExportDiagramJson={handleExportDiagramJson}
        importFileRef={importFileRef}
        onImportDiagram={handleImportDiagram}
        onUndo={handleUndo}
        onRedo={handleRedo}
        canUndo={canUndo}
        canRedo={canRedo}
        searchQuery={searchQuery}
        setSearchQuery={setSearchQuery}
        typeFilter={typeFilter}
        typeFilterMenuOpen={typeFilterMenuOpen}
        setTypeFilterMenuOpen={setTypeFilterMenuOpen}
        onToggleTypeFilter={toggleTypeFilter}
        onClearTypeFilter={clearTypeFilter}
      />

      {locked && showLockHint && (
        <div className="diagram-lock-hint">
          <Lock size={13} />
          <span>The diagram is <strong>locked</strong> — click the lock icon to unlock and start editing.</span>
          <button className="diagram-lock-hint-dismiss" onClick={dismissLockHint} aria-label="Dismiss">×</button>
        </div>
      )}

      <div className="diagram-layout">
        <div className="diagram-container" ref={containerRef} style={{ position: 'relative' }} data-placing={placingAnnotation ? 'true' : undefined} data-connecting={isConnecting ? 'true' : undefined} data-locked={locked ? 'true' : undefined}>
          <span className={`diagram-save-status diagram-save-status-${saveStatus}`} style={selectedElement ? { right: '290px' } : undefined}>
            {saveStatus === 'saving' && 'Saving…'}
            {saveStatus === 'saved' && '✓ Saved'}
          </span>
          {displayNodes.length === 0 && diagramData && (
            <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', zIndex: 5, textAlign: 'center', color: 'var(--color-text-muted)', pointerEvents: 'auto' }}>
              <p style={{ fontSize: '1.1rem', marginBottom: '0.5rem' }}>This diagram is empty.</p>
              <p style={{ fontSize: '0.85rem', marginBottom: '1rem' }}>Use the toolbar to add devices and subnets, or auto-generate from your inventory.</p>
            </div>
          )}
          <ReactFlow
            nodes={displayNodes}
            edges={showEdges ? edges : []}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            onConnectStart={onConnectStart}
            onConnectEnd={onConnectEnd}
            onNodeClick={onNodeClick}
            onEdgeClick={onEdgeClick}
            onPaneClick={onPaneClick}
            onNodeContextMenu={onNodeContextMenu}
            onEdgeContextMenu={onEdgeContextMenu}
            onSelectionContextMenu={onSelectionContextMenu}
            onReconnectStart={locked ? undefined : onReconnectStart}
            onReconnect={locked ? undefined : onReconnect}
            onReconnectEnd={locked ? undefined : onReconnectEnd}
            onSelectionChange={onSelectionChange}

            onMoveEnd={onMoveEnd}
            nodeTypes={nodeTypes}
            deleteKeyCode={null}
            proOptions={{ hideAttribution: true }}
            fitView={!savedViewport}
            defaultViewport={savedViewport || undefined}
            snapToGrid
            snapGrid={[15, 15]}
            nodesDraggable={!locked}
            nodesConnectable={!locked}
            elementsSelectable={!locked}
            selectionOnDrag={!locked && selectMode}
            panOnDrag={locked ? [0, 1] : selectMode ? [1] : [0, 1]}
          >
            <Controls showInteractive={false} />
            {showMinimap && <MiniMap pannable zoomable />}
            {showGrid && <Background variant={BackgroundVariant.Dots} gap={15} size={1} />}
          </ReactFlow>
          {showLegend && (
            <DiagramLegend items={diagramData?.legend_items ?? []} onUpdate={handleLegendUpdate} />
          )}
          {contextMenu && (
            <ContextMenu
              position={{ x: contextMenu.x, y: contextMenu.y }}
              items={getContextMenuItems()}
              onClose={() => setContextMenu(null)}
            />
          )}
          {selectedNodeIds.length > 1 && (
            <div className="diagram-bulk-bar">
              <span>{selectedNodeIds.length} selected</span>
              <button className="btn btn-sm btn-danger" onClick={handleBulkRemove}>Remove from Diagram</button>
            </div>
          )}
        </div>
        {selectedElement && (
          <PropertiesPanel
            selected={selectedElement}
            onClose={() => setSelectedElement(null)}
            nodePrefs={selectedPrefs}
            onPrefChange={(key: keyof NodePrefs, value: any) => handlePrefChange(selectedElement.id, key, value)}
            onConnectionUpdate={handleConnectionUpdate}
            projectBase={base}
            locked={locked}
          />
        )}
      </div>
      <input ref={imageFileInputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={handleImageFileSelected} />
      <input ref={iconFileInputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={handleIconFileSelected} />
      <ImageLibraryModal
        projectId={projectId}
        open={imageLibraryOpen}
        onClose={() => setImageLibraryOpen(false)}
        onPlaceImage={handlePlaceLibraryImage}
      />
      {editingView && createPortal(
        <div className="confirm-overlay" onClick={() => setEditingView(null)}>
          <div className="confirm-dialog" onClick={e => e.stopPropagation()}>
            <div className="confirm-dialog-title">Edit View</div>
            <div className="confirm-dialog-message">
              <div className="form-group">
                <label>Name</label>
                <input
                  type="text"
                  value={editingViewName}
                  onChange={e => setEditingViewName(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Enter' && editingViewName.trim() && editingViewName.trim() !== editingView.name) {
                      handleRenameView(editingView.id, editingView.name, editingViewName.trim());
                      setEditingView(null);
                    }
                    if (e.key === 'Escape') setEditingView(null);
                  }}
                  autoFocus
                />
              </div>
            </div>
            <div className="confirm-dialog-actions" style={{ justifyContent: 'space-between' }}>
              <button
                className="btn btn-danger btn-sm"
                onClick={async () => { setEditingView(null); await handleDeleteView(editingView.id); }}
              >
                <Trash2 size={14} /> Delete View
              </button>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button className="btn btn-secondary" onClick={() => setEditingView(null)}>Cancel</button>
                <button
                  className="btn btn-primary"
                  disabled={!editingViewName.trim() || editingViewName.trim() === editingView.name}
                  onClick={() => { handleRenameView(editingView.id, editingView.name, editingViewName.trim()); setEditingView(null); }}
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}

function DiagramErrorFallback(error: Error) {
  const handleReset = () => {
    // Clear all per-project diagram viewport keys so a bad saved viewport
    // can't trap the user on reload.
    try {
      for (let i = localStorage.length - 1; i >= 0; i--) {
        const key = localStorage.key(i);
        if (key && key.startsWith('diagram-viewport-')) localStorage.removeItem(key);
      }
    } catch {
      // ignore storage errors
    }
    window.location.reload();
  };
  return (
    <div className="card" style={{ margin: '2rem auto', maxWidth: 520, textAlign: 'center', padding: '2rem' }}>
      <h2 style={{ marginBottom: '0.5rem' }}>Diagram failed to render</h2>
      <p style={{ color: 'var(--color-text-secondary)', marginBottom: '1rem', fontSize: '0.9rem' }}>
        {error.message || 'An unexpected error occurred while rendering the diagram.'}
      </p>
      <button className="btn btn-primary" onClick={handleReset}>Reset view</button>
    </div>
  );
}

export default function NetworkDiagram() {
  return (
    <ErrorBoundary fallback={(err) => DiagramErrorFallback(err)}>
      <ReactFlowProvider>
        <NetworkDiagramInner />
      </ReactFlowProvider>
    </ErrorBoundary>
  );
}
